### ISSUE TITLE
ng lint crashes after adding TS indent rule

### ISSUE THREAD

**Issue by crafton** [angular-eslint/angular-eslint#101]
**ngular-eslint version:** 0.0.1-alpha.32
**angular version**: 9.1.9

I realize that adding the following indent rule causes linting to crash: `'@typescript-eslint/indent': ['error', 4],`. Removing the rule, everything works as expected.  I also realize deleting the content of the html root component results in the linter working as expected.

eslint config: https://github.com/crafton/angular-eslint-test/blob/master/.eslintrc.js
offending html: https://github.com/crafton/angular-eslint-test/blob/master/projects/external-config-tester/src/app/app.component.html

**Steps to reproduce:**

1. Check out: https://github.com/crafton/angular-eslint-test
2. Run `npm run lint` or `ng lint`

Is this a bug or have I configured something incorrectly?

Appreciate the work you're doing here!!

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by crafton** [comment]
> Thank you for submitting the issue, please see [#86 (comment)](https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652) for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

Really sorry to hear that. My condolences to you and your family.

**Comment by JamesHenry** [comment]
Thank you, @crafton, I really appreciate that.

Please could you try out the latest version I just published `v0.1.0-beta.1` and see if this resolve the issue - it fundamentally updates the builder and requires the latest version of major dependencies, such as Angular, TypeScript and ESLint.

Feel free to reopen if it does not resolve the issue
