### ISSUE TITLE
ng lint without a specified project throws out of memory

### ISSUE THREAD

**Issue by frederikdekegel** [angular-eslint/angular-eslint#102]
While working in a nrwl monorepo, running ng lint on a single project, e.g. ng lint myProject, works fine for every project in the repo. 

However, if ng lint is ran without a specified project, e.g. ng lint, and thus linting all projects, out of memory exceptions are throw.

Seems to me like the memory consumpted by eslint and most probably @typescript-eslint is not released when the linting of a project is finished before starting to lint the next project.

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Thanks again for the report @frederikdekegel - the Nrwl folks actually use their own `builder` implementation (which is the most relevant package here as it determines how ESLint is invoked), they do not use the one provided by this project.

Therefore, it would be most appropriate to report this on the Nx github.

**Comment by frederikdekegel** [comment]
@JamesHenry, your assumption as I am using the eslint builder from nx is unfortunately wrong. As the nx eslint builder was causing me even more problems, I switched out the nx eslint builder for the builder provides by this repo which for me at least works better 😊

The only thing I cannot do is run ng lint on the whole Angular workspace. The fact that nx is the game in my repo is not relevant for this issue. 

Could you please reconsider to reilen this issue?

Thank you in avance 😊

**Comment by eMuonTau** [comment]
I am not using Nx and i am getting out of memory exceptions too.

**Comment by JamesHenry** [comment]
@frederikdekegel and @eMuonTau please can you migrate to `v0.2.0-beta.1`? It was added in https://github.com/angular-eslint/angular-eslint/pull/120

It is a major change to address specifically the issues you have mentioned. You will see that the integration-tests now include lots of separate projects (and you can also see in there how different the config now is).

There is a schematic available now in that same PR to take a current Angular CLI project and convert it to the appropriate configuration.

If you still have issues with `v0.2.0-beta.1` please open a fresh issue with as much information as possible.

Thanks all 🙏

**Comment by tripleequal** [comment]
> I am not using Nx and i am getting out of memory exceptions too.

+1

Running 0.6.0-beta.0

**Comment by SSmale** [comment]
Also getting OOM with the stack track trace looking like that in https://github.com/angular-eslint/angular-eslint/issues/115#issue-672740514.

I am running it against a vanilla angular workspace with 3 projects using the latest version

**Comment by zbarbuto** [comment]
Was having this issue as well with Node 12.x. Updating to 14.x resolved memory issue for me.
