### ISSUE TITLE
[i18n] Disable i18n rule for inline templates in tests but not source

### ISSUE THREAD

**Issue by rajsite** [angular-eslint/angular-eslint#1023]
**Description and reproduction of the issue**

Following the discussion in https://github.com/angular-eslint/angular-eslint/issues/105#issuecomment-761537457 I am able to target inline templates for the i18n rule by being aware of the internal filename pattern of `*inline-template-*.component.html`.

However, I'd like to target inline templates based on the original source file name so that I can enable the `i18n` rule for inline templates in components with the name `*.component.ts` and disable the `i18n` rule for inline templates in tests with the name `*.spec.ts`.

```js
overrides: [
    {
        files: [
            '*.html'
        ],
        extends: ['plugin:@angular-eslint/template/recommended'],
        rules: {
            '@angular-eslint/template/i18n': ['error', {
                checkAttributes: false,
                checkId: false
            }],
        },
    },
    {
        files: [
            // How to target the inline-template of just *.spec.ts files?
            '*inline-template-*.component.html'
        ],
        rules: {
            '@angular-eslint/template/i18n': 'off'
        }
    },
]

```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `12.7.0` |
| `@angular-eslint/template-parser`         | `12.7.0` |
| `@typescript-eslint/parser`               | `4.33.0` |
| `ESLint`                                  | `7.32.0` |
| `node`                                    | `16.14.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.14
Node: 16.14.0 (Unsupported)
Package Manager: npm 8.12.0
OS: win32 x64

Angular: 12.2.14
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cdk                    12.2.13
@angular/material               12.2.13
@schematics/angular             12.2.14
ng-packagr                      12.2.5
rxjs                            7.5.4
typescript                      4.3.5

Warning: The current version of Node (16.14.0) is not supported by Angular.
```

- [x] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here. I have not but I can see the naming convention for the [inlineTemplateTmpFilename](https://github.com/angular-eslint/angular-eslint/blob/8b89ec7ba1ebdd5a29914bac457387d4b65bd691/packages/eslint-plugin-template/src/processors.ts#L158) has not changed

**Comment by JamesHenry** [comment]
Hi @rajsite this is now possible in v14, please take a look at the release notes for more information https://github.com/angular-eslint/angular-eslint/releases/tag/v14.0.0

Many thanks!

**Comment by rgant** [comment]
In case anyone else finds this issue (had to use Google, GitHub issue search wouldn't match at the time) this is how I solved this problem in my project using an eslint.config.js:

```js
  {
    files: ['**/*.spec.ts*.html'],
    rules: { '@angular-eslint/template/i18n': 'off' }
  },
```

I needed to add the `**/` to the beginning unlike what [rajsite did](https://github.com/rbell517/ni-javascript-styleguide/blob/414fcd6556d7839e466f5a7f997b57aaf06d2f7f/tests/angular/custom-ignore-attributes/.eslintrc.js) however that file is gone now and I didn't quickly see what their current solution is.
