### ISSUE TITLE
When Adding Linter To An Existing Project, It Assumes The Code Is In a Directory Named src

### ISSUE THREAD

**Issue by mylifeandcode** [angular-eslint/angular-eslint#1048]
I recently migrated a legacy app originally created manually with Angular 2 (not generated by the CLI) to an Angular CLI app using Angular 13. After this work was done, I added the linter by running _ng lint_. The CLI prompted me about adding the required libraries, etc, to enable the linter, and I accepted. Everything seemed to install correctly.

However, afterward, when trying to run the linter, I got an error saying that the setup was incorrect (original error message has been lost). I found the cause was that, in _angular.json_, the linter was configured to use the _src_ folder (as Angular apps do) as the location of the code (lint->options->lintFilePatterns value). However, in the crazy old app I'd updated, the location of the source code was not under a folder named _src_.

I understand this is probably a rare edge case, and I regret not naming that source folder _src_ to be consistent (hindsight!). If it would be possible for the process that sets up the linter to use the _sourceRoot_ value in _angular.json_ to determine the correct folder that might be helpful. This is a minor issue.

**Comment by JamesHenry** [comment]
Thanks @mylifeandcode, agreed it's an edge case but was also very quick to address so I've done that now and it will be released as part of the standard canary release from `main` shortly if you wanted to use it straight away
