### ISSUE TITLE
inline template temp file created by angular-eslint causes error when prettier is also used

### ISSUE THREAD

**Issue by abdes** [angular-eslint/angular-eslint#105]
### Context
setup with angular-eslint and prettier, with eslint config having:
```
  extends: [
    'plugin:prettier/recommended',
    'plugin:@angular-eslint/recommended',
  ],
```
package.json has prettier related modules:
```
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "2.0.5",
```

Angular component with inline template, in file : ...\test\libs\ui\components\src\lib\icons\inline-icon.component.ts
```typescript

@Component({
  selector: 'hc-inline-icon',
  template: ` <ng-content></ng-content> `,
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InlineIconComponent {
}
 ```

### Error
An unhandled exception occurred: ENOTDIR: not a directory, scandir '....\test\libs\ui\components\src\lib\icons\inline-icon.component.ts'
Occurred while linting ....\test\libs\ui\components\src\lib\icons\inline-icon.component.ts\1_inline-template.component.html:3

```
[error] Error: ENOTDIR: not a directory, scandir '...\test\libs\ui\components\src\lib\icons\inline-icon.component.ts'
Occurred while linting ...\test\libs\ui\components\src\lib\icons\inline-icon.component.ts\1_inline-template.component.html:3
    at Object.readdirSync (fs.js:876:3)
    at traverseFolder (...\test\node_modules\prettier\index.js:21298:20)
    at findRoot (...\test\node_modules\prettier\index.js:21314:10)
    at maybeParse (...\test\node_modules\prettier\index.js:21338:16)
    at editorconfigSyncNoCache (...\test\node_modules\prettier\index.js:21352:33)
    at editorconfigSyncNoCache (...\test\node_modules\prettier\index.js:16864:26)
    at _resolveConfig (...\test\node_modules\prettier\index.js:24281:68)
    at Function.resolveConfig.sync (...\test\node_modules\prettier\index.js:24308:42)
    at Program (...\test\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js:174:40)
    at ...\test\node_modules\eslint\lib\linter\safe-emitter.js:45:58

```

### Expected behavior
It should be possible to combine angular-eslint with any other eslint extensions, including prettier.

### Workaround

1. Remove prettier - unacceptable
2. Just do not use inline templates - not cool :-)

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JakeFDev** [comment]
Still in issue as of 2021. 

Luckily my project only had one inline template, so i've just added a rule to disallow inline templates and moved that one out.

**Comment by NicholaAlkhouri** [comment]
I am also having this problem, basically in spec.ts files where we usually write some simple inline templates.

**Comment by matusko89** [comment]
Same problem here, but funny enough somehow I am able to run lint fine but every other team member experiences this problem
my settings
`{
    "root": true,
    "ignorePatterns": [
        "projects/**/*"
    ],
    "overrides": [
        {
            "files": [
                "*.ts"
            ],
            "parserOptions": {
                "project": [
                    "tsconfig.json",
                    "e2e/tsconfig.json"
                ],
                "createDefaultProgram": true
            },
            "extends": [
                "plugin:@angular-eslint/recommended",
                "plugin:@angular-eslint/template/process-inline-templates",
                "eslint:recommended",
                "plugin:@typescript-eslint/recommended",
                "plugin:@typescript-eslint/recommended-requiring-type-checking",
                "prettier/@typescript-eslint",
                "plugin:prettier/recommended"
            ],
            "rules": {
                "@angular-eslint/component-selector": [
                    "error",
                    {
                        "type": "element",
                        "prefix": "",
                        "style": "kebab-case"
                    }
                ],
                "@angular-eslint/directive-selector": [
                    "error",
                    {
                        "type": "attribute",
                        "prefix": "",
                        "style": "camelCase"
                    }
                ],
                "@typescript-eslint/explicit-member-accessibility": [
                    "off",
                    {
                        "accessibility": "explicit"
                    }
                ],
                "@typescript-eslint/no-floating-promises": [
                    "off"
                ],
                "arrow-parens": [
                    "off",
                    "avoid"
                ],
                "import/order": "off"
            }
        },
        {
            "files": [
                "*.html"
            ],
            "extends": [
                "plugin:@angular-eslint/template/recommended",
                "prettier/@typescript-eslint",
                "plugin:prettier/recommended"
            ],
            "rules": {}
        }
    ]
}
`

**Comment by JamesHenry** [comment]
Please can you try ignoring these "special files" (that are temporarily created behind the scenes by the processing logic within ESLint) within your prettier configs?

i.e. in `.prettierignore` something like:

```
*inline-template.component.html
```

Or whatever the syntax would be

If that is successful, then we can add it to the docs.

Thanks!

**Comment by matusko89** [comment]
> Please can you try ignoring these "special files" (that are temporarily created behind the scenes by the processing logic within ESLint) within your prettier configs?
> 
> i.e. in `.prettierignore` something like:
> 
> ```
> inline-template-*.component.html
> ```
> 
> Or whatever the syntax would be to get them to ignore this pattern:
> 
> ```
> const inlineTemplateTmpFilename = `inline-template-${++id}.component.html`;
> ```
> 
> That is how we create those names. When this issue was first opened we didn't support multiple inline templates in a single file, but now we do which is why that incrementing id is in there.
> 
> If that is successful, then we can add it to the docs.
> 
> Thanks!

hmmm I tried to add `.prettierignore`, `.eslintignore` and also I tried adding it to `ignorePatterns` in .eslintrc with many different patterns for example `**/*.ts/*` witch should match the path I am receiving in the error output but with no result

 ENOTDIR: not a directory, stat '/srv/www/ipsom/mkopernicky/web-client/src/app/widget/widget-base/widget-base.component.ts/1_inline-template-1.component.html'

**Comment by NicholaAlkhouri** [comment]
Same here, ignoring the files didn't work, here is the stack:

```
[error] Error: ENOTDIR: not a directory, stat '*******/1_inline-template-1.component.html'
Occurred while linting ********/1_inline-template-1.component.html:2
    at Object.statSync (fs.js:1035:3)
    at isTypeSync (****/node_modules/prettier/third-party.js:9748:46)
    at getDirectorySync (****/node_modules/prettier/third-party.js:9802:62)
    at ExplorerSync.searchSync (****/node_modules/prettier/third-party.js:9950:66)
    at _resolveConfig (****/node_modules/prettier/index.js:25592:50)
    at Function.resolveConfig.sync (****/node_modules/prettier/index.js:25621:42)
    at Program ****/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:167:40)
    at****/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (****/node_modules/eslint/lib/linter/safe-emitter.js:45:38)


```

**Comment by tbadlov** [comment]
As a workaround you can add the pattern `*inline-template-*.component.html` to your `excludedFiles` from `.eslintrc.json` file:

```
{
      "files": ["*.html"],
      "excludedFiles": ["*inline-template-*.component.html"],
      "extends": [
        "plugin:@angular-eslint/template/recommended",
        "prettier/@typescript-eslint",
        "plugin:prettier/recommended"
      ],
      "rules": {}
    }
```

That said, it should be looked at.

**Comment by JamesHenry** [comment]
I have had a look into this and @tbadlov answer is nearly correct.

`eslint-plugin-prettier` is separately doing some file resolution behind the scenes - that is not something we can control.

I believe In order to get the full range of options working, namely:
- ESLint + prettier together should work on Components with external templates
- ESLint + prettier together should work on the external template HTML files themselves
- ESLint + prettier together should work on Components with inline templates

...the key point is that if you want to use `eslint-plugin-prettier` in this way, you should have **two** overrides for HTML:

Here is a fully working (tested in VSCode and on the command line via `ng lint`) example:

**.eslintrc.json**

```jsonc
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json", "e2e/tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates",
        "plugin:prettier/recommended"
      ],
      "rules": {}
    },
    // NOTE: I AM NOT APPLYING PRETTIER HERE
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {}
    },
    // NOTE: I AM NOT APPLYING ANGULAR-ESLINT TEMPLATE HERE
    {
      "files": ["*.html"],
      "excludedFiles": ["*inline-template-*.component.html"],
      "extends": ["plugin:prettier/recommended"],
      "rules": {
        // NOTE: I AM OVERRIDING THE DEFAULT CONFIG TO ALWAYS SET THE PARSER TO HTML
        "prettier/prettier": ["error", { "parser": "html" }]
      }
    }
  ]
}
```

I set the parser within the `prettier/prettier` rule config because in my testing the inference wasn't 100% accurate and we know based on our usage above that that override block will only ever be run on HTML files.

PS I am using the latest `eslint-plugin-prettier` and as of v8 it has changed its behaviour -  you no longer need `"prettier/@typescript-eslint"` at all

**Screenshots from testing in VSCode**
<br>

![image](https://user-images.githubusercontent.com/900523/110239717-44923880-7f40-11eb-8099-d2ebbdadd109.png)

![image](https://user-images.githubusercontent.com/900523/110239789-bb2f3600-7f40-11eb-94a2-acf3f1722c8c.png)

**Comment by JamesHenry** [comment]
I will add a section to the README which covers this case in order to formally close this issue

**Comment by JamesHenry** [comment]
The README has been updated

**Comment by snebjorn** [comment]
@JamesHenry should the prettier parser be set to html regardless of the project type?

I was thinking it should be set to `angular` or `vue` for those projects

**Comment by JamesHenry** [comment]
I’m AFK at the moment, @snebjorn would you like to open a PR to adjust the README?
