### ISSUE TITLE
Cannot find module '@typescript-eslint/eslint-plugin' Error Angular 14

### ISSUE THREAD

**Issue by sevspo** [angular-eslint/angular-eslint#1062]
**
When trying to lint a file after running the convert schematics as described in the docs, I get:
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json#overrides[0] » plugin:@angular-eslint/ng-cli-compat » ./configs/base.json': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:..**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `13.5.0` |
| `@typescript-eslint/parser`        | `5.29.0` |
| `ESLint`                           | `8.18.0` |
| `node`                             | `16.15.3` |

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
angular-eslint v14.0.0 was just published and is available on npm

Please check out the release notes for guidance: https://github.com/angular-eslint/angular-eslint/releases/tag/v14.0.0

Many thanks 🙏
