### ISSUE TITLE
Suggestion/ Feature Request: Plugin for SonarQube

### ISSUE THREAD

**Issue by sisohs** [angular-eslint/angular-eslint#107]
Just a feature request to make a SonarQube plugin for this, so that it can be used for generating reports that can be visualized on Sonar Server.
Please let me know if it is in plans or ways to integrate in Sonar Rules set :)

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Thanks for the write up @sisohs - I think for now something like this should be maintained by the community that uses it. The current focus is on core features which are common to most/all Angular projects, and for a 3rd party tool like this it is not the case.

Cheers!
