### ISSUE TITLE
schematicCollections is now renamed to defaultCollection in the angular.json

### ISSUE THREAD

**Issue by wtang-8** [angular-eslint/angular-eslint#1076]
In the documentation ([README.md](https://github.com/angular-eslint/angular-eslint/blob/main/README.md)), we can modify the key schematicCollections to defaultCollection instead. The "ng add @angular-eslint/schematics" seems to modify angular.json differently now.

```json
  "cli": {
    "schematicCollections": ["@angular-eslint/schematics"]
  }
```

**Comment by JamesHenry** [comment]
Hi @wtang-8, actually it's exactly the opposite way around.

In v14 of the Angular CLI, latest major version, `defaultCollection` is deprecated and `schematicCollections` should be used instead.

The README always reflects the correct usage for the currently supported major version. In this case it is v14, and which was released with the change to use `schematicCollections`: https://github.com/angular-eslint/angular-eslint/releases/tag/v14.0.0
