### ISSUE TITLE
 Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "~0.900.2", would install "0.1000.1").

### ISSUE THREAD

**Issue by denys5dev** [angular-eslint/angular-eslint#108]
1. run -  ng update @angular/cli (v10)
2. Result:
 Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "~0.900.2", would install "0.1000.1").       
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.

Can you update "@angular-devkit/build-angular to 0.1000.0 + version ? it will fix issue related with Angular 10 migrations?

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Thanks again for the report @denys5dev.

Please could you try out the latest version I just published `v0.1.0-beta.1`, it has explicitly added support for Angular 10
