### ISSUE TITLE
Case `no-useless-constructor` with DI in Angular

### ISSUE THREAD

**Issue by sahilbabbar** [angular-eslint/angular-eslint#1081]
ESLint throws `no-useless-constructor` error for the following code, rather it is a correct implementation in Angular(using DI design pattern) to inject dependencies:

```
export class ButtonComponent {
  constructor(private buttonService: ButtonService) {}
}
```

It is treating it like a generic TS code block and what can we do to make it realize that it's valid Angular syntax?

**Comment by JamesHenry** [comment]
Hi @sahilbabbar you should be using the rule from `@typescript-eslint`, not the ESLint core rule. The syntax in question is TS specific and so ESLint has no understanding of it.

You can see how to use it here:

https://typescript-eslint.io/rules/no-useless-constructor/#how-to-use

**Comment by sahilbabbar** [comment]
@JamesHenry thanks for pointing it out. I had seen this before, but was avoiding to introduce another dependency in my projects, so was looking for a native way(native to ESLint).
