### ISSUE TITLE
An unhandled exception occurred: Cannot find module 'nx/src/config/workspaces' since v14.0.1

### ISSUE THREAD

**Issue by jnizet** [angular-eslint/angular-eslint#1087]
**Description and reproduction of the issue**

See https://github.com/jnizet/decouvertes-nature/pull/284:

- checkout the branch of the PR (renovate/angular-eslint-monorepo)
- run `yarn`
- run `yarn lint`

It passed with version 14.0.0. With version 14.0.1, it fails with the following error:

```
An unhandled exception occurred: Cannot find module 'nx/src/config/workspaces'
Require stack:
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@nrwl/devkit/index.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular-eslint/builder/dist/compat.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular-devkit/architect/node/index.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/src/command-builder/architect-command-module.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/src/commands/build/cli.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/src/command-builder/command-runner.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/lib/cli/index.js
- /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/@angular/cli/lib/init.js
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `14.0.1` |
| `ESLint`                           | `8.19.0` |
| `node`                             | `14.19.3` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 14.0.5
Node: 14.19.3
Package Manager: yarn 1.22.19 
OS: darwin x64

Angular: 14.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.5
@angular-devkit/build-angular   14.0.5
@angular-devkit/core            14.0.5
@angular-devkit/schematics      14.0.5
@angular/fire                   7.4.1
@schematics/angular             14.0.5
rxjs                            7.5.5
typescript                      4.7.4
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by hardmaster92** [comment]
I confirm the same issue using NPM after updating to version 14.0.1

**Comment by jnizet** [comment]
Thanks for the quick fix and release @JamesHenry

**Comment by JamesHenry** [comment]
@jnizet thanks!

**Comment by anton-white** [comment]
Hello guys,
thanks for all your great job on making Eslint available to Angular.
I'm working on the project which doesn't use NX.
However, after upgrading from 14.0 to newer version, the entire NX package gets installed.
Can this be avoided?

**Comment by jerone** [comment]
NX is added as an `dependency` here only: https://github.com/angular-eslint/angular-eslint/blob/89459be35a922ba5f6146636b02cee508ac88ffb/packages/builder/package.json#L23

It looks like its nowhere in the compiled source code referenced, it could be an `devDependency`.

**Comment by elcreator** [comment]
nx dependency itself causes problem with the eslint-builder crashing if some libraries have conflicting version dependencies.
