### ISSUE TITLE
[@angular-eslint/template/no-any] Disabling for a single line

### ISSUE THREAD

**Issue by AbdealiJK** [angular-eslint/angular-eslint#1089]
**Description and reproduction of the issue**
I am trying to add the rule: `@angular-eslint/template/no-any`
In most places we have stopped using `$any` but in a few places, I need to continue using it.
So, I was thinking I can disable it for those specific lines like how I would disable eslint Typescript rules.

I have the following code:
```html
<div
    class="col-12"
    [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
</div>
```

I tired:
```html
<div
    <!-- eslint-disable-next-line @angular-eslint/template/no-any -->
    class="col-12"
    [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
</div>
```
And:
```html
<!-- eslint-disable-next-line @angular-eslint/template/no-any -->
<div
    class="col-12"
    [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
</div>
```
Neither seems to be able to disable this rule for a single line.

```js
module.exports = {
    root: true,
    ignorePatterns: ['projects/**/*'],
    overrides: [
        {
            files: ['*.html'],
            plugins: ['rulesdir'],
            extends: ['plugin:@angular-eslint/template/recommended'],
            rules: {}
        }
    ]
}
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `14.0.0` |
| `@angular-eslint/template-parser`         | `14.0.0` |
| `@typescript-eslint/parser`               | `5.30.6` |
| `ESLint`                                  | `8.19.0` |
| `node`                                    | `16.13.2` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
$ npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.0.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: linux x64

Angular: 14.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@schematics/angular             14.0.5
rxjs                            7.5.5
typescript                      4.7.4
```

- [x] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by AbdealiJK** [comment]
Hi @JamesHenry Thanks for the reply.

I realize I had not written my first example correctly.

I have also tried:
```
<div
    class="col-12"
    <!-- eslint-disable-next-line @angular-eslint/template/no-any -->
    [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
</div>
```
But I cannot put a comment inside a div tag in this case - as that is invalid HTML

And we are using a formatter which refuses to let me do:
```
<!-- eslint-disable-next-line @angular-eslint/template/no-any -->
<div class="col-12" [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
</div>
```
due to line length issues and so on

So, I still seem to be stuck on how to disable this

**Comment by JamesHenry** [comment]
@AbdealiJK you switch to use the non next-line disable comment and have an opening comment and closing comment around the whole element. On mobile so can’t type out an example right now, but seems what you want is just eslint-disable and eslint-enable, not eslint-disable-next-line

**Comment by AbdealiJK** [comment]
Aha - thanks !
I was now aware I could disable and then enable eslint like this.
This worked perfectly.

Reference for any one else who may be looking for this: https://writingjavascript.com/eslint-disable-single-line-and-code-blocks

I finally did:
```
<!-- eslint-disable @angular-eslint/template/no-any -->
<div
    class="col-12"
    [formGroup]="$any(formGroup).get('arrayOfVals').at(0)">
    <!-- eslint-enable @angular-eslint/template/no-any -->
</div>
```
While I feel it is disabling "more than required" - it works out fine.
