### ISSUE TITLE
How to lint multiple angular libraries?

### ISSUE THREAD

**Issue by eestein** [angular-eslint/angular-eslint#109]
Hi, how can I setup multiple projects?
For me it's only linting the main app, the projects inside `projects` folder don't seem to be linting properly.

Here's my structure.

```
library
├── .eslintrc.json
├── angular.json
├── ...
└─┬ projects
  └─┬ myproj
    ├── ...
    ├── tsconfig.lib.json
    └── .eslintrc.json
└─┬ src
  ├── app
  ├── ...
  ├── tsconfig.app.json
```

And here's my `angular.json` file:
Internal project:

```json
"myproj": {
    "root": "projects/myproj",
    "sourceRoot": "projects/myproj/src",
    "projectType": "library",
    "prefix": "myproj",
    "schematics": {
        "@schematics/angular:component": {
            "style": "scss"
        }
    },
    "architect": {
        "build": {...},
        "test": {...},
        "lint": {
            "builder": "@angular-eslint/builder:lint",
            "options": {
                "eslintConfig": "projects/myproj/.eslintrc.json",
                "tsConfig": [
                    "projects/myproj/tsconfig.lib.json",
                    "projects/myproj/tsconfig.spec.json"
                ],
                "exclude": [
                    "**/node_modules/**",
                    "projects/myproj/schematics/**"
                ]
            }
        }
    }
}
```

Main app:
```json
"lint": {
    "builder": "@angular-eslint/builder:lint",
    "options": {
        "eslintConfig": ".eslintrc.json",
        "tsConfig": [
            "src/tsconfig.app.json",
            "src/tsconfig.spec.json"
        ],
        "exclude": [
            "**/node_modules/**"
        ]
    }
}
```

When I run `ng lint` I get errors from the main app, but not from the project. Even if I run `ng lint myproj` I get no errors, only the warnings of the excluded files, which tells me it is loading the proper `.eslintrc.json` file. I even tried to change the names of the files to confirm and it is loading the correct `.estlinrc.json`. The problem is that it doesn't lint the files inside the project only the main app.

Any ideas on what I'm doing wrong here?

**Comment by pmstss** [comment]
Do you have `defaultProject` in `angular.json`? For me with some recent ng or nx changes, only `defaultProject` is linted on `ng lint`

**Comment by eestein** [comment]
@pmstss I do, the main app is set as the `defaultProject`

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by pmstss** [comment]
For those who are using [nx](https://nx.dev): linting of all projects could be done with `nx run-many --all --target lint` (thanks to @abdes for the [hint](https://github.com/abdes/happy-coding/issues/1#issuecomment-659625899))

**Comment by JamesHenry** [comment]
Thanks again for the report @eestein, in my latest PR, and the latest version I published I have added an explicit integration-test to validate the scenario of having multiple projects in a workspace.

Please give the latest version I just published `v0.1.0-beta.1` a try!

**Comment by eestein** [comment]
@JamesHenry thank you, James! I'll test it right away :)

**Comment by eestein** [comment]
Ok, so thanks again.
I've updated to `0.1.0-beta.1` and checked your PR #38, but it's not working for me. I noticed I didn't have to change anything, was that correct? The only difference I noticed from your `angular.json` to mine was that I was using `eslintConfig`. Do you think that might be the problem?

This is my lint section on my lib's `angular.json`:

```json
"lint": {
    "builder": "@angular-eslint/builder:lint",
    "options": {
        "eslintConfig": "projects/myproj/components/.eslintrc.json",
        "tsConfig": [
            "projects/myproj/components/tsconfig.lib.json",
            "projects/myproj/components/tsconfig.spec.json"
        ],
        "exclude": [
            "**/node_modules/**",
            "projects/myproj/components/schematics/**"
        ]
    }
}
```

when I run `ng lint myproj` I get no errors, just warnings from `.spec` files, even though I added an error. I even tried adding the specific file to the `files` section on my `tsconfig` and it still wouldn't be validated. I only get warnings from specs that were skipped:

```
/Users/eestein/Documents/dev/c/xproj/projects/myproj/components/src/lib/services/scroll/viewport-ruler.service.spec.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```

I added an error in the `viewport-ruler.service.ts` file and it's not displaying. I thought the problem could've been the files not being added, that's why I added the file manually, but it doesn't seem to be the issue given the skips are being notified.

Any ideas?

**Comment by eestein** [comment]
@JamesHenry hey, I'm sorry to ping you, but since I didn't get a response I thought you maybe didn't see my previous message. Could you please take a look at it?

Thanks!

**Comment by JamesHenry** [comment]
@eestein please can you migrate to `v0.2.0-beta.1`? It was added in https://github.com/angular-eslint/angular-eslint/pull/120

It is a major change to address performance and memory issues. You will see that the integration-tests now include lots of separate projects (and you can also see in there how different the config now is).

There is a schematic available now in that same PR to take a current Angular CLI project and convert it to the appropriate configuration.

If you still have issues with `v0.2.0-beta.1` please open a fresh issue with as much information as possible.

Thanks all 🙏
