### ISSUE TITLE
[@angular-eslint/no-empty-lifecycle-method] add an option to exclude check any lifecycle methods

### ISSUE THREAD

**Issue by Korsarius** [angular-eslint/angular-eslint#1090]
**Description and reproduction of the issue**
Would it be possible to consider adding an option to the rule to disable the check for lifecycle methods (An array of excluded methods from the rule)?
For example, we use decorators for some lifecycle methods (ngOnChanges, ngOnDestroy) in the project and they are empty. I think this will be useful to many.

```JSON
{
  "rules": {
    "@angular-eslint/no-empty-lifecycle-method": ["error"]
  }
}
```

```TS
     @TrackChanges<number>('top', 'setIconTop')
     @TrackChanges<number>('right', 'setIconRight')
     @TrackChanges<boolean>('isOverlap', 'resetPosition')
     @TrackChanges<boolean>('isHighlighted', 'updateIconState')
     @TrackChanges<boolean>('enableLeftAlign', 'setIconLeft')
     ngOnChanges(changes: SimpleChanges): void {}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `12.7.0` |
| `@typescript-eslint/parser`        | `4.28.2` |
| `ESLint`                           | `^7.26.0` |
| `node`                             | `14.16.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.17
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.17
@angular-devkit/build-angular   12.2.17
@angular-devkit/core            12.2.17
@angular-devkit/schematics      12.2.17
@angular/cdk                    12.2.13
@angular/cli                    12.2.17
@schematics/angular             12.2.17
rxjs                            6.5.5
typescript                      4.3.5

Warning: The current version of Node (16.13.0) is not supported by Angular.
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @Korsarius I'm afraid I really don't think this is generically applicable enough. This seems very custom to your use-case and I would advise creating your own custom rule to handle it (or simply use an eslint-disable comment for these cases).

Adding custom decorators to one of Angular's own lifecycle hooks is not something they would encourage and correspondingly is not something that would go in this project
