### ISSUE TITLE
Performance too slow - seems to run eslint for each file instead of whole project

### ISSUE THREAD

**Issue by LiandriCorp** [angular-eslint/angular-eslint#112]
When I run eslint directly, it completes in 30 seconds. If I run with esw -w, it picks up file changes and returns within a few seconds.

When I run with ng lint, it takes over 20 minutes to complete. The output seems to indicate eslint is run separately for each file. This is due to the problem report after each file. When I run eslint directly, I get 1 problem report for the entire project.

I thought it might just be due to my migrating from tslint and the many problems still detected, but I've cleaned all the problems and `ng lint` still takes an insane amount of time. We have a few hundred .ts files, which is plenty but not crazy.

If this is due to a misconfiguration, please let me know. It's all company files so it will take some work to create a working example. Looking at the code, it appears to `executeOnFiles` one file at a time instead of all of the files.

Also, why does the angular.json config get its own exclude list? Why not at least prefer what's already in .eslintrc?

Thanks!

**Comment by xiaoxiangmoe** [comment]
How many tsconfig files in your `.eslintrc`'s `parserOptions.project` filed?

I wrote an array of tsconfig files before.
Later I changed it to a single `./tsconfig.eslint.json` file. And it works well.

**Comment by LiandriCorp** [comment]
> How many tsconfig files in your `.eslintrc`'s `parserOptions.project` filed?
> 
> I wrote an array of tsconfig files before.
> Later I changed it to a single `./tsconfig.eslint.json` file. And it works well.

Hi xiaoxiangmoe! There is only one in the  eslintrc, and only one in the directory.

I updated my first report above. It does look like in the code, it appears to do `executeOnFiles` one file at a time instead of all of the files. https://github.com/angular-eslint/angular-eslint/blob/master/packages/builder/src/index.ts#L233

**Comment by GerkinDev** [comment]
Seems to be in WIP ⇒ https://github.com/angular-eslint/angular-eslint/commit/37e4cb20269fa184c379823780ed43c2dba17db6#diff-e76bed08b97b2bf571dfb923c657c1b9L233

**Comment by JamesHenry** [comment]
Major update to the builder and configuration in v0.2.0-beta.1 - anybody that has been using this toolset so far, please read the updated docs in the README and take a look at PR #120 for when this change happened.

You will need to update your usage of the builder to match what we do in the integration-tests within this repo. In general things are a lot more straightforward to follow, and you as a user have much more fine-grained control over what gets included in your lint runs.

There is new (schematics) tooling available to take existing Angular CLI project and add all the right configuration files and architect target config for you, so you only need to worry about the actual ESLint config.

If you continue to experience issues after moving to 0.2.0, please open a new issue.

Many thanks!
