### ISSUE TITLE
"@angular-eslint/utils" package is not available on npm

### ISSUE THREAD

**Issue by abdulrahman-khankan** [angular-eslint/angular-eslint#113]
The package `@angular-eslint/utils` is used in the tests of the [eslint-plugin](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin), but when I run `npm install`, I get an error that the package is not available on npm.

I have searched for it manually on npm and couldn't find it.

Was it recently deleted or is it marked as a private package? 🤔

It is a [dev dependency](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/package.json).

```json
  "devDependencies": {
    "@angular-eslint/utils": "^0.0.1-alpha.32"
  },
```

**Comment by JamesHenry** [comment]
It's a private package, only intended to be used within this monorepo. Also note that you should be using `yarn install` rather than `npm install` for this repo. 

You can also take a look at the steps we run in our github actions if you are unsure.

Stay safe!

**Comment by abdulrahman-khankan** [comment]
@JamesHenry thank you for the quick reply.

Any chance you could make the package public and share it with the community? I like how you are doing your tests and want to use the package to test my custom rules if possible.

**Comment by JamesHenry** [comment]
@abdulrahman-khankan did you delete a comment from here requesting this package be made public? It seems to have gone for me but I got an email about it...

I don't think it's an unreasonable request, we just need to do a little tidy up first I think.

Feel free to reopen the issue to track if you would still find it useful!
