### ISSUE TITLE
[max-attributes-per-line] Support restricting the number of attributes per line

### ISSUE THREAD

**Issue by yuanyuanlife** [angular-eslint/angular-eslint#1176]
**Description and reproduction of the issue**
Please consider supporting restricting the number of attributes per line, in the cases as follows:

![Duplicated method call](https://user-images.githubusercontent.com/2127129/201302010-198e74bd-e460-4a88-97ef-867017d03c6a.png)
![Duplicated method call case 2](https://user-images.githubusercontent.com/2127129/201302210-2c72a442-b82e-434f-b31c-29dc77c8ff29.png)

Before manually formatting, both of them look like:

![1668157318717](https://user-images.githubusercontent.com/2127129/201304949-9a34fccf-896a-426b-a7c1-b75b399c5e0f.png)

Restricting the number of attributes per line could prevent bugs like this as early as posible, especially in a collaborative situation.

```JSON
{
  "rules": {
    "@angular-eslint/template/max-attributes-per-line": ["error", {
      "singleline": {
        "max": 1
      },
      "multiline": {
        "max": 1
      }
    }]
  }
}
```

Some implemetations may be helpful: 
https://github.com/vuejs/eslint-plugin-vue/blob/2479d2fc2c88963e5627902f5d09656aa77c18cb/lib/rules/max-attributes-per-line.js
 https://github.com/ecomfe/eslint-plugin-san/blob/f0e2cd29e93123084265cdc3447942da4e48bed5/lib/rules/max-attributes-per-line.js

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `14.1.2` |
| `@angular-eslint/template-parser`         | `14.1.2` |
| `@typescript-eslint/parser`               | `5.37.0` |
| `ESLint`                                  | `8.23.1` |
| `node`                                    | `16.17.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.7
Node: 16.17.1
Package Manager: pnpm 7.13.5 
OS: win32 x64

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@angular/cli                    14.2.7
@schematics/angular             14.2.7
rxjs                            7.5.7
typescript                      4.7.4
```

- [x] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @yuanyuanlife, this project's views on code formatting rules in linters is documented here: https://github.com/angular-eslint/angular-eslint/blob/main/docs/FORMATTING_RULES.md

It's therefore not something we would look to maintain under this project. If you do end up making it feel free to post on here and I will happily link out to your plugin from the README.

Many thanks! 🙏
