### ISSUE TITLE
[@angular-eslint/template/attributes-order] fixer is broken

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular-eslint/angular-eslint#1197]
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "@angular-eslint/template/attributes-order": [
          "error",
          {
            "alphabetical": false,
            "order": [
              "TEMPLATE_REFERENCE",
              "STRUCTURAL_DIRECTIVE",
              "INPUT_BINDING",
              "OUTPUT_BINDING",
              "TWO_WAY_BINDING",
              "ATTRIBUTE_BINDING"
            ]
          }
        ]
  }
}
```
Before and after `lint --fix`
```HTML
<app-button variant="primary" (click)="confirm()">{{ texts.confirmLabel }}</app-button>
<app-button (click)="confirm()" variant="primary"">{{ texts.confirmLabel }}</app-button>
```
```HTML
<div
  layout
  *ngFor="
    let control of socialLinksFormArray.controls;
    index as i;
    last as isLast;
    first as isFirst;
    trackBy: trackByValue
  "
  [attr.margin-bottom-small]="!isLast || null"
  [attr.margin-bottom-small-xx]="isLast || null"
>
                      <div
                        *ngFor=
                        ntrols;
                          index as i;
                "
                          let control of socialLinksFormArray.co                    "
           last as isLast;
                          first as isFirst;
                          trackBy: trackByValue
    [attr.margin-bottom-small]="!isLast || null"                       [attr.margin-bottom-small-xx]="isLast || null"
                        layout
                      >
```
```HTML
 <div #grip class="grip" [attr.data-column-id]="col.id"></div>
 <div #grip[attr.data-column-id]="col.id" class="grip""></div>
```
```HTML
<app-search-page-filter-group
  [@slideInOut]="animateFilterInOut"
  *ngFor="let filterGroup of filters; trackBy: trackByFilterGroup"
  ...
  
<app-search-page-filter-group
        *ngFor=
         of filters; t"let filterGroup trackBy: trackByFilterGroup"[@slideInOut]="animateFilterInOut"
         ...
```
```HTML
<td
  app-activity-subscriptions-table-item
  *ngFor="let type of types; trackBy: trackByType"
  [type]="$any(type)"
  [eventsGroup]="eventsGroup"
  [activitySubscriptions]="activitySubscriptions"
  (changeEvents)="changeEvents.emit($event)"
></td>

<td
  *ngFor=
   of types; t"let type trackBy: trackByType"[type]="$any(type)"
  [eventsGroup]="eventsGroup"
  [activitySubscriptions]="activitySubscriptions"
  (changeEvents)="changeEvents.emit($event)"
  app-activity-subscriptions-table-item
></td>
 ```
 ```HTML
 <div #chartTarget layout (mouseleave)="forceHideTooltip()"></div>
 <div #chartTarget (mouseleave)="forceHideTooltip()" layout"></div>
 ```
 ```HTML
 <div layout-vertical margin-bottom *ngIf="hires.length; else emptyState">
 <div *ngIf="hires.length; e  else emptyState" layout-verticalmargin-bottom>
```
**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `14.2.0` |
| `@angular-eslint/template-parser`         | `14.2.0` |
| `@typescript-eslint/parser`               | `5.43.0` |
| `ESLint`                                  | `8.27.0` |
| `node`                                    | `16.6.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 14.2.0
Node: 16.16.0
Package Manager: yarn 1.21.1
OS: darwin x64

Angular: 14.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.5
@angular-devkit/build-angular   14.2.5
@angular-devkit/build-webpack   0.1402.5
@angular-devkit/core            14.2.5
@angular-devkit/schematics      14.2.5
@angular/benchpress             0.3.0
@angular/cdk                    14.2.4
@angular/cli                    14.2.0
@ngtools/webpack                14.2.5
@schematics/angular             14.2.2
ng-packagr                      14.2.1
rxjs                            7.5.7
typescript                      4.8.4
webpack                         5.74.0
```

- [ ] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by joergbaier** [comment]
+1 very buggy for us as well (on 14.4.0)

**Comment by guilhermetod** [comment]
It also gets confused with animations:

![image](https://user-images.githubusercontent.com/53096593/212204856-5a83f57f-8c6b-4629-bc67-a70955e03f1e.png)

**Comment by stevebor1** [comment]
Simple repo:


**.eslintrc.json**
    
    "overrides": [{
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {
        "@angular-eslint/template/attributes-order": [
          "warn",
          {
            "alphabetical": false,
            "order": [
              "STRUCTURAL_DIRECTIVE",
              "TEMPLATE_REFERENCE",
              "ATTRIBUTE_BINDING",
              "INPUT_BINDING",
              "TWO_WAY_BINDING",
              "OUTPUT_BINDING"
            ]
          }
        ]
      }
    },]

**HTML**
`<ng-container id="issue" (click)="bar = []" *ngFor="let foo of bar; index as i"></ng-container>`

**-fix produces**
`<ng-container *ngFor=  of bar; i id="issue""let foo(click)="bar = []"ndex as i"></ng-container>`

**Comment by michaelcm** [comment]
I thought I'd add another example where the fixer really messes things up:
`"@angular-eslint/eslint-plugin-template": "15.2.1",`

```
        "@angular-eslint/template/attributes-order": [
          "error",
          {
            "alphabetical": true
          }
        ],
```

NgIf HTML
`<ng-container *ngIf="hasEntitlementAttributes() then template1 else template2">`

-fix produces
`<ng-container *ngIf="hasEntitlementAttributes() else searchEngineTemplate" e entitlementAttributeSupportedPage then>`

I feel like the fixer needs to respect that the inside of a set of double quotes should remain untouched.

Thanks!

**Comment by michaelcm** [comment]
Found one more... broke a ton of spec files. Same config as the previous message.
Inline template
`<li><input type="text" id="input"></li>`
-fix produces
`<li><inputid="input" type="text""></li>`

**Comment by jerone** [comment]
Possible duplicate, at least related, issue of getting correct LOC location: https://github.com/angular-eslint/angular-eslint/issues/384

**Comment by pmccloghrylaing** [comment]
This was an issue with structural directives where a single HTML attribute is parsed as multiple template attributes, as well as variables (for `let`). I've opened a PR that seems to fix the main issue, but I'm not sure what's causing problems with inline templates.

**Comment by abaran30** [comment]
Note: I personally have not been able to reproduce the following cases with Angular 16.0.6 and angular-eslint 16.0.3:
```html
<app-button variant="primary" (click)="confirm()">{{ texts.confirmLabel }}</app-button>
<app-button (click)="confirm()" variant="primary"">{{ texts.confirmLabel }}</app-button>
```
and
```html
<li><input type="text" id="input"></li>
<li><inputid="input" type="text""></li>
```
The fixer is fixing the attributes correctly.

**Comment by abaran30** [comment]
@pmccloghrylaing thank you for the PR.

If there's a case from this discussion that still hasn't been addressed and is reproducible, we can reopen this issue or file a new one.
