### ISSUE TITLE
Updating to Angular v15

### ISSUE THREAD

**Issue by damingerdai** [angular-eslint/angular-eslint#1205]

**Comment by vytautas-pranskunas-** [comment]
Having issue with Angular 15: ```Data path "" must NOT have additional properties()```

**Comment by JamesHenry** [comment]
v15 is the now available under the latest tag on npm, the release notes are available here:

https://github.com/angular-eslint/angular-eslint/releases/tag/v15.0.0

Just as a reminder, I receive zero official/corporate backing or sponsorship to work on this project which is downloaded millions of times per month and used across the Angular community. I work on it in my personal time at the expense of other things in my life.

If you can spare it and would like to buy me a black americano to help keep this "caffeine to code converter" well fueled then that would be very much appreciated 🙏 

https://www.buymeacoffee.com/jameshenry

**Comment by damingerdai** [comment]
good work

**Comment by vytautas-pranskunas-** [comment]
I still get same error after upgrading eslint when trying to run `ng lint -- --fix`

```
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties().
```

it looks like compiler does not like this part added to angular.json
```
"lint": {
                    "builder": "@angular-eslint/builder:lint",
                    "options": {
                        "lintFilePatterns": [
                            "src/**/*.ts",
                            "src/**/*.html"
                        ]
                    }
                }
```

any thoughts?
