### ISSUE TITLE
Add VS Code `eslint.validate` options to docs

### ISSUE THREAD

**Issue by muuvmuuv** [angular-eslint/angular-eslint#122]
I noticed that validating HTML only works if both is set. So it must be:

```json
  "eslint.validate": [
    "javascript",
    "typescript",
    "html"
  ],
  "eslint.options": {
    "extensions": [
      ".js",
      ".ts",
      ".html"
    ]
  },
```

In my `settings.json` I had previously excluded `html` (for whatever reason) but anyway I think it would make sense to add this to avoid future confusion.

**Comment by gagle** [comment]
Does not worked for me. html is not being validated by @angular-eslint

**Comment by muuvmuuv** [comment]
Did you also add it to `lintFilePatterns` in `angular.json`?

```json
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.component.html",
              "src/**/*.page.html"
            ],
            "exclude": [
              "**/node_modules/**",
              "src/app/assets/**"
            ]
          }
        },
```

**Comment by gagle** [comment]
Yes, I opened a new issue with that https://github.com/angular-eslint/angular-eslint/issues/129
