### ISSUE TITLE
eqeqeq rule allowNullOrUndefined does not work.

### ISSUE THREAD

**Issue by foxel** [angular-eslint/angular-eslint#1228]
```
    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@typescript-eslint/eslint-plugin": "~5.11.0",
    "@typescript-eslint/parser": "~5.11.0",
    "eslint": "^7.6.0",
```

This is what I see in debugger: `isLiteralPrimitive` returns false for LiteralPrimitive object.
![image](https://user-images.githubusercontent.com/1551926/203729904-9aa0bebc-2591-403b-a6b7-848305b3a8ed.png)

I suspect there is an issue with imports but I checked installed packages and there is only one '@angular-eslint/bundled-angular-compiler' in modules tree.

**Comment by JamesHenry** [comment]
@foxel We try really hard to help people (for free, during our personal time - this project is not backed by a corporation), but they first have to help themselves by filling out the issue templates we took the time to create for them. You have chosen to disregard that here and have provided insufficient information, so this will be closed.
