### ISSUE TITLE
[no-inputs-metadata-property] Angular Host Directive inputs error

### ISSUE THREAD

**Issue by Marcarrian** [angular-eslint/angular-eslint#1238]
**Description and reproduction of the issue**
When using the new Angular 15 Directive Composition API and specifying inputs, angular-eslint reports an error.
 **Use `@Input` rather than the `inputs` metadata property (https://angular.io/styleguide#style-05-12) @angular-eslint/no-inputs-metadata-property**

Reproduction Repository https://github.com/Marcarrian/angular-15-eslint-issue

```TS
@Component({
  selector: 'app-my-component',
  template: `<span>MyComponent</span>`,
  hostDirectives: [{
    directive: MyDirective,
    inputs: ['myDirectiveSomeInput: someInput'], // errors here with @angular-eslint/no-inputs-metadata-property
  }],
  standalone: true,
})
export class MyComponent {

  @Input()
  public someInput = false;
}

@Directive({
  selector: '[appMyDirective]',
  standalone: true,
})
export class MyDirective {

  @Input()
  public myDirectiveSomeInput = false;
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `15.1.0` |
| `@typescript-eslint/parser`        | `5.44.0` |
| `ESLint`                           | `8.28.0` |
| `node`                             | `16.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 15.0.1        
Node: 16.16.0              
Package Manager: npm 8.11.0
OS: win32 x64              

Angular: 15.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.1
@angular-devkit/build-angular   15.0.1
@angular-devkit/core            15.0.1
@angular-devkit/schematics      15.0.1
@schematics/angular             15.0.1
rxjs                            7.5.7
typescript                      4.8.4
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Thanks @Marcarrian! I made a similar adjustment to `no-input-rename` recently: https://github.com/angular-eslint/angular-eslint/pull/1231

Would you like to submit a PR for this?

**Comment by evgeniyefimov** [comment]
Hi @JamesHenry . `@angular-eslint/no-outputs-metadata-property` complains about host directive output. I think it should be also fixed.

**Comment by lucasousi** [comment]
@JamesHenry the same problem happens with the `output` property. (`@angular-eslint/no-outputs-metadata-property`).

![image](https://github.com/angular-eslint/angular-eslint/assets/37607560/013b1994-6311-4e04-819d-75c66626f34d)
