### ISSUE TITLE
Error: Debug Failure. False expression: position cannot precede the beginning of the file

### ISSUE THREAD

**Issue by KostblLb** [angular-eslint/angular-eslint#126]
Hello! I'm having troubles using angular-eslint with Angular 10.1 (with TS 4 included)

I've created a project using ng new --minimal (this is important since there will be no tslint nor e2e directory on minimal workspace).

I did `ng add @angular-eslint/schematics` then `ng g @angular-eslint/schematics:add-config-to-project {{YOUR_PROJECT_NAME_GOES_HERE}}` and just modified `tsconfig.eslint.json` so that linting would work. Then i called `npx ng run client-app:eslint`, and got the following error:
```
Error: Debug Failure. False expression: position cannot precede the beginning of the file
... continues with stack trace ...
preprocess: ERROR could not parse @Component() metadata C:\projects\projectdir\src\app\app.component.ts
```

my app.component.ts:

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
      <h1>
        {{ title }}
      </h1>
  `,
  styles: []
})
export class AppComponent {
  title = $localize`Hello`;
}
```

But linting does work when i  have a single line template in my code, i.e.
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<h1>{{ title }}</h1>',
  styles: []
})
export class AppComponent {
  title = $localize`Hello`;
}
```

**Comment by Yanduz** [comment]
@KostblLb Yo, I ran into the same problem yesterday, it happens because in angualr 10.1.0, the tsconfig.base.json file, which uses angular eslint, was removed.  I changed tsconfig.base.json -> tsconfig.json in tsconfig.eslint.json and it worked.

**Comment by KostblLb** [comment]
@Yanduz , yeah i noticed that about tsconfig.base, so  i changed tsconfig.eslint.json beforehand. i'd better post it here along with eslintrc

*.eslintrc.js:*
```
module.exports = {
  env: {
    browser: true,
    es2020: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "prettier/@typescript-eslint",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 11,
    sourceType: "module",
  },
  plugins: ["@typescript-eslint"],
  rules: {},

  overrides: [
    {
      files: ["*.ts"],
      parserOptions: {
        project: "./tsconfig.eslint.json",
      },
      extends: ["plugin:@angular-eslint/recommended"],
      rules: {
        "@angular-eslint/directive-selector": [
          "error",
          { type: ["attribute", "element"], prefix: "app", style: "camelCase" },
        ],

        "@angular-eslint/component-selector": [
          "error",
          { type: "element", prefix: "app", style: "kebab-case" },
        ],
        "@typescript-eslint/no-misused-promises": ["error"],

        quotes: "off",
      },
    },

    {
      files: ["*.component.html"],
      extends: ["plugin:@angular-eslint/template/recommended"],
      rules: {
        "max-len": ["error", { code: 140 }],
      },
    },

    {
      files: ["*.component.ts"],
      extends: ["plugin:@angular-eslint/template/process-inline-templates"],
    },
  ],
};
```

*tsconfig.eslint.json*:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "noEmit": true
  },
  "include": ["src"]
}
```

**Comment by JamesHenry** [comment]
Thanks for the heads up about this change guys, I will update the repo to use 10.1+ to make sure everything works.

Please note that in v0.4+ we moved away from `tsconfig.eslint.json` again, so hopefully this shouldn't be an issue.

For context on why we removed `tsconfig.eslint.json` usage, please see https://github.com/angular-eslint/angular-eslint/pull/136

**Comment by JamesHenry** [comment]
I have now upgrade everything to Angular 10.1 and TS 4 in https://github.com/angular-eslint/angular-eslint/pull/148 and as predicted, when the additional tsconfig file is not involved (see my previous comment for why) there is no issue.

Closing this, but thanks again for the heads up around the changes to tsconfigs in 10.1
