### ISSUE TITLE
ng add @angular-eslint/schematics adds incorrect version, throws error

### ISSUE THREAD

**Issue by inorganik** [angular-eslint/angular-eslint#1261]
This issue is for @angular-eslint/schematics, so I hope I'm putting this in the right place. Upon creating a new angular project, and then running the ng add schematic, it will install v1.0 and then throw an error. Upon opening the fresh project, when you run `ng lint` it prompts you to install ESLint. When you do, it installs v1.0 and then throws "NOT SUPPORTED: keyword "id", use "$id" for schema ID":

```
% ng lint
Cannot find "lint" target for the specified project.
You can add a package that implements these capabilities.

For example:
  ESLint: ng add @angular-eslint/schematics

Would you like to add ESLint now? Yes
ℹ Using package manager: npm
✔ Found compatible package version: @angular-eslint/schematics@1.0.0.
✔ Package information loaded.

The package @angular-eslint/schematics@1.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
NOT SUPPORTED: keyword "id", use "$id" for schema ID
```
Note: You will get the same result of having v1.0 installed if you start by running the ng add command instead of letting the CLI prompt you to install ESLint.

From here you have to run `ng update @angular-eslint/schematics` and it will update the package sequentially - v2, v3, v4, v12, v13, v14, and finally v15. 

At this point, you will just have the eslint schematics package installed, but it will not have added eslintrc or other dependencies.  From the README, it says to run ng add @angular-eslint/schematic and "that's it", but alas I still had to run `ng add @angular-eslint/schematics` again to get the deps, and then `ng g @angular-eslint/schematics:add-eslint-to-project` to get the .eslintrc and angular.json changes.

I would have expected a single `ng add @angular-eslint/schematics` to do all of this, based on the docs. But am still very grateful for all this package provides.

**Versions**

| package                            | 14 & 15|
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | 15 & 15 |
| `ESLint`                           | `8.28` |
| `node`                             | `16.13.2` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 15.0.4
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@schematics/angular             15.0.4
rxjs                            7.5.7
typescript                      4.8.4
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by leherv** [comment]
I had the same problem and just tried to do `ng add @angular-eslint/schematics@14` which worked for me. Of course this is not a solution to the problem but maybe a workaround for now.

**Comment by gewubuntu** [comment]
any updates here?

**Comment by JamesHenry** [comment]
Hi Folks, I'm sorry you ran into issues. I can only guess that you had a copy of the older version on your machine already and it was preferentially loaded from the cache by your package manager.

This is not generally an issue, otherwise we would be inundated by duplicate issues and +1s on this one.

The absolute safest way is to be explicit with your version, like @leherv points out above:

```
ng add @angular-eslint/schematics@{{ SOME_VERSION_HERE }}
```

But in general I think you have been unlucky with an undesired cache hit.

There is nothing we can do on the angular-eslint side, as the installation and interaction with the package manager is all out of our control, so I'm closing this one.
