### ISSUE TITLE
Docs: create list of rules with easy way to see recommended & fixable

### ISSUE THREAD

**Issue by rubiesonthesky** [angular-eslint/angular-eslint#1287]
It would be really helpful if there were rule lists for packages, where you could easily see which rules are part of recommended config and which have fixer. Most eslint plugins have this kind of lists.  This project also have one sort of list where there is list of codelyzer rules and their corresponding angular-eslint rule, but I think that is starting to get more outdated way of consuming angular-eslint. :) 

I have created small script generating this kind of readmes for myself using typescript-eslint code as a base, so it should be kinda easy to do at least rudimentary listing. (Though in this point the code is old and I'm not really familiar it anymore.)

So something like this:

### Possible problems

**Key**

- :white_check_mark: = recommended
- :wrench: = fixable
- :bulb: = has suggestions

| Rule | Description | :white_check_mark: | :wrench: | :bulb: |
| --- | --- | --- | --- | --- |
| [`@angular-eslint/contextual-lifecycle`](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/contextual-lifecycle.md) | Ensures that lifecycle methods are used in a correct context | :white_check_mark: |  |  |
| [`@angular-eslint/no-attribute-decorator`](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/no-attribute-decorator.md) | The `@Attribute` decorator is used to obtain a single value for an attribute. This is a much less common use-case than getting a stream of values (using `@Input`), so often the `@Attribute` decorator is mistakenly used when `@Input` was what was intended. This rule disallows usage of `@Attribute` decorator altogether in order to prevent these mistakes. |  |  |  |

**Comment by jerone** [comment]
You could use https://github.com/bmish/eslint-doc-generator

**Comment by json-derulo** [comment]
Fixed by #1399. This issue can be closed.
