### ISSUE TITLE
adding @angular-eslint/schematics brakes angular ng generate

### ISSUE THREAD

**Issue by alvipeo** [angular-eslint/angular-eslint#1288]
If you create a new angular project and then run `ng lint`, the __@angular-eslint/schematics__ is installed (or just use `ng add @angular-eslint/schematics` command). But then you won't be able to use `ng generate` for this project. For example, running the following command:
```
ng g module Test --route=test --module=app.module
```
throws the error:
> An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined. See [..]\angular-errors.log" for further details.

Please fix this as it breaks the usability of any CLI (not just angular).

**Comment by JamesHenry** [comment]
This was an Angular CLI bug which has already been fixed https://github.com/angular/angular-cli/issues/24586
