### ISSUE TITLE
New rule: [require-attribute-on-tag]

### ISSUE THREAD

**Issue by undsoft** [angular-eslint/angular-eslint#1290]
This is a rule suggestion. This is something that I'm going to build internally anyway, but if you like it, I can make a PR here.

Requires element to have an attribute or a directive applied to it.
Examples:
```js
// Require test ids on some elements.
@angular-eslint/template/require-attribute-on-tag: ['error', [
   {
      elements: ['button', 'tr', 'mat-select'],
      require: 'attr.data-test-id',
   }
]],

// Require alt tag on images.
@angular-eslint/template/require-attribute-on-tag: ['error', [
   {
      elements: ['img'],
      required: 'alt',
   }
]],

// Require all buttons to have type (replaces button-has-type)
@angular-eslint/template/require-attribute-on-tag: ['error', [
   {
      elements: ['button'],
      require: 'type',
   }
]],
```

**Comment by sandikbarr** [comment]
There are existing rules that cover the specific standards for alt text on images and button has type, see:
https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/accessibility-alt-text.md
https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/button-has-type.md

**Comment by undsoft** [comment]
Yes, I know. I'm mainly interested in this because I need a rule to enforce test-ids on elements, but I thought I could make it more generic for other use cases.
Alternatively I could make it more focused on test-ids or make it a separate package.

**Comment by undsoft** [comment]
I decided to build it as a separate package and to focus it on test ids. 
https://github.com/undsoft/eslint-plugin-angular-test-ids

**Comment by mackelito** [comment]
I have been looking to do the same.. but want to have a more generic way of enforcing specific attr on specific elements.. To bad nothing came out of this ticket :/
