### ISSUE TITLE
[no-inferrable-types] Recommended config ignoreParameters.

### ISSUE THREAD

**Issue by infacto** [angular-eslint/angular-eslint#1316]
Any reason for the following config?

https://github.com/angular-eslint/angular-eslint/blob/9ecf4acc786d8529c6110db8842303286df80103/packages/eslint-plugin/src/configs/recommended--extra.json#L33-L36

Why `ignoreParameters`? 
[Docs](https://typescript-eslint.io/rules/no-inferrable-types/#ignoreparameters) Consider to reset to default...

**Comment by JamesHenry** [comment]
v16 is now the latest release and the `recommended--extra` config no longer exists: https://github.com/angular-eslint/angular-eslint/releases/tag/v16.0.0

As with almost all other ESLint plugins, angular-eslint will focus on providing recommended configuration for its own rules. Please refer to typescript-eslint documentation and shared configs for the recommended setup for typescript-eslint rules:
https://typescript-eslint.io/linting/configs/#recommended-configurations
