### ISSUE TITLE
@angular-eslint/schematics creates an invalid .eslintrc.json

### ISSUE THREAD

**Issue by kuzivany** [angular-eslint/angular-eslint#138]
The `.eslintrc.json` created by schematics is an invalid JSON file. It contains a trailing semicolon as seen [in the template](https://github.com/angular-eslint/angular-eslint/blob/0d7746a9a17edb8a6623b23b111443725db5e5bb/packages/schematics/src/add-config-to-project/files/root-files/.eslintrc.json__tmpl__#L105)

**Comment by JamesHenry** [comment]
Thanks! Would you like to submit a quick fix PR?

**Comment by kuzivany** [comment]
> Thanks! Would you like to submit a quick fix PR?

Cool, let me get one done
