### ISSUE TITLE
node_modules/eslint npm ERR!   peer eslint@"^7.20.0 || ^8.0.0" from @angular-eslint/builder@15.2.1

### ISSUE THREAD

**Issue by Sampath-Lokuge** [angular-eslint/angular-eslint#1385]
**Description and reproduction of the issue**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `15.2.1` |
| `ESLint`                           | `8.33.0` |
| `node`                             | `18.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


```

- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Note** I do not use Angular 16. So I use https://github.com/angular-eslint/angular-eslint/releases/tag/v15.2.1

`package.json`

{
  "name": "me",
  "version": "1.6.1",
  "author": "me",
  "homepage": "me",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "15.2.8",
    "@angular/cdk": "15.2.8",
    "@angular/common": "15.2.8",
    "@angular/core": "15.2.8",
    "@angular/fire": "7.5.0",
    "@angular/forms": "15.2.8",
    "@angular/google-maps": "15.2.8",
    "@angular/platform-browser": "15.2.8",
    "@angular/platform-browser-dynamic": "15.2.8",
    "@angular/router": "15.2.8",
    "@awesome-cordova-plugins/app-availability": "^6.3.0",
    "@awesome-cordova-plugins/call-number": "^6.3.0",
    "@awesome-cordova-plugins/core": "^6.3.0",
    "@awesome-cordova-plugins/in-app-browser": "^6.3.0",
    "@awesome-cordova-plugins/screen-orientation": "^6.3.0",
    "@awesome-cordova-plugins/social-sharing": "^6.3.0",
    "@capacitor-community/fcm": "3.0.2",
    "@capacitor-community/photoviewer": "2.0.5",
    "@capacitor/android": "4.8.0",
    "@capacitor/app": "4.0.1",
    "@capacitor/browser": "4.0.0",
    "@capacitor/camera": "4.0.0",
    "@capacitor/core": "4.8.0",
    "@capacitor/device": "4.1.0",
    "@capacitor/geolocation": "4.0.0",
    "@capacitor/haptics": "4.0.1",
    "@capacitor/ios": "4.8.0",
    "@capacitor/keyboard": "4.0.0",
    "@capacitor/preferences": "4.0.1",
    "@capacitor/push-notifications": "4.0.0",
    "@capacitor/splash-screen": "4.0.0",
    "@capacitor/status-bar": "4.0.0",
    "@ionic/angular": "7.0.4",
    "@ionic/pwa-elements": "3.1.1",
    "@lithiumjs/angular": "^7.2.2",
    "@lithiumjs/ngx-virtual-scroll": "^0.2.3",
    "@types/lodash": "4.14.172",
    "call-number": "^1.0.1",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-screen-orientation": "^3.0.3",
    "cordova-plugin-x-socialsharing": "^6.0.4",
    "es6-promise-plugin": "4.2.2",
    "firebase": "9.8.2",
    "lodash": "4.17.21",
    "ng-cloudimage-responsive": "4.0.0",
    "ngx-image-cropper": "6.2.2",
    "primeicons": "5.0.0",
    "primeng": "15.4.1",
    "rxjs": "7.5.0",
    "swiper": "^9.2.4",
    "tslib": "2.2.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.2.7",
    "@angular-eslint/builder": "15.2.1",
    "@angular-eslint/eslint-plugin": "15.2.1",
    "@angular-eslint/eslint-plugin-template": "15.2.1",
    "@angular-eslint/template-parser": "15.2.1",
    "@angular/cli": "15.2.7",
    "@angular/compiler": "15.2.8",
    "@angular/compiler-cli": "15.2.8",
    "@angular/language-service": "15.2.8",
    "@capacitor/cli": "4.8.0",
    "@ionic/angular-toolkit": "8.0.0",
    "@types/node": "12.11.1",
    "@typescript-eslint/eslint-plugin": "5.48.2",
    "@typescript-eslint/parser": "5.48.2",
    "eslint": "8.33.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jeep-photoviewer": "1.1.4",
    "prettier": "2.3.2",
    "ts-node": "8.3.0",
    "typescript": "4.9.5"
  },
  "description": "me"
}

It shows the below error when I tried to install a new package like so:

npm install capacitor-branch-deep-links
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-plugin-import@2.22.1
npm ERR! Found: eslint@8.33.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.20.0 || ^8.0.0" from @angular-eslint/builder@15.2.1
npm ERR!   node_modules/@angular-eslint/builder
npm ERR!     dev @angular-eslint/builder@"15.2.1" from the root project
npm ERR!   peer eslint@"^7.20.0 || ^8.0.0" from @angular-eslint/eslint-plugin@15.2.1
npm ERR!   node_modules/@angular-eslint/eslint-plugin
npm ERR!     dev @angular-eslint/eslint-plugin@"15.2.1" from the root project
npm ERR!   10 more (@angular-eslint/eslint-plugin-template, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0" from eslint-plugin-import@2.22.1
npm ERR! node_modules/eslint-plugin-import
npm ERR!   dev eslint-plugin-import@"2.22.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0" from eslint-plugin-import@2.22.1
npm ERR!   node_modules/eslint-plugin-import
npm ERR!     dev eslint-plugin-import@"2.22.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by JamesHenry** [comment]
Your error is showing that the issue is with `eslint-plugin-import` - you need to update it to a more modern version that supports ESLint v8

**Comment by Sampath-Lokuge** [comment]
Yes, this works for me. Thanks!

>  "eslint-plugin-import": "2.27.5",
> "eslint-plugin-jsdoc": "44.2.4",
