### ISSUE TITLE
Failed to load config "plugin:@angular-eslint/ng-cli-compat" to extend from

### ISSUE THREAD

**Issue by psarno** [angular-eslint/angular-eslint#1388]
**Description and reproduction of the issue**

Upgraded our project to Angular 16.0.2.  Ran:

`ng add @angular-eslint/schematics`

No issues.

Note this part of the quickstart does _not_ get added:

```
  "cli": {
    "schematicCollections": ["@angular-eslint/schematics"]
  }
```

I added it manually.

When I execute `ng lint`, I get:

> An unhandled exception occurred: Failed to load config "plugin:@angular-eslint/ng-cli-compat" to extend from.
> Referenced from: C:\Users\user\source\repos\portal\portal\.eslintrc.json

Log:

[error] Error: Failed to load config "plugin:@angular-eslint/ng-cli-compat" to extend from.
Referenced from: C:\Users\user\source\repos\portal\portal\.eslintrc.json
    at configInvalidError (C:\Users\user\source\repos\portal\ortal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2627:9)
    at ConfigArrayFactory._loadExtendedPluginConfig (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3225:31)
    at ConfigArrayFactory._loadExtends (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3133:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3074:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3019:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3112:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\user\source\repos\portal\portal\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3019:20)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `16.0.2` |
| `@typescript-eslint/parser`        | `5.59.2` |
| `ESLint`                           | `8.40.0` |
| `node`                             | `18.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 16.0.3
Node: 18.16.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@angular/cdk                    16.0.2
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      5.0.4

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
You must have a stale copy of the schematics cached globally on your machine.

I recommend trying the ng add again with the major version appended to ensure the cache is busted.

Eg

ng add @angular-eslint/schematics@16

**Comment by psarno** [comment]
@JamesHenry Same result.

I get:

`ng add @angular-eslint/schematics@16`

ℹ Using package manager: npm
✔ Package information loaded.

The package @angular-eslint/schematics@16 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
    
    All @angular-eslint dependencies have been successfully installed 🎉

    Please see https://github.com/angular-eslint/angular-eslint for how to add ESLint configuration to your project.  

Running `ng lint` results in the same error.

> Failed to load config "plugin:@angular-eslint/ng-cli-compat" to extend from.

**Comment by psarno** [comment]
@JamesHenry Why was this closed?  I can provide further information as necessary.

**Comment by JamesHenry** [comment]
@psarno just to take a step back then on what you’ve said so far…

this is an angular 15 project which did NOT use angular-eslint, which you have first upgraded to angular 16, and then added angular-eslint to for the first time? Is that correct?

**Comment by psarno** [comment]
@JamesHenry No this was an Angular 15.2.5 project in production.    Master branch is still on that version.

It used:

    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "eslint": "^8.18.0",
    "eslint-plugin-deprecation": "^1.3.2",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsdoc": "^37.7.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-unused-imports": "^2.0.0",

This is a feature branch upgrade to 16.   It compiles and runs fine via `ng s` I just can't lint it with `ng lint`.

Package.json devdependencies are now:

    "@angular-eslint/builder": "16.0.2",
    "@angular-eslint/eslint-plugin": "16.0.2",
    "@angular-eslint/eslint-plugin-template": "16.0.2",
    "@angular-eslint/schematics": "16.0.2",
    "@angular-eslint/template-parser": "16.0.2",
    "@typescript-eslint/eslint-plugin": "5.59.2",
    "@typescript-eslint/parser": "5.59.2",
    "eslint-plugin-deprecation": "^1.4.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsdoc": "^44.2.4",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-unused-imports": "~2.0.0",

**Comment by JamesHenry** [comment]
Ok so you were clearing using eslint manually before though. The ng add use case is not really expecting this scenario, and this is the first time it’s ever been reported!

Anyway the error you are getting is because of referencing a config which no longer exists, I don’t really understand how that reference got in there given you say your weren’t using it in v15, but I recommend checking out the v16 release notes and the linked documentation about the changes:

https://github.com/angular-eslint/angular-eslint/releases/tag/v16.0.0

https://github.com/angular-eslint/angular-eslint/blob/main/docs/MIGRATING_FROM_TSLINT.md#legacy-premade-eslint-configs

You will need to decide on if you just want to switch to the recommended configs or copy and contents of the removed configs into your own.

There is not really anything the tooling can do differently here so I’m closing this

**Comment by psarno** [comment]
@JamesHenry Thanks, appreciate the feedback.

I'm in charge of this migration and hate to say I'm in way over my head with this mix and matching of eslint and angular-eslint when it comes to the v16 migration.

Given what I posted, is there anything obvious I should be doing, whether with those files or with `.eslintrc.json`?

I do see the reference to the config file in question:

      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],

The TSLINT to ESLINT documentation does not apply as we are already migrated from tslint to eslint.

I'm lost as to what my `.eslintrc.json` file should look like specifically, or if this is even the source of the problems.

**Comment by JamesHenry** [comment]
@psarno Hopefully this is useful context:

https://github.com/angular-eslint/angular-eslint/assets/900523/98998ed6-e2b7-49a0-b338-8d58cb5eb8ff

As noted in the video, I recommend using the config structure found in the README as your starting point. It is what angular-eslint would have generated for you automatically in a more standard case of having no linter and then adding angular-eslint.

**Comment by psarno** [comment]
@JamesHenry Thanks.   Managed to get it functional enough that I got us down from 100+ problems, 40 errors to "all files pass linting" already.

Including converting all of our class guards into functional ones and other things I've been meaning to get too.

Now just to add even stricter rules to it 😉
