### ISSUE TITLE
ng add @angular-eslint/schematics@13 is throwing error

### ISSUE THREAD

**Issue by roopeshreddy** [angular-eslint/angular-eslint#1414]
This is throwing the @parcel/watcher error!!!

**This is the error with VPN of my enterprise.** 

CREATE .eslintrc.json (984 bytes)
UPDATE package.json (1450 bytes)
UPDATE angular.json (3508 bytes)

> @parcel/watcher@2.0.4 install C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\@parcel\watcher
> node-gyp-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.20.0/node-v16.20.0-headers.tar.gz failed, reason: self signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\minipass-fetch\lib\index.js:110:14)
gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:494:9)
gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WB527065\\Downloads\\Apps\\ng13App\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\@parcel\watcher
gyp ERR! node -v v16.20.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Without VPN, i'm getting this error -** 

> @parcel/watcher@2.0.4 install C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\@parcel\watcher
> node-gyp-build

gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:410:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WB527065\\Downloads\\Apps\\ng13App\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WB527065\Downloads\Apps\ng13App\node_modules\@parcel\watcher
gyp ERR! node -v v16.20.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by JamesHenry** [comment]
Angular 13 is _very_ out of date. The Angular Team themselves do not support it, and they are backed by Google.

We are a tiny team of volunteers and cannot support old major versions of the tooling.

Please look to update your tooling to the latest as soon as possible
