### ISSUE TITLE
[@angular-eslint/template/attributes-order] Cannot read properties of undefined (reading 'sourceSpan')

### ISSUE THREAD

**Issue by jmeinlschmidt** [angular-eslint/angular-eslint#1456]
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "'@angular-eslint/template/attributes-order": ["error"]
  }
}
```

This code (combination of `ng-template` and `mat-icon`) leads to the following error.

```HTML
<ng-template>
  <mat-icon>assignment</mat-icon>
</ng-template>
```

```sh
[error] TypeError: Cannot read properties of undefined (reading 'sourceSpan')
Occurred while linting /Users/.../src/app/.../pages/detail/detail.component.html:10
Rule: "@angular-eslint/template/attributes-order"
    at extractTemplateAttrs (/Users/.../node_modules/@angular-eslint/eslint-plugin-template/dist/rules/attributes-order.js:193:45)
    at Element$1 (/Users/.../node_modules/@angular-eslint/eslint-plugin-template/dist/rules/attributes-order.js:81:24)
    at ruleErrorHandler (/Users/.../node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/.../node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/.../node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

Unfortunately, I haven't yet got time to prepare a stackblitz but the problem is here https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/src/rules/attributes-order.ts#L303. I checked the `attrs` variable at the error, and it is empty (seems correct to me, `ng-template` doesn't have any attributes). Therefore `attrs[attrs.length - 1]` leads to undefined.

If I add an attribute to the `ng-template`:

```html
<ng-template mat-tab-label>
  <mat-icon>assignment</mat-icon>
</ng-template>
```

The error still occurs, `attrs` is empty. However, the attribute `mat-tab-label` appears in the `node.parent.attributes` but not in the `node.parent.templateAttrs`.

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.1.0` |
| `@angular-eslint/template-parser`         | `16.1.0` |
| `@typescript-eslint/parser`               | `6.0.0` |
| `ESLint`                                  | `8.44.0` |
| `node`                                    | `18.10.0` |

```sh

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.4
Node: 18.10.0
Package Manager: npm 8.15.0
OS: darwin arm64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@angular/fire                   7.6.1
@schematics/angular             16.1.4
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.0.4
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by osnoser1** [comment]
I have this same error in this piece of code:

```
      <ng-template #enterCode>
        <div class="field">
          <code-input
            [isCodeHidden]="false"
            [codeLength]="6"
            (codeCompleted)="onCodeCompleted($event)"
            [disabled]="disabledInputs"
          >
          </code-input>
        </div>
      </ng-template>
```

The error line the exception says is: `<div class="field">`

**Comment by alfaproject** [comment]
Just got hit by this regression as well ):

**Comment by Timeout-Timo** [comment]
Same with this line: 

```html
<ng-template #options>
    <mat-card class="options" @options> <!-- This line causes the exception --> 
        <ng-content></ng-content>
    </mat-card>
</ng-template>
```

**Comment by jmeinlschmidt** [comment]
It seems to be this change https://github.com/angular-eslint/angular-eslint/commit/90c0e916654297b29cabf8289b1811ed307018ab#diff-c55fb0b26be29b06161102f2487618150b5c5febbc6810b01f71df87cccf4be4R302-R303 @pmccloghrylaing

**Comment by pmccloghrylaing** [comment]
I'm taking a look at this. Looks like I need to differentiate between actual usages of NgTemplate and implied usages (via a structural directive)

**Comment by joergbaier** [comment]
Where is `v16.1.1` at?

![](https://media.tenor.com/PmktnnCEfsMAAAAC/cmon-do-something-original-cmon.gif)

**Comment by joeldhenry** [comment]
still an issue ? why closed
