### ISSUE TITLE
[prefer-self-closing-tags] auto-fix results in invalid HTML

### ISSUE THREAD

**Issue by ocsurfnut** [angular-eslint/angular-eslint#1464]
**Description and reproduction of the issue**

Starting with **16.1.0**, the [new auto-fix for prefer-self-closing-tags](https://github.com/angular-eslint/angular-eslint/pull/1322) results in invalid HTML in our templates.  It looks like the column calculation is off by one.  

```JSON
{
  "rules": {
    "@angular-eslint/template/prefer-self-closing-tags": "error"
  }
}
```

**Before**

```html
<app-datepicker data-testid="date" formControlName="date" [maxDate]="today" required></app-datepicker>
```

**After**

```html
<app-datepicker data-testid="date" formControlName="date" [maxDate]="today" require />>
```

All of our projects are private, so I cannot provide a full repro, however it may help to know that we only use inline templates with our components.

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.1.0` |
| `@angular-eslint/template-parser`         | `16.1.0` |
| `@typescript-eslint/parser`               | `16.1.0` |
| `ESLint`                                  |`8.45.0` |
| `node`                                    | `18.16.1` |

**Comment by cipchk** [comment]
An animation example:

![demo](https://github.com/angular-eslint/angular-eslint/assets/2987467/069a8f11-a6b2-4798-8e54-a663bc34b381)

code: 

```ts
@Component({
  template: `
    <avatar-list [size]="size" [maxLength]="maxLength">
      <avatar-list-item
        tips="Jake"
        src="https://gw.alipayobjects.com/zos/rmsportal/zOsKZmFRdUtvpqCImOVY.png"
      ></avatar-list-item>
      <avatar-list-item
        tips="Andy"
        src="https://gw.alipayobjects.com/zos/rmsportal/sfjbOqnsXXJgNCjCzDBL.png"
      ></avatar-list-item>
      <avatar-list-item
        tips="Niko"
        src="https://gw.alipayobjects.com/zos/rmsportal/kZzEzemZyKLKFsojXItE.png"
      ></avatar-list-item>
      <avatar-list-item tips="Cipchk" text="Cipchk"></avatar-list-item>
      <avatar-list-item tips="heart-o"></avatar-list-item>
    </avatar-list>
  `
})
class TestComponent {
  size: 'large' | 'small' | 'mini' | 'default' = 'default';
  maxLength = 0;
}
```

**Comment by json-derulo** [comment]
The issue is only present when using inline templates. If the template is in a separate file, everything seems to work fine.

**Comment by json-derulo** [comment]
I found very similar issues with the autofixer on inline templates for several other rules. Minimal reproducible example:

```typescript
import { Component } from '@angular/core';

@Component({
  template: `
    <div autofocus></div> <!-- no autofocus -->
    <marquee></marquee>{{ '' }} <!-- no-distracting-elements -->
    <div scope></div> <!-- table-scope -->
  `
})
export class TestComponent {}
```

After running autofix I'm getting the following unexpected results:

```typescript
import { Component } from '@angular/core';

@Component({
  template: `
    <dis></div> <!-- no autofocus -->
   >{{ '' }} <!-- no-distracting-elements -->
    <die></div> <!-- table-scope -->
  `
})
export class TestComponent {}
```

So I believe this is a more general problem of the inline template parser.

I found yet another issue but I'm not sure if it's related. Sometimes when using the `eqeqeq` rule, the fixer adds code in the imports. Example:

```typescript
import { Component } from '@angular/core';

@Component({
  template: `
    <div *ngIf="value == null"></div>
  `
})
export class TestComponent {
  value?: string | null;
}
```

Will be "fixed" to:

```typescript
import { Component } from= '@angular/core';

@Component({
  template: `
    <div *ngIf="value == null"></div>
  `
})
export class TestComponent {
  value?: string | null;
}
```


Which is a TypeScript syntax error.
