### ISSUE TITLE
Cannot update to the latest version

### ISSUE THREAD

**Issue by erwinheitzman** [angular-eslint/angular-eslint#149]
When I run `npm i -D -E @angular-eslint/builder@0.5.0-beta.1` for the builder package or any of the other packages, I get the following error:
```
No matching version found for @angular-eslint/builder@0.5.0-beta.1
```

Running `npm i -D -E @angular-eslint/builder@latest` installs version `0.4.0-beta.2`

**Comment by JamesHenry** [comment]
It's definitely available: https://www.npmjs.com/package/@angular-eslint/builder/v/0.5.0-beta.1

And worked fine for me just now:

![image](https://user-images.githubusercontent.com/900523/94931359-95988f00-04bf-11eb-9998-7937fddca598.png)

Maybe just a timing issue? Please try again

**Comment by erwinheitzman** [comment]
Tried again but it's still not pulling the latest. I'll try to figure out what's the reason since I've already cleared my npm cache as well.

Thank you for the fast feedback btw!

**Comment by erwinheitzman** [comment]
Checking the latest version using `npm show @angular-eslint/builder version` returns `0.4.0-beta.2`.

Using https://www.npmjs.com/package/npm-check-updates to check for an update also says there's no newer version.

**Comment by JamesHenry** [comment]
I'm a little confused, are you saying your issue has resolved?

I haven't been able to reproduce at all - it immediately showed everywhere for me and was installable

![image](https://user-images.githubusercontent.com/900523/94945459-9a1a7300-04d2-11eb-9246-8d597ef8f96e.png)

**Comment by erwinheitzman** [comment]
It has indeed been resolved. We use a Nexus repository for our packages which holds a cache which was causing the issue. My apologies, it's the first time I have dealt with such a situation before and should have known this from the start.
Simply commenting the `registry` attribute in the `.npmrc` file did the trick because it directly went to npm instead of fetching the cached version of the packages from Nexus.

**Comment by JamesHenry** [comment]
Ok great, thanks!
