### ISSUE TITLE
Extreme slowness when using tsconfig.app.json

### ISSUE THREAD

**Issue by oBusk** [angular-eslint/angular-eslint#150]
So I'm trying to set this up on our very large angular-hybrid project in angular-cli and I'm having trouble where each file takes a very long time to lint (3.5 seconds or so). I assume it would be possible to configure eslint to run standard `@typescript-eslint` rules for the Angular.js files and usng `overrides` to run `@angular-eslint` rules only on Angular components.

We keep all Angular code in `src/app` and all Angular.js code in `src/app-ajs`.

The config in angular.json looks like this;

```jsonc
// ...
"lint": {
    "builder": "@angular-eslint/builder:lint",
    "options": {
    "lintFilePatterns": [
        "src/**/*.ts",
        "src/app/**/*.component.html"
    ]
    }
},
// ...
```

To not try to parse the angular.js templates.

If I change the `project` in the eslintrc.json to be the root `tsconfig.json`  it goes a lot quicker and still seems to be able to do a lot of the checks.

Turning `createDefaultProgram` on or off does not seem ot make any difference. 

I cannot share the source code of the project, and I assume the size of the project is part of the problem so I've not created a recreation repo.  Please let me know of any suggestions as to figure out what's going wrong.

**Comment by JamesHenry** [comment]
Please share your ESLint config and the contents of any tsconfig files that the ESLint config references.

Please also try running linting with the `DEBUG` environment variable set, e.g.

```sh
DEBUG=typescript-eslint:* npx nx lint
```

And see what typescript-eslint is logging around its activity and how long certain actions are taking.

If you could share that debug output as well that would also be useful

**Comment by oBusk** [comment]
The eslintrc currently looks like this;

<details>
<summary><code>.eslintrc.json</code></summary>
<br/>

    /**
    * -----------------------------------------------------
    * NOTES ON CONFIGURATION STRUCTURE
    * -----------------------------------------------------
    *
    * Out of the box, ESLint does not support TypeScript or HTML. Naturally those are the two
    * main file types we care about in Angular projects, so we have to do a little extra work
    * to configure ESLint exactly how we need to.
    *
    * Fortunately, ESLint gives us an "overrides" configuration option which allows us to set
    * different lint tooling (parser, plugins, rules etc) for different file types, which is
    * critical because our .ts files require a different parser and different rules to our
    * .html (and our inline Component) templates.
    */
    {
        "root": true,
        "overrides": [
            /**
            * -----------------------------------------------------
            * TYPESCRIPT FILES (COMPONENTS, SERVICES ETC) (.ts)
            * -----------------------------------------------------
            */
            {
                "files": ["*.ts"],
                "parserOptions": {
                    "project": ["tsconfig.*?.json", "e2e/tsconfig.json"],
                    "createDefaultProgram": true
                },
                "extends": ["plugin:@angular-eslint/recommended"],
                "rules": {
                    /**
                    * Any TypeScript related rules you wish to use/reconfigure over and above the
                    * recommended set provided by the @angular-eslint project would go here.
                    *
                    * There are some examples below from the @angular-eslint plugin and ESLint core:
                    */
                    "@angular-eslint/directive-selector": [
                        "error",
                        {
                            "type": "attribute",
                            "prefix": "sb",
                            "style": "camelCase"
                        }
                    ],
                    "@angular-eslint/component-selector": [
                        "error",
                        {
                            "type": "element",
                            "prefix": "sb",
                            "style": "kebab-case"
                        }
                    ],
                    "quotes": ["error", "single", { "allowTemplateLiterals": true }]
                }
            },

            /**
            * -----------------------------------------------------
            * COMPONENT TEMPLATES
            * -----------------------------------------------------
            *
            * If you use inline templates, make sure you read the notes on the configuration
            * object after this one to understand how they relate to this configuration directly
            * below.
            */
            {
                "files": ["*.component.html"],
                "extends": ["plugin:@angular-eslint/template/recommended"],
                "rules": {
                    /**
                    * Any template/HTML related rules you wish to use/reconfigure over and above the
                    * recommended set provided by the @angular-eslint project would go here.
                    *
                    * There is an example below from ESLint core (note, this specific example is not
                    * necessarily recommended for all projects):
                    */
                    "max-len": ["error", { "code": 140 }]
                }
            },

            /**
            * -----------------------------------------------------
            * EXTRACT INLINE TEMPLATES (from within .component.ts)
            * -----------------------------------------------------
            *
            * This extra piece of configuration is necessary to extract inline
            * templates from within Component metadata, e.g.:
            *
            * @Component({
            *  template: `<h1>Hello, World!</h1>`
            * })
            * ...
            *
            * It works by extracting the template part of the file and treating it as
            * if it were a full .html file, and it will therefore match the configuration
            * specific for *.component.html above when it comes to actual rules etc.
            *
            * NOTE: This processor will skip a lot of work when it runs if you don't use
            * inline templates in your projects currently, so there is no great benefit
            * in removing it, but you can if you want to.
            *
            * You won't specify any rules here. As noted above, the rules that are relevant
            * to inline templates are the same as the ones defined for *.component.html.
            */
            {
                "files": ["src/app/**/*.component.ts"],
                "extends": [
                    "plugin:@angular-eslint/template/process-inline-templates"
                ]
            }
        ]
    }

</details>

And the debug log looks like this;

<details>
<summary><code>DEBUG=typescript-eslint:* ng lint</code></summary>
<br/>

    Linting "silobreaker-webapp"...
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +0ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.component.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.component.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/e2e/tsconfig.json. +0ms
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/tsconfig.app.json. +1s
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/tsconfig.spec.json. +5s
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +0ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +8s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +8s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +2s
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +70ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +495ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +64ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +39ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +512ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +54ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +1ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +36ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +493ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +52ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +36ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +468ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +74ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +36ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +465ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +87ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +1ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +35ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +492ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +3s
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [ 'e2e/tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json' ] +3s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +3s
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +61ms
    typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +1ms
    typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +36ms

</details>

Looks like it's `typescript-eslint:typescript-estree:createProjectProgram` that takes a long time.

If I change the `project` in `.eslintrc.json` to include `tsconfig.json`; `"project": ["tsconfig.json", "tsconfig.*?.json", "e2e/tsconfig.json"],`, it looks like this;

<details>
<summary><code>DEBUG=typescript-eslint:* ng lint</code></summary>
<br/>

    Linting "silobreaker-webapp"...
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +0ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.component.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.component.ts +0ms
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/tsconfig.json. +0ms
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/e2e/tsconfig.json. +6s
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/tsconfig.app.json. +545ms
    typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /home/oscar/source/Silobreaker/WebApp/tsconfig.spec.json. +4s
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +0ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +14s
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +14s
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/account-settings.module.ts +2s
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +52ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +13ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +12ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/date-format.model.ts +8ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +10ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +5ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +5ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/hour-format.model.ts +5ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +4ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +4ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +4ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-adapter.service.ts +4ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +10ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +18ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +18ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-settings.component.ts +18ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +34ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +37ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +37ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/mfa-settings/mfa-verification.component.ts +38ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +28ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +22ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +22ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/account-settings/password-states.model.ts +21ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +10ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +11ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-multi/add-to-project-multi.component.ts +11ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-multi/add-to-project-multi.component.ts +11ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +18ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +18ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-multi/add-to-project-multi.module.ts +19ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-multi/add-to-project-multi.module.ts +19ms
    typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom' ] +11ms
    typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
    'tsconfig.json',
    'e2e/tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.spec.json'
    ] +7ms
    typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-single/add-to-project-single.component.ts +6ms
    typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /home/oscar/source/Silobreaker/WebApp/src/app/add-to-project/add-to-project-single/add-to-project-single.component.ts +6ms

</details>

So looks like with `tsconfig.app.json` it recreates the program for every single file while if I include `tsconfig.json` it manages to reuse the program for every file. I guess since you need to find the dependency graph to each file to figure out if it is even part of `tsconfig.app.json` while all files are included in `tsconfig.json` by default?

Here is our config files too. I've tried to keep them as close to angular-cli basic setup as possible, with only necessary changes. I guess the various versions of angular-cli can have varied a bit too.

<details>
<summary><code>tsconfig.json</code></summary>
<br/>

    {
        "compileOnSave": false,
        "compilerOptions": {
            "baseUrl": "./src",
            "outDir": "./dist/out-tsc",
            "sourceMap": true,
            "declaration": false,
            "downlevelIteration": true,
            "experimentalDecorators": true,
            "module": "es2020",
            "esModuleInterop": true,
            "moduleResolution": "node",
            "importHelpers": true,
            "target": "es5",
            "forceConsistentCasingInFileNames": true,
            "typeRoots": [
                "node_modules/@types"
            ],
            "lib": [
                "es2020",
                "dom"
            ],
            "plugins": []
        },
        "angularCompilerOptions": {
            "fullTemplateTypeCheck": true,
            "strictInjectionParameters": true,
            "strictNullInputTypes": true,
            "strictAttributeTypes": true,
            "strictSafeNavigationTypes": true,
            "strictDomLocalRefTypes": true,
            "strictContextGenerics": true,
            "strictLiteralTypes": true
        }
    }

</details>

<details>
<summary><code>tsconfig.app.json</code></summary>
<br/>

    {
        "extends": "./tsconfig.json",
        "compilerOptions": {
            "outDir": "./out-tsc/app",
            "types": [
                "jquery",
                "jqueryui",
                "angular",
                "angular-animate",
                "angular-cookies",
                "angular-sanitize",
                "angular-ui-sortable",
                "ng-file-upload"
            ],
            "paths": {
                "generated/*": [
                    "../generated/*"
                ]
            }
        },
        "files": [
            "src/common/files.d.ts",
            "src/main.ts",
            "src/polyfills.ts"
        ]
    }

</details>

<details>
<summary><code>tsconfig.spec.json</code></summary>
<br/>

    {
        "extends": "./tsconfig.json",
        "compilerOptions": {
            "outDir": "./out-tsc/spec",
            "types": [
                "jasmine",
                "node",
                "jquery",
                "jqueryui",
                "angular",
                "angular-animate",
                "angular-cookies",
                "angular-sanitize",
                "angular-ui-sortable",
                "ng-file-upload"
            ]
        },
        "files": [
            "src/common/files.d.ts",
            "src/test.ts",
            "src/polyfills.ts"
        ],
        "include": [
            "src/common/**/*.spec.ts",
            "src/common/**/*.d.ts",
            "src/app/**/*.spec.ts",
            "src/app/**/*.d.ts"
        ]
    }

</details>

For good measure, here are the relevant versions too;

```
"@angular-eslint/builder": "0.5.0-beta.2",
"@angular-eslint/eslint-plugin": "0.5.0-beta.2",
"@angular-eslint/eslint-plugin-template": "0.5.0-beta.2",
"@angular-eslint/template-parser": "0.5.0-beta.2",
"@typescript-eslint/eslint-plugin": "4.3.0",
"@typescript-eslint/parser": "4.3.0",
"eslint": "7.10.0",
```

**Comment by JamesHenry** [comment]
Thanks, @oBusk, this is definitely useful!

Do you have a `src/main.ts` and if so what logic is contained within it (i.e. how much does it differ from the one the Angular CLI generates)?

**Comment by oBusk** [comment]
Our `main.ts` imports both the Angular and AngularJS app modules, makes some configuration to the AngularJS module, bootstraps Angular and then syncs `ui-router` once it's done.

Based on [`ui-router/angular-hybrid#bootstrap-the-app`](https://github.com/ui-router/angular-hybrid#bootstrap-the-app) and [`ui-router/app/main.ts`](https://github.com/ui-router/sample-app-angular-hybrid/blob/master/app/main.ts).

```typescript
// src/main.ts

import { enableProdMode, NgZone } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UrlService, UIRouter } from '@uirouter/angular';

import { AppModule } from './app/app.module';
import { appAjsModule } from './app-ajs/app-ajs.module';
import { environment } from './environments/environment';

if (environment.production) {
    enableProdMode();
}

// Using AngularJS config block, call `deferIntercept()`.
// This tells UI-Router to delay the initial URL sync (until all bootstrapping is complete)
appAjsModule.config(['$urlServiceProvider', ($urlService: UrlService) => $urlService.deferIntercept()]);

platformBrowserDynamic().bootstrapModule(AppModule)
    .then(platformRef => {
        // Intialize the Angular Module
        // get() the UIRouter instance from DI to initialize the router
        const urlService: UrlService = platformRef.injector.get(UIRouter).urlService;

        // Instruct UIRouter to listen to URL changes
        function startUIRouter() {
            urlService.listen();
            urlService.sync();
        }

        platformRef.injector.get(NgZone).run(startUIRouter);
    })
    .catch(err => console.error(err));
```

The AngularJS module just imports a load of other AngularJS modules. 

The Angular module imports some modules and bootstraps `@angular/upgrade`.

```
// src/app/app.module.ts

import { appAjsModule } from 'app-ajs/app-ajs.module'; // We need to import the angularjs application before `UpgradeModule`.

import { DoBootstrap, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { UpgradeModule } from '@angular/upgrade/static';
import { UIRouterUpgradeModule } from '@uirouter/angular-hybrid';
// Some other local modules
import { MAT_RIPPLE_GLOBAL_OPTIONS } from '@angular/material/core';

@NgModule({
    imports: [
        BrowserAnimationsModule,
        BrowserModule,
        UIRouterUpgradeModule.forRoot(),
        UpgradeModule,
        // Some other modules
    ],
    providers: [
        {provide: MAT_RIPPLE_GLOBAL_OPTIONS, useValue: {disabled: true}},
    ],
})
export class AppModule implements DoBootstrap {
    constructor(private upgrade: UpgradeModule) { }

    ngDoBootstrap() {
        this.upgrade.bootstrap(document.documentElement, [appAjsModule.name], { strictDi: true });
    }
}
```

**Comment by oBusk** [comment]
So since the linting seems to work fine when adding `tsconfig.json` as a project file, is there any problems that using `tsconfig.json` might cause that isn't a corner case?

**Comment by napei** [comment]
I have also noticed a very strong difference between the old TSLint integration and this new ESLint integration. VSCode now seems to take up to a minute to parse changes on save, with errors sticking around for a long time seemingly being checked several times until they eventually go away. 

Example would be syntax errors for incomplete code that got saved after delay but no linting errors turn up until I finish writing that line, but then they are outdated errors from when the line wasn't complete yet, and then after a while it goes away or moves to another position after adding more code.

**Comment by jr01** [comment]
I also noticed extreme slowness when running from command line using a solution style tsconfig.json. Also Visual Studio 2019 eslint fails to parse each .ts file, VScode is fine. 

When clearing out the project array in the *.ts section eslint is quick and also Visual Studio 2019 eslint works. I'm not sure what linting rules I'm missing out on by overriding the project array....

```
"files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [] // overrides the "./tsconfig.json" that ng-cli-compat drags in. 
      },
```

**Comment by JamesHenry** [comment]
I have added a whole new section on performance considerations to the docs: https://github.com/angular-eslint/angular-eslint#notes-on-performance

Please kindly have a read through that.

Having catch all issues on performance, where multiple people chime in from different projects, absolutely never work and just make it harder to offer help in what little unpaid time I do have.

If you are still facing confusing performance issues after reading the above linked docs, and digging into the logs as it suggests, please open a new issue _specific to your setup_, including as much information as possible. Think about what kind information you would want to see from a colleague or customer when troubleshooting an issue where you don't have perfect insight into what they have run or configured on their machine. 🙏 

Many thanks!
