### ISSUE TITLE
An unhandled exception occurred: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by AlexanderFSP** [angular-eslint/angular-eslint#151]
**Prerequisites:**
I have generated a new angular 10.1 app and perform migration to ESLint using `@angular-eslint/schematics:add-config-to-project` schematic. And also I change a bit `.eslintrc.json` to use  `plugin:@angular-eslint/template/all` config instead of recommended.

This is my pretty simple AppComponent:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<input type="text" tabindex="20" />`,
  styleUrls: ['./app.component.css'],
})
export class AppComponent {}
```
**Problem:**
And when I try to lint my code I get an error:
1. In the console, when I execute `lint` npm run script:
`An unhandled exception occurred: Cannot read property 'range' of undefined`
2. Also in VSCode output console (using `dbaeumer.vscode-eslint` extension):
```
[Error - 17:26:22] ESLint stack trace:
[Error - 17:26:22] TypeError: Cannot read property 'range' of undefined
    at C:\GitHub\ng10\node_modules\@angular-eslint\eslint-plugin-template\dist\index.js:1:1953
    at Array.map (<anonymous>)
    at postprocess (C:\GitHub\ng10\node_modules\@angular-eslint\eslint-plugin-template\dist\index.js:1:1762)
    at Linter._verifyWithProcessor (C:\GitHub\ng10\node_modules\eslint\lib\linter\linter.js:1327:16)
    at Linter._verifyWithConfigArray (C:\GitHub\ng10\node_modules\eslint\lib\linter\linter.js:1264:25)
    at Linter.verify (C:\GitHub\ng10\node_modules\eslint\lib\linter\linter.js:1226:25)
    at Linter.verifyAndFix (C:\GitHub\ng10\node_modules\eslint\lib\linter\linter.js:1416:29)
    at verifyText (C:\GitHub\ng10\node_modules\eslint\lib\cli-engine\cli-engine.js:224:48)
    at CLIEngine.executeOnText (C:\GitHub\ng10\node_modules\eslint\lib\cli-engine\cli-engine.js:882:26)
    at c:\Users\root\.vscode\extensions\dbaeumer.vscode-eslint-2.1.8\server\out\eslintServer.js:1:40795
```

This issue happens right here due to `no-positive-tabindex` rule isn't an auto-fixable => the passed message hasn't `fix` property. So, additional check needed here.
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L190

**Comment by AlexanderFSP** [comment]
Also I have found the issue with the `preprocessComponentFile` function returns wrong interface. According to [ESLint docs](https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins) this function must return an array of code blocks (`{ text: string; filename: string }[]`).

But in most places it returns just `text`:
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L15
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L30
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L55
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L77
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L82
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L98
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L105
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L129
https://github.com/angular-eslint/angular-eslint/blob/b30fd0e9c8fe35b7cda8117131c2f836a5bcace0/packages/eslint-plugin-template/src/processors.ts#L145

**Comment by AlexanderFSP** [comment]
Will fix it on my own :sunglasses:

**Comment by JamesHenry** [comment]
> Also I have found the issue with the `preprocessComponentFile` function returns wrong interface. According to [ESLint docs](https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins) this function must return an array of code blocks (`{ text: string; filename: string }[]`).

Sure, that additional capability to add a filename was added in ESLint v6, but it is clearly still valid to return just the string of the text when you don't need the filename, as we have been doing it since the beginning and it demonstrably works, so I wouldn't really call it an issue right now :) 

If you've managed to reliably reproduce your underlying issue and you are working on a fix for that then that's great!

**Comment by AlexanderFSP** [comment]
@JamesHenry , also a small point regarding this great monorepo. I think it'll be very helpful to add global dev ESLint config to make it more organized :)

**Comment by JamesHenry** [comment]
Yes, thanks, a separate issue to track would be good, I will add in a linting setup with minimal (and non-controversial) rules, I don't think we need a ton
