### ISSUE TITLE
Failed to load plugin '@angular-eslint/template' -  Cannot find module 'functions-have-names' - transitive dependency

### ISSUE THREAD

**Issue by brabenetz** [angular-eslint/angular-eslint#1522]
I hope it's the right place here:
Version: @angular-eslint/eslint-plugin-template@15.2.1 (not tested with newer version 16)

## Problem:
Exception during eslint using extention 'plugin:@angular-eslint/template/process-inline-templates':

```
An unhandled exception occurred: Failed to load plugin '@angular-eslint/template' declared in '.eslintrc.json » ...': Cannot find module 'functions-have-names'
Require stack:
- ...\foo-spa\node_modules\set-function-name\index.js
- ...\foo-spa\node_modules\regexp.prototype.flags\implementation.js
- ...\foo-spa\node_modules\regexp.prototype.flags\index.js
- ...\foo-spa\node_modules\deep-equal\index.js
- ...\foo-spa\node_modules\aria-query\lib\elementRoleMap.js
- ...\foo-spa\node_modules\aria-query\lib\index.js
- ...\foo-spa\node_modules\@angular-eslint\eslint-plugin-template\dist\index.js
- ...\foo-spa\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
```

## Reason:

Transitive dependency "functions-have-names" is not provided anymore by "regexp.prototype.flags"
![image](https://github.com/angular-eslint/angular-eslint/assets/1237858/2c3be882-e7d0-4dcf-99b5-6ccce043c7db)

New Patch Version of "regexp.prototype.flags" was released 2023-09-13 5:29 UTC (4h ago)
https://www.npmjs.com/package/regexp.prototype.flags?activeTab=versions

The old Dependency-Tree was:
```
├─┬ @angular-eslint/eslint-plugin-template@15.2.1
│ ├─┬ aria-query@5.1.3
│ │ └─┬ deep-equal@2.2.2
│ │   ├─┬ regexp.prototype.flags@1.5.0
│ │   │ ├── call-bind@1.0.2 deduped
│ │   │ ├── define-properties@1.2.0 deduped
│ │   │ └── functions-have-names@1.2.3
```

## Proposed solution:
Add "functions-have-names" as transitive dependency to the eslint-project

**Comment by brabenetz** [comment]
FYI: there is also a ticket on the 'RegExp.prototype.flags' library: https://github.com/es-shims/RegExp.prototype.flags/issues/27

**Comment by panicoenlaxbox** [comment]
Hi,

I'm just creating a new project with Angular 16 and I'm having the same problem.

```
ng new app1
ng add @angular-eslint/schematics
npm run lint
```

```
An unhandled exception occurred: Cannot find module 'functions-have-names'
Require stack:
- C:\Temp\app1\node_modules\set-function-name\index.js
- C:\Temp\app1\node_modules\regexp.prototype.flags\implementation.js
- C:\Temp\app1\node_modules\regexp.prototype.flags\index.js
- C:\Temp\app1\node_modules\deep-equal\index.js
- C:\Temp\app1\node_modules\axobject-query\lib\elementAXObjectMap.js
- C:\Temp\app1\node_modules\axobject-query\lib\index.js
- C:\Temp\app1\node_modules\@angular-eslint\eslint-plugin-template\dist\utils\is-interactive-element\get-interactive-element-ax-object-schemas.js
- C:\Temp\app1\node_modules\@angular-eslint\eslint-plugin-template\dist\utils\is-interactive-element\index.js
- C:\Temp\app1\node_modules\@angular-eslint\eslint-plugin-template\dist\rules\click-events-have-key-events.js
- C:\Temp\app1\node_modules\@angular-eslint\eslint-plugin-template\dist\index.js
- C:\Temp\app1\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Occurred while linting C:\Temp\app1\src\index.html:3
Rule: "@angular-eslint/template/click-events-have-key-events"
See "C:\Users\SERGIO~1.ANA\AppData\Local\Temp\ng-ErxYWp\angular-errors.log" for further details.
```

**Comment by brabenetz** [comment]
Quickfix: just add "functions-have-names": "1.2.3" do your devDependencies

**Comment by glenstaes** [comment]
The `overrides` configuration in `package.json` as suggested here https://github.com/es-shims/RegExp.prototype.flags/issues/27#issuecomment-1717110100 , is a more suitable option in my opinion.

It makes the workaround more explicit. You won't remember in a few weeks/months that `functions-have-names` is not an explicit dependency of your project.

```json
"overrides": {
    "deep-equal": {
      "regexp.prototype.flags": "npm:regexp.prototype.flags@1.5.0"
    }
  }

**Comment by brabenetz** [comment]
can be closed.
It is now fixed with: https://github.com/ljharb/set-function-name/issues/1
