### ISSUE TITLE
Type declaration files are missing from the distributed packages

### ISSUE THREAD

**Issue by sean-perkins** [angular-eslint/angular-eslint#1523]
**Description and reproduction of the issue**

It appears that type declaration files are missing in the bundled and published packages, including `@angular-eslint/template-parser`. 

For example, with: https://cdn.jsdelivr.net/npm/@angular-eslint/template-parser@16.1.2/ the `package.json` refers to a type declaration file in `dist/index.d.ts` that does not exist in the bundle. 

The package itself extends the root `tsconfig.base.json` which disables generating type declaration files: https://github.com/angular-eslint/angular-eslint/blob/main/tsconfig.base.json#L6

This results in errors when using the package in typescript environments and prevents any type detection on the public APIs.

Is this intended?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/template-parser`  | `16.1.2` |
| `ESLint`                           | `8.0.0` |
| `node`                             | `18.0.0` |

I'm not using this package in an Angular workspace, but a typescript project that needs to parse Angular component templates. 

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@sean-perkins It isn't intentional, we simply haven't had many people attempting to use the parser programmatically as far as I know, and it's not a use-case I have personally needed.

PR welcome to resolve this!

**Comment by joeyj** [comment]
It looks like my PR didn't fix this :( Sorry about that! I'm still unsure why the type definition files are missing from the package. Someone with more knowledge of the CI used by this repo will need to investigate.
