### ISSUE TITLE
[prefer-ngsrc] Disable the rule if the src is a Base64-encoded string

### ISSUE THREAD

**Issue by scurk1415** [angular-eslint/angular-eslint#1543]
**Description and reproduction of the issue**

The `"@angular-eslint/template/prefer-ngsrc": "error"` rule does not check for instances of Base64-encoded string (which are valid src values, but are not supported with the NgOptimizedImage).

When putting the Base64-encoded string into ngSrc we get this runtime error
```
ERROR Error: NG02952: The NgOptimizedImage directive has detected that `ngSrc` is a Base64-encoded string (data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDov...). NgOptimizedImage does not support Base64-encoded strings. To fix this, disable the NgOptimizedImage directive for this element by removing `ngSrc` and using a standard `src` attribute instead.
```

```JSON
{
  "rules": {
    "@angular-eslint/template/prefer-ngsrc": "error"
  }
}
```

I didn't add you library to this reproduction example, as I think it is clear where the issue is
https://stackblitz.com/edit/angular-slnnqs?file=src%2Fmain.ts

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.2.0` |
| `@angular-eslint/template-parser`         | `16.2.0` |
| `@typescript-eslint/parser`               | `5.62.0` |
| `ESLint`                                  | `8.49.0` |
| `node`                                    | `18.12.1` |

```sh
Angular CLI: 16.2.3
Node: 18.12.1
Package Manager: npm 7.11.1
OS: win32 x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@scurk1415 would you like to submit a PR for this?
