### ISSUE TITLE
peer dependency on typescript-eslint@5

### ISSUE THREAD

**Issue by alexfung888** [angular-eslint/angular-eslint#1544]
**Description and reproduction of the issue**

reproduction: build a package with typescript-eslint@6
description: eslint gives tons of error messages regarding modules not found.

there is no problem if I stay on typescript-eslint@5.62.0, but typescript-eslint is @6 since a *long* time ago. It is already on @6.7.5 today.

I am not sure whether it is a builder problem, but I can't post an issue to @angular-eslint itself.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `16.2.0` |
| `ESLint`                           | `8.51.0` |
| `node`                             | `18.8.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 16.2.6
Node: 18.18.0
Package Manager: yarn 3.6.4
OS: win32 x64

Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.6
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.2.6
@angular-devkit/schematics      16.2.6
@angular/cdk                    16.2.8
@angular/cli                    16.2.6
@angular/fire                   7.6.1
@angular/material               16.2.8
@schematics/angular             16.2.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

```

- [ X ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
It would will be in v17 https://github.com/angular-eslint/angular-eslint/pull/1454#issuecomment-1722260639

**Comment by alexfung888** [comment]
> It will be in v17 [#1454 (comment)](https://github.com/angular-eslint/angular-eslint/pull/1454#issuecomment-1722260639)

Thanks 😆

**Comment by JamesHenry** [comment]
typescript-eslint v6 is now used in the latest angular-eslint: https://github.com/angular-eslint/angular-eslint/releases/tag/v17.0.0
