### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by d-koppenhagen** [angular-eslint/angular-eslint#1568]
Angular 17 is almost out and it would be awesome to support it quite fast after the final release.
In my opinion it can already be tasted against the latest rc.

**Comment by JeanMeche** [comment]
There is a pending PR #1563 !

**Comment by JamesHenry** [comment]
Hot on the heels of Angular v17, angular-eslint v17 is now available: https://github.com/angular-eslint/angular-eslint/releases/tag/v17.0.0
