### ISSUE TITLE
Schematic for adding component suffixes

### ISSUE THREAD

**Issue by cyrilletuzi** [angular-eslint/angular-eslint#158]
First, thanks for the hard work! 👍🏻 

Using different component suffixes to differentiate component types (pure / dumb / presentational vs impure / page / ~ controller) is a widely used and good practice in Angular, which is officially supported by:
- the `component-class-suffix` from `codelizer`, which is already supported by `angular-eslint`
- the `--type` option in Angular CLI >= 9: `ng g component hello --type page`

Apart #157 issue, the support for custom suffixes in `angular-eslint` also requires quite a lot of manual configuration:
- `"files": ["*.component.html", "*.page.html"]` in `.eslintrc.json`
- `"files": ["*.component.ts", "*.page.ts"]` in `.eslintrc.json`
- `"lintFilePatterns": ["src/**/*.ts", "src/**/*.component.html", "src/**/*.page.html"]` in `angular.json`
- `"@angular-eslint/component-class-suffix": ["error", { "suffixes": ["Component", "Page"] }]` in `.eslintrc.json`

For comparison, TSLint just required the last one.

So would you be OK if I plan a PR add a schematic to add a new component suffix which would do all the above automatically?

As a side note, I would like to bring to your attention that such kind of manual configuration can become very difficult to manage, as I already encountered such issues with tools like [`typescript-strictly-typed`](https://github.com/cyrilletuzi/typescript-strictly-typed/) (see [issue 3](https://github.com/cyrilletuzi/typescript-strictly-typed/issues/3)). Indeed, for now `angular-eslint` is using a JSON file config, which is easy to modify, but ESLint also supports a `.eslintrc.js` config file (which has priority over `.eslintrc.json`), which is required for some advanced cases (like dynamic configurations using environment variables), and parsing and modifying a JS file is way more complicated than a JSON.

**Comment by JamesHenry** [comment]
I believe this can now be closed now that we do not use the suffix anywhere (as of 0.7.x). Please feel free to reopen if I'm mistaken.
