### ISSUE TITLE
parser: errors when using `@defer` with angular-eslint v17

### ISSUE THREAD

**Issue by cexbrayat** [angular-eslint/angular-eslint#1603]
**Description and reproduction of the issue**

The parser fails on templates using `@defer` syntax with angular-eslint v17 (but not with angular-eslint v16.3.1).

```html
@defer (when show) {
  <ns-chart />
}
```

See https://github.com/cexbrayat/eslint-defer for a repro

Error:
```
  0:0  error  Parsing error: Cannot create property 'type' on string 'when'
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/template-parser`  | `17.0.0` |
| `ESLint`                           | `8.53.0` |
| `node`                             | `18.18.2` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 17.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Thanks a lot for the repro @cexbrayat, I have verified that https://github.com/angular-eslint/angular-eslint/pull/1604 fixes the issue on that repo, I'll cut a release as soon as CI is green
