### ISSUE TITLE
Rule Option Proposal: no-host-metadata-property allow-static

### ISSUE THREAD

**Issue by MikeMatusz** [angular-eslint/angular-eslint#161]
The rationale behind Angular Style [06-03](https://angular.io/guide/styleguide#style-06-03) doesn't really apply to static cases, where you want to set the property of a host to a constant value.  I'd like to propose optionally allowing an exception to the rule to only forbid dynamic host properties, indicated by brackets or parentheses, e.g. `[property]` or `(property)`.

Example configuration:
`'@angular-eslint/no-host-metadata-property': ['error', 'allow-static']`

Example allowed usage:
```ts
@Component({
    selector: 'my-component',
    templateUrl: 'my-component.html',
    host: { class: 'my-component' }
})
export class MyComponent {
```

As the alternative HostBinding in this case would set up unnecessary change detection, even though the property could be `readonly`.  Additionally, since it's something that any consumer of the component can rely on as being constant, it seems like metadata is an appropriate place to specify it.

**Comment by MikeMatusz** [comment]
@JamesHenry Any feedback on whether a PR for this option would be considered?  I can just disable this rule in my configuration and write a custom rule, but figured I'd propose it here first in case anyone else found the distinction useful.

**Comment by JamesHenry** [comment]
I don't see any particular issues in supporting this case, although we should probably have it off by default. It's not personally something I've run into or feel strongly about, but I would happily accept a PR.

I think it might be more idiomatic to have the config look like this:

```json
"@angular-eslint/no-host-metadata-property": ["error", { "allowStatic": true }]
```
