### ISSUE TITLE
Blank lines printed when using "quiet" option

### ISSUE THREAD

**Issue by miked1090** [angular-eslint/angular-eslint#164]
Hello,

If there are warnings from eslint and the quiet option is used, there will be blank lines printed instead of the warnings.

**Comment by JamesHenry** [comment]
Please could you give a little more information?

The `quiet` option is specifically designed to suppress warnings: https://eslint.org/docs/user-guide/command-line-interface#-quiet

Are you referring to something different?

**Comment by miked1090** [comment]
Sorry, I should have explained a bit more. It does suppress the warnings, but when running the lint task in a terminal and there are warnings present in the code, there are large gaps of blank space printed.

For example, if there are warnings and errors in the code and lint is ran with --quiet. The errors get printed, but with large amounts of blank space between them. 

If there are warnings in the code with no errors, with --quiet. There's a large amount of blank space between the start lint log and the ending "All files pass linting" log.

If there are no warnings, but there are errors in the code with --quiet, the logs print as they should. The errors print one after another with no blank space between them.

Here's a screenshot of a case with warnings in the code, but no errors.

![image](https://user-images.githubusercontent.com/9553515/96897692-e0714b00-145c-11eb-9639-93ebd5a5e1b6.png)
![image](https://user-images.githubusercontent.com/9553515/96897736-ed8e3a00-145c-11eb-80cf-420372a89254.png)

**Comment by JamesHenry** [comment]
Ah gotcha, want to take a stab at a fix?
