### ISSUE TITLE
directive-selector does not ignore indentation differences nor work with multiple selectors

### ISSUE THREAD

**Issue by laurentgoudet** [angular-eslint/angular-eslint#166]
Using `{ type: 'attribute', prefix: ['app'], style: 'kebab-case' }`, this works:

```
@Directive({
  selector: `[app-foo-bar]`
})
```

but this does not, while it used to in the former Codelyzer rule:

```
@Directive({
  selector: `
    [app-foo-bar]
  `
})
```

This also used to work but no longer does, and is commonly used in "advanced" directives:

```
@Directive({
  selector: `
    [app-foo-bar],
    [app-foo-baz]
  `
})
```

Looking at the code in https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/utils/property-selector.ts#L165, the selector list is parsed with `CssSelector.parse()` but the result is ignored when checking for prefixes and the rule simply work at the raw string level, instead of working at the CSS AST one:

```
listSelectors = CssSelector.parse(node.quasis[0].value.raw);
hasExpectedPrefix = arrayify<string>(
  node.quasis[0].value.raw as string,
).some((selector) =>
  prefixOption.some((prefix) =>
    SelectorValidator.prefix(prefix, styleOption)(selector),
  ),
);
```

**Comment by johncrim** [comment]
Another (related) case that works with tslint/codelyzer but no longer works:

```
@Directive({
  selector: 'button[app-foo]'
})
```

This is valid for the attribute selector rule listed above, but is rejected by the eslint rule.

**Comment by JamesHenry** [comment]
PRs welcome on these things!

**Comment by GavinWu1991** [comment]
I thought I'd try to do something about this issue this week!
