### ISSUE TITLE
[prefer-self-closing-tags] `<app-root />` breaks Angular CLI's build output.

### ISSUE THREAD

**Issue by lacolaco** [angular-eslint/angular-eslint#1663]
**Description and reproduction of the issue**

Typically, ESLint config for HTML files in an Angular project is like below: `files:["*.html"]`. This setting includes `src/index.html`, and `prefer-self-closing-tags` rule checks any components in that.

```json
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {
        "@angular-eslint/template/prefer-control-flow": ["error"]
      }
    },
```

But if `<app-root>` is changed as `<app-root />`, Angular CLI's build output breaks. HTML perser in esbuild-based Angular CLI seems not supporting self-closing the custom element. As below, `<script>` tags are inserted between `<app-root>` tags. 

```html
  <body>
    <app-root>
      <script src="runtime.93077a601f1aa8fd.js" type="module"></script>
      <script src="polyfills.f4ed13a3431d30a8.js" type="module"></script>
      <script src="main.f623c690de443919.js" type="module"></script
    ></app-root>
  </body>
</html>
```

```JSON
{
  "rules": {
    "@angular-eslint/template/prefer-self-closing-tags": ["error"]
  }
}
```

```HTML
<!doctype html>
<html lang="ja">
  <head>
    ...
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `17.1.1` |
| `@angular-eslint/template-parser`         | `17.1.1` |
| `@typescript-eslint/parser`               | `^6.0.0` |
| `ESLint`                                  | `^8.39.0` |
| `node`                                    | `^20.0.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@angular/cdk                    16.1.6
@angular/material               16.1.6
@schematics/angular             17.0.6
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

```

- [x] I have tried restarting my IDE and the issue persists.
- [ x I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
There isn’t any universally applicable solution to this that can be applied within the rule itself.

You have several possible workarounds/solutions on your side though:

- ignore the index.html file using .eslintignore file
- add an eslint disable comment above the relevant line in the index.html file
- amend the lintFilePatterns in your builder config in your angular.json so that it doesn’t include the index.html

You could also report this to the relevant tooling authors if you feel this should be supported by them
