### ISSUE TITLE
NX Missing Module on install

### ISSUE THREAD

**Issue by impurity-dev** [angular-eslint/angular-eslint#1665]
**Description and reproduction of the issue**
While running on bamboo, we have an install step. The install would cause an error "MODULE_NOT_FOUND" for `@nx/nx-linux-x64-gnu`. I cannot fully reproduce this as this was encountered at work, which I do not have adequant admin access to our bamboo instance or the ability to share more. I was able to fix the issue by rolling back all @angular-eslint packages from 17.1.1 to 17.0.0, but hopefully this identifies an issue for future fixes.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `17.1.1` |
| `ESLint`                           | `8.54.0` |
| `node`                             | `21.4.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 17.0.6
Node: 21.4.0 (Unsupported)
Package Manager: npm 10.2.4
OS: darwin x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@angular/cdk                    17.0.3
@angular/material               17.0.3
@schematics/angular             17.0.6
rxjs                            6.5.5
typescript                      5.2.2
zone.js                         0.14.2

```

- [x ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by Almamu** [comment]
Same issue and symptoms here, reverting to 17.0.0 fixes the issue.
```
npm ERR! path /home/vsts/work/1/s/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /home/vsts/work/1/s/node_modules/nx/src/native/index.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module '@nx/nx-linux-x64-gnu'
npm ERR! Require stack:
npm ERR! - /home/vsts/work/1/s/node_modules/nx/src/native/index.js
npm ERR! - /home/vsts/work/1/s/node_modules/nx/src/hasher/task-hasher.js
npm ERR! - /home/vsts/work/1/s/node_modules/nx/src/tasks-runner/run-command.js
npm ERR! - /home/vsts/work/1/s/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js
npm ERR! - /home/vsts/work/1/s/node_modules/nx/bin/post-install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:985:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at Object.<anonymous> (/home/vsts/work/1/s/node_modules/nx/src/native/index.js:184:31)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/vsts/work/1/s/node_modules/nx/src/native/index.js',
npm ERR!     '/home/vsts/work/1/s/node_modules/nx/src/hasher/task-hasher.js',
npm ERR!     '/home/vsts/work/1/s/node_modules/nx/src/tasks-runner/run-command.js',
npm ERR!     '/home/vsts/work/1/s/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
npm ERR!     '/home/vsts/work/1/s/node_modules/nx/bin/post-install.js'
npm ERR!   ]
npm ERR! }
```

We are not using nx in our project.

**Comment by JamesHenry** [comment]
Please kindly follow the guidance here: 

https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#native-modules

**Comment by JamesHenry** [comment]
I'm going to close this one, if following the above instructions has not solved the issue for you please open an issue on the Nx repo

**Comment by whjvenyl** [comment]
Redirecting to the nx documentation seems counter-intuitive if the project does not use nx at all.

**Comment by loetscher** [comment]
Same issue here.

- Downgrade from `@angular-eslint/builder@17.1.1` to `@angular-eslint/builder@17.0.0` fixed the issue as already mentioned
- Upgrade from `@angular-eslint/builder@17.1.1` to `@angular-eslint/builder@17.3.0` fixed the issue as well

**Comment by orestisioakeimidis** [comment]
Same issue with out project which is not using NX. 

@JamesHenry Why is it required to use NX and follow NX guidelines for this project?

**Comment by toxaq** [comment]
Is there a version 16 without the NX dependency? I'm not using NX and this is causing CI issues.

**Comment by riscie** [comment]
> Same issue here.
> 
> * Downgrade from `@angular-eslint/builder@17.1.1` to `@angular-eslint/builder@17.0.0` fixed the issue as already mentioned
> * Upgrade from `@angular-eslint/builder@17.1.1` to `@angular-eslint/builder@17.3.0` fixed the issue as well

Thank you for your comment.
I had to downgrade to 17.0.0. 17.3.0 did not work for me.
