### ISSUE TITLE
[eqeqeq] Incorrectly updates the template when run with '--fix' option

### ISSUE THREAD

**Issue by phalgunv** [angular-eslint/angular-eslint#1666]
**Description and reproduction of the issue**

Please see isolated reproduction repo at [eslint-autofix-issue](https://github.com/phalgunv/eslint-autofix-issue). Steps to reproduce

1. git clone https://github.com/phalgunv/eslint-autofix-issue
2. cd eslint-autofix-issue; npm install;
3. npm run ng lint -- --fix

app.component.html will get updated incorrectly after step 3. 
Please note, the code in this repository is a strip-down version of code from a enterprise project where the issue was originally found.

```JSON
{
  "rules": {
    "@angular-eslint/template/eqeqeq": "error"
  }
}
```

```HTML
<h1>Minimal example to demo issue with eslint --fix</h1>
<ng-container>
	<ng-container>
		<ng-container>
			<ng-container>
				<ng-container>
					<ng-container>
						<ng-container>
							<app-test
								[labelStyle]="
									formGroup.controls[field.options.stateKey].value == '' &&
									formGroup.controls[field.options.stateKey].dirty
										? invalidLabelStyle
										: labelStyle
								"
							>
							</app-test>
						</ng-container>
					</ng-container>
				</ng-container>
			</ng-container>
		</ng-container>
	</ng-container>
</ng-container>
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `15.2.1` |
| `@angular-eslint/template-parser`         | `15.2.1` |
| `@typescript-eslint/parser`               | `5.48.2` |
| `ESLint`                                  | `^8.33.0` |
| `node`                                    | `v16.20.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.10
Node: 16.20.0
Package Manager: npm 8.19.4
OS: linux x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@schematics/angular             15.2.10
rxjs                            7.8.1
typescript                      4.9.5

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by json-derulo** [comment]
The reproduction can be simplified a lot. The following code has the same issue, also in Angular v17:

```html
<app-test
  [labelStyle]="
    formGroup.controls[field.options.stateKey].value == '' &&
    formGroup.controls[field.options.stateKey].dirty
      ? invalidLabelStyle
      : labelStyle
  "
>
</app-test>
```

It seems like the white spaces between the quotes and start of the expression are not taken into consideration. The following code would work correctly:

```html
<app-test
  [labelStyle]="formGroup.controls[field.options.stateKey].value == '' &&
    formGroup.controls[field.options.stateKey].dirty
      ? invalidLabelStyle
      : labelStyle
  "
>
</app-test>
```

This format is commonly used also by auto-formatters like prettier, so it should definitely be fixed.

**Comment by phalgunv** [comment]
In the isolated reproduction repo, I have added prettier to ensure that eslint runs after auto-formatting has happened.

**Comment by balkaninal** [comment]
same here so annoying

```
<i
    class="d-inline-block"
    [ngClass]="
        'famfamfam-flags ' +
        (translation.language == 'en'
            ? 'us'
            : translation.language)
    "
    [title]="
        translation.language.toUpperCase()
"></i> 
```

to

```
 <i
     class="d-inline-block"
     [ngClass]="
         'famfamfam-flags ' +
         (translation.language ==
         'en'
    ==========         ? 'us'
             : translation.language)
     "
     [title]="
         translation.language.toUpperCase()
"></i>
```
```


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.11
Node: 18.16.1 (Unsupported)
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 13.4.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.3.11
@angular-devkit/schematics      13.3.11
@angular/cdk                    12.2.13
@angular/cli                    13.3.11
@schematics/angular             13.3.11
rxjs                            6.6.7
typescript                      4.5.4

```

| Header | Header |
|--------|--------|
| eslint| ^8.17.0|
| @typescript-eslint/parser| 5.27.1|
| @angular-eslint/template-parser| 13.5.0|
| @angular-eslint/eslint-plugin| 13.5.0|

**Comment by JamesHenry** [comment]
@balkaninal I’ll happily a review a PR to fix it, this is a community run project

**Comment by phalgunv** [comment]
> @balkaninal I’ll happily a review a PR to fix it, this is a community run project
@JamesHenry 
Would you help with review of https://github.com/angular-eslint/angular-eslint/pull/1709?

**Comment by phalgunv** [comment]
Thanks @JamesHenry and @estevezluis. I would like to be able to contribute, but do not quite know where to start. It would be great if some guidance is provided.
