### ISSUE TITLE
[Suggestion] The prefix configured in eslintrc.json should use the ones specified in the angular.json

### ISSUE THREAD

**Issue by hanct** [angular-eslint/angular-eslint#169]
Hi,

Currently, my angular.json configured using "cb" as the prefix., 
When i run the lint, i observe that it flagged out error that my selector should use prefix. 
Then i realize in the eslintrc.json (as shown below), it is by default configured to use "app" as prefix. I have to manually change the "app" to "cb" to extinguish the error. 

"@angular-eslint/directive-selector": [
          "error",
          { "type": "attribute", "prefix": "app", "style": "camelCase" }
        ],
        "@angular-eslint/component-selector": [
          "error",
          { "type": "element", "prefix": "app", "style": "kebab-case" }
        ],

I was wondering, whether it is possible for the generated eslintrc to automatically use the prefix specified in the angular.json as the default, instead of developers having to change them manually.

**Comment by JamesHenry** [comment]
Closing as no longer applicable post v1, the prefix is consistently used by the tooling:

- if you are converting a TSLint component-selector or directive-selector rule it will use whatever custom prefix is specified in your tslint.json
- if you are creating a new ESLint project with no TSLint involvement, it will pass through any custom `--prefix` from the `ng generate` command and use that.

Thanks!
