### ISSUE TITLE
[no-input-rename] support signal input/model

### ISSUE THREAD

**Issue by xXNickznXx** [angular-eslint/angular-eslint#1723]
## Request
The rule doesnt display errors on the new signal [input](https://angular.dev/api/core/input?tab=usage-notes) and [model](https://angular.dev/api/core/model?tab=usage-notes). Both cases should also be supported.

### Example
```js
foo = input('text', { alias: 'bar' });
foo2 = model('text', { alias: 'bar2' });
```

**Comment by reduckted** [comment]
#2098 should fix this for the `input` function. The `model` function will need a separate fix. Should that be a new rule (`no-model-rename`), or should it be part of the `no-input-rename` rule?

**Comment by JamesHenry** [comment]
This was addressed in v19
