### ISSUE TITLE
[@typescript-eslint/array-type] Definition for rule '@typescript-eslint/array-type' was not found

### ISSUE THREAD

**Issue by AliceZhuZhu** [angular-eslint/angular-eslint#1727]
**after update angular-eslint from v15 to v17, Definition for rule '@typescript-eslint/array-type' was not found**

```JSON
{
   "extends": [
        "plugin:@angular-eslint/recommended"
    ],
   "plugins": [
        "eslint-plugin-jsdoc"
    ],
  "rules": {
    "@typescript-eslint/array-type": [
      "error",
      {
        "default": "array"
      }
    ]
  }
}
```

```TS
// The rule definition is valid in the playground.
https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=LAKCA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRgA2uGw5EXAPbRIAGlFisY7JAAmiAGbsE%2BQZE7dCkBdgC%2BJgLqjzpoA&tsconfig=&tokens=false

```
![image](https://github.com/angular-eslint/angular-eslint/assets/36066123/f10e3c77-e4ff-4a01-8aad-f92e5ac2cfac)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `17.1.0` |
| `@typescript-eslint/parser`        | `6.20.0` |
| `ESLint`                           | `8.57.0` |
| `node`                             | `18.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
@angular-devkit/architect       0.1702.2
@angular-devkit/build-angular   17.2.2
@angular-devkit/core            17.2.2
@angular-devkit/schematics      17.2.2
@angular/animations             17.2.3
@angular/cli                    17.2.2
@angular/compiler-cli           17.2.3
@angular/elements               17.2.3
@schematics/angular             17.2.2
rxjs                            7.4.0
typescript                      5.2.2
zone.js                         0.14.4


```

- [v] I have tried restarting my IDE and the issue persists.
- [v] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

This `eslintrc.json` file works fine in `angular-eslint` v15, and I didn't find that `@typescript-eslint/array-type` rule was removed in releases.
Thank you so much!

**Comment by tr1stan** [comment]
Hey @AliceZhuZhu, I think I've just come across a similar issue having upgraded an application from 15 > 17.

Can you try adding `plugin:@typescript-eslint/recommended` to your extends declaration to see if that helps.

so your: 
```
  "extends": [             
                "plugin:@angular-eslint/recommended"
            ],
```
becomes:
```
  "extends": [
                "plugin:@typescript-eslint/recommended",
                "plugin:@angular-eslint/recommended"
            ],
```
If that works, you might find, like me, that you now have a bunch of valid errors in your code, as I don't think the rules were being enforced in earlier versions of eslint because of the missing extends.

**Comment by AliceZhuZhu** [comment]
> Hey @AliceZhuZhu, I think I've just come across a similar issue having upgraded an application from 15 > 17.
> 
> Can you try adding `plugin:@typescript-eslint/recommended` to your extends declaration to see if that helps.
> 
> so your:
> 
> ```
>   "extends": [             
>                 "plugin:@angular-eslint/recommended"
>             ],
> ```
> 
> becomes:
> 
> ```
>   "extends": [
>                 "plugin:@typescript-eslint/recommended",
>                 "plugin:@angular-eslint/recommended"
>             ],
> ```
> 
> If that works, you might find, like me, that you now have a bunch of valid errors in your code, as I don't think the rules were being enforced in earlier versions of eslint because of the missing extends.

Hi @tr1stan,

Thank you very much for your comment!
This helps me a lot.

Thanks,
Alice
