### ISSUE TITLE
Error: The `convert-tslint-to-eslint` schematic is no longer supported.

### ISSUE THREAD

**Issue by colincameron** [angular-eslint/angular-eslint#1728]
**Description and reproduction of the issue**

When running the steps described in https://github.com/angular-eslint/angular-eslint/blob/main/docs/MIGRATING_FROM_TSLINT.md, I get the following error at step 2:

```
% ng g @angular-eslint/schematics:convert-tslint-to-eslint
Node.js version v21.6.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.

Error: The `convert-tslint-to-eslint` schematic is no longer supported.

Please see https://github.com/angular-eslint/angular-eslint/blob/main/docs/MIGRATING_FROM_TSLINT.md
```

The "please see" link points back to the exact same instructions that I was running.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `X.Y.Z` |
| `@typescript-eslint/parser`        | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Node.js version v21.6.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/previous-releases/.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.2.3
Node: 21.6.1 (Unsupported)
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cli                    17.2.3
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
    
Warning: The current version of Node (21.6.1) is not supported by Angular.

```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@colincameron you seem to have skipped over the first section which explains everything in detail

**Comment by colincameron** [comment]
Ah ok sorry I misunderstood. I thought the first section was describing a conversion method that was removed in favour of the manual steps below.

**Comment by JamesHenry** [comment]
All good! I’m sorry that you’re still dealing with the migration at this point 😄 hopefully either the linked tooling and/or the git history on this repo is useful for you
