### ISSUE TITLE
Is there a linting role for detecting duplicated imports?

### ISSUE THREAD

**Issue by jon9090** [angular-eslint/angular-eslint#1754]
for example:

```
@Compoennt({
   imports: [CommonModule, SomeOtherModule, CommonModule.....]
})
```

**Comment by abaran30** [comment]
There currently is not. Should one be created, perhaps it should also check `declarations`, `exports`, `providers`, etc.

I did not see any prior proposals in the issues. @JamesHenry has this idea been discussed before?

**Comment by JamesHenry** [comment]
I don't believe so, I think it would make sense to add

**Comment by abaran30** [comment]
I created a draft PR #1779, which currently handles the simplest case of a single duplicate in NgModule imports. I left `TODO` comments with questions around how we might want to configure the rule to handle different cases (maybe we want multiple rules).

Feel free to refer to and/or contribute to the PR. I'll contribute more when I can.
