### ISSUE TITLE
Unexpected 9MB binary produced from `@angular-eslint/schematics`: `.nx/cache/18.3.3-nx.linux-x64-gnu.node`

### ISSUE THREAD

**Issue by johnnygerard** [angular-eslint/angular-eslint#1784]
A ~9MB binary is generated from `@angular-eslint/schematics@17.3.0`.
I'm assuming it is a regression bug maybe after your migration to Nx 18.

To reproduce:

```sh
ng new app --defaults
cd app
ng add @angular-eslint/schematics --skip-confirmation
```

You should see this file: `app/.nx/cache/18.3.3-nx.linux-x64-gnu.node`.

**Environment:**

```txt
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.5
Node: 20.12.2
Package Manager: npm 10.5.2
OS: linux x64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Added dependencies:**
```txt
    "@angular-eslint/builder": "17.3.0",
    "@angular-eslint/eslint-plugin": "17.3.0",
    "@angular-eslint/eslint-plugin-template": "17.3.0",
    "@angular-eslint/schematics": "17.3.0",
    "@angular-eslint/template-parser": "17.3.0",

    "@typescript-eslint/eslint-plugin": "7.2.0",
    "@typescript-eslint/parser": "7.2.0",
    "eslint": "^8.57.0",
```

**Comment by robertIsaac** [comment]
I think eslint should add `.nx` to `.gitignore`

**Comment by MonsieurBon** [comment]
I also have this file after running `ng update @angular/core@17 @angular/cli@17 @angular-eslint/schematics@17`. We are not using nx in our project and I'm therefore surprised this is needed!

**Comment by tyzess** [comment]
Same here. With @angular-eslint 17.3.0 the nx/devkit/nwl dependencies find their way into the project. Even breaks my build process `Error: Cannot find module '@nx/nx-linux-x64-gnu'`. Why are they suddenly required by @angular-eslint?

**Comment by dertuerke** [comment]
same here

**Comment by ranma42** [comment]
@tyzess they were removed but then added again (see https://github.com/angular-eslint/angular-eslint/pull/1142#issuecomment-1769584479 )
I too would like to remove the dependency on nx (in the comment I offered to work on a PR in that direction).

**Comment by jonasduever** [comment]
Con confirm this and it is a little bit annoying because it adds this binary _and_ breaks CI (same error as @tyzess). There are possible [workarounds](https://github.com/nrwl/nx/issues/17767#issuecomment-1630543307) for all of this, but I don't really like adding them (temporarily?) for a dev dependency.
Will try to downgrade (to v17.2.x?) for now.

**Comment by JamesHenry** [comment]
Hi Folks, being able to leverage `@nx/devkit` gives me a greatly improved developer experience for building `@angular-eslint/schematics` and `@angular-eslint/builder`.

For maximum speed and efficiency the internals of Nx are written in rust, so the native code is referenced via that .node file. It used to be placed inside the node_modules so you never saw it, now it lives in the `.nx` directory. I can understand why it seems unexpected to have that directory in an Angular workspace that isn't leveraging Nx directly, so please leave this with me and I'll discuss with the Nx team and get back to you on here.

For now, gitignoring the directory is the expected solution. Not being able to find the file is definitely unexpected @tyzess @jonasduever - is the file missing from your package-lock.json (or equivalent)?

Many thanks!

**Comment by jonasduever** [comment]
@JamesHenry Thanks for your feedback!
My guess would be the different OS/architecture.
In my case:
- Development machine: Windows
- Azure DevOps Pipeline: Linux
- In `package-lock.json`, there is only `@nx/nx-win32-x64-msvc` but **no** `@nx/nx-linux-x64-gnu` - probably because it's in `optionalDependencies` of `nx`?
- Azure DevOps Pipeline task (`Npm@1`) runs `npm ci` → Error:

```bash
npm ERR! code 1
npm ERR! path /home/vsts/work/1/s/frontend/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /home/vsts/work/1/s/frontend/node_modules/nx/src/native/native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module '@nx/nx-linux-x64-gnu'
npm ERR! Require stack:
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/native/index.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/node-task-hasher-impl.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/task-hasher.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/hash-task.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/tasks-runner/run-command.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js
npm ERR! - /home/vsts/work/1/s/frontend/node_modules/nx/bin/post-install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
npm ERR!     at Function.resolve (node:internal/modules/helpers:190:19)
npm ERR!     at Module._load (/home/vsts/work/1/s/frontend/node_modules/nx/src/native/index.js:53:36)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1231:19)
npm ERR!     at require (node:internal/modules/helpers:179:18)
npm ERR!     at Object.<anonymous> (/home/vsts/work/1/s/frontend/node_modules/nx/src/native/native-bindings.js:184:31)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1369:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1206:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1022:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/native/index.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/node-task-hasher-impl.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/task-hasher.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/hasher/hash-task.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/tasks-runner/run-command.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
npm ERR!     '/home/vsts/work/1/s/frontend/node_modules/nx/bin/post-install.js'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.12.2
```

**Comment by johnnygerard** [comment]
@JamesHenry Is the `.nx/cache/` directory and its contents required or is it a build artifact that can be deleted?

**Comment by ranma42** [comment]
> Hi Folks, being able to leverage `@nx/devkit` gives me a greatly improved developer experience for building `@angular-eslint/schematics` and `@angular-eslint/builder`.

Would it be possible to restrict the usage of `nx` to the building (i.e. avoid using it at runtime)?
AFAICT at runtime `angular-eslint` might be able to work with `@nx/devkit` (and without `nx`)?
That could provide a convenient DX while still reducing the issues of package dependencies.

> For maximum speed and efficiency the internals of Nx are written in rust, so the native code is referenced via that .node file. It used to be placed inside the node_modules so you never saw it, now it lives in the `.nx` directory. I can understand why it seems unexpected to have that directory in an Angular workspace that isn't leveraging Nx directly, so please leave this with me and I'll discuss with the Nx team and get back to you on here.

Another issue I pointed out regarding `nx` is that it pulls in several other dependencies, which are sometimes not well supported in some environments (for example I mentioned that my team was hitting some unexpected issues because `nx` pulled in `@parcel/watcher@2.0.4`, which did not provide pre-build packages for arm64).
The dependencies pulled in from `@nx/devkit` are fewer and hopefully more well-behaved :)

**Comment by ranma42** [comment]
I tried and wrote #1815 that preserves `nx` for building/testing the packages (very convenient, especially for fast iteration) but removes its uses from within the packages.

**Comment by JamesHenry** [comment]
@johnnygerard 

>  Is the .nx/cache/ directory and its contents required or is it a build artifact that can be deleted?

Right now, it will be repopulated if you delete it, so per my previous message the recommended action is to git ignore it

**Comment by JamesHenry** [comment]
@jonasduever

This should hopefully just be a matter of regenerating your lock file, you should then see all the native references in there.

**Comment by JamesHenry** [comment]
Update to https://github.com/angular-eslint/angular-eslint/issues/1784#issuecomment-2112101479: 

angular-eslint `17.4.1` is out now which ignores the native file in its current temporary location within the workspace

**Comment by jonasduever** [comment]
> if you browse your node_modules you will likely find other .node files from other tools, particularly compilers, bundlers, task runners etc.

In this pretty large Angular application, I only found one `*.node` file (`rollup` from `@angular-devkit/build-angular -> vite`).

I think most **build** tools can be kept as a dev dependency and are not actually used in the distributed package. I hoped that this was possible with `angular-eslint` + `nx` as well, but it seems that it's too much integrated into the application.

> This should hopefully just be a matter of regenerating your lock file, you should then see all the native references in there.

Will try this again in the next sprint, to be 100% sure. I'm pretty sure I did several completely fresh installs (no `node_modules`, no `package-lock.json`) when testing this. But maybe I messed up something. 🤞

@tyzess Did you solve this issue on your end in the meantime?

**Comment by JamesHenry** [comment]
@jonasduever Exactly, you had .node files in there you didn't realize already. It was definitely a mistake for nx to start caching the .node within the workspace source, and we are addressing that ASAP with the above linked PR, so it will go back to being an invisible implementation detail.

> I think most build tools can be kept as a dev dependency and are not actually used in the distributed package. I hoped that this was possible with angular-eslint + nx as well, but it seems that it's too much integrated into the application.

angular-eslint is still also a dev dependency and a devtool, it is not involved in your Angular application at all

> Will try this again in the next sprint, to be 100% sure. I'm pretty sure I did several completely fresh installs (no node_modules, no package-lock.json) when testing this. But maybe I messed up something. 🤞

Please open a fresh issue focused on your case if you run into any more issues and we will figure out it together!

**Comment by JamesHenry** [comment]
Nx `19.0.4` has been released, which is what the new angular-eslint `17.4.1` depends on (as long you refresh your dependencies), so you will no longer see the native file in your angular-eslint workspaces as long as you are using that latest version.

Thanks all, and sorry for the confusion!

**Comment by dertuerke** [comment]
@JamesHenry if have installed the latest versions but yet if I run ng lint they create a nx folder. 

How I can fix it?

**Comment by robertIsaac** [comment]
> @JamesHenry if have installed the latest versions but yet if I run ng lint they create a nx folder.
> 
> How I can fix it?

You should add .nx folder to the .gitignore

**Comment by JamesHenry** [comment]
@dertuerke check your lock file, it suggests you are still pulling in an older version of nx. For the most basic solution you could delete the lock file and regenerate it

**Comment by dertuerke** [comment]
I don’t use nx 🙈

**Comment by JamesHenry** [comment]
@dertuerke That's fine, as outlined on this thread, angular-eslint uses Nx in its implementation details. It's the same as all your other dependencies - they have dependencies themselves.

All those dependencies and dependencies of dependencies are specified in your lock file, and sometimes the lock file can pin dependencies of dependencies to older versions.

Please kindly try regenerating the lock file and it should fix your issue
