### ISSUE TITLE
Wrong error message for no-empty-lifecycle-method

### ISSUE THREAD

**Issue by napei** [angular-eslint/angular-eslint#181]
Came across this today, and I believe the error message it's displaying is wrong. Pretty sure the only place you can define a lifecycle method is inside a class. Perhaps `Declaring an empty ngOnInit lifecycle method is not recommended.` or `Lifecycle methods should not be empty.` as it's a best practice so saying `should not` translates that a bit better.

![image](https://user-images.githubusercontent.com/8946502/99228486-ca2e9300-2840-11eb-8ca0-ad876ed07d36.png)

https://github.com/angular-eslint/angular-eslint/blob/50b244751e940fc25c98bbcbec8cafca4e7a8b3d/packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts#L26

**Comment by JamesHenry** [comment]
Thanks @napei! Do you fancy opening a PR to make the change?

**Comment by napei** [comment]
@JamesHenry see #183
