### ISSUE TITLE
Migration Feedback

### ISSUE THREAD

**Issue by eluchsinger** [angular-eslint/angular-eslint#184]
I would like to give you feedback about what's missing in the migration process from my point of view. Thanks for your great work!

---------------------------------

In step 3 of the migration guide, I see no mention of Codelyzer and if I can remove it from the dependencies.

> ## Step 3 - Remove root TSLint configuration and use only ESLint
> Once you are happy with your ESLint setup, you simply need to remove the root-level tslint.json and potentially uninstall TSLint and any TSLint-related plugins/dependencies if your Angular CLI workspace is now no longer using TSLint at all.

------------------------------------

After doing the migration, I see the linting does not run automatically. I believe, work is still in progress to include it in the CLI, but there should be a guide to at least enable it for the IDE, for example Visual Studio Code. There is a mention of `vscode-eslint` further down the guide, but it should probably be placed either in Step 3 or 4. And also people didn't have to use that extension before the migration, so it should also be a bit more detailed as a lot of them won't know how that extension works.

------------------------------------

Can we remove the schematics `@angular-eslint/schematics`  after running them? Maybe even automatically?

**Comment by JamesHenry** [comment]
> potentially uninstall TSLint and any TSLint-related plugins/dependencies

👀 

Codelyzer is a TSLint plugin/dependency, wouldn't you say? 😁 

> I see the linting does not run automatically

Do you mean that your IDE is not automatically configured for you?

> Can we remove the schematics @angular-eslint/schematics after running them?

If you never want to add more projects to your workspace or take advantage of any other "generators" we may make in future, theoretically you could. We will be adding schematics to allow you to create new projects with ESLint directly (instead of having to convert them after generating them), for example.

I don't see any particular upside to removing them, and the downside is you'll have to remember you operating on a slightly custom setup...

**Comment by eluchsinger** [comment]
> 👀
> 
> Codelyzer is a TSLint plugin/dependency, wouldn't you say? 😁

I would say most people don't even know they are using Codelyzer (and less what it actually is), because it's included by default in the Angular CLI Generation Schematics. They don't have to opt in and they are not asked if they want to use Codelyzer.

> Do you mean that your IDE is not automatically configured for you?

I think what I meant is that you don't see the linting results when you're serving the application with `ng serve`. That was default before the migration. I believe, it's an ongoing discussion if you want to include it into the CLI right now, but we should at least point this out in the Docs.

**Comment by JamesHenry** [comment]
> I think what I meant is that you don't see the linting results when you're serving the application with ng serve.

I was genuinely not aware the Angular CLI did this. Please could you share a screenshot of what you are referring to?

**Comment by JamesHenry** [comment]
I haven't been able to reproduce seeing linting errors by default during ng serve, so going to close this for now. Please share a screenshot and/or instructions if I am mistaken
