### ISSUE TITLE
[@angular-eslint/schematics] Also provide ESModule syntax (in addition to commonJS)

### ISSUE THREAD

**Issue by rzschoch** [angular-eslint/angular-eslint#1859]
I am very happy about the latest updates for the new flat configuration that is required with ESlint 9.

In the meantime, however, I have also invested a lot of time unsuccessfully to find a configuration in ESModule syntax that works with Angular 18. 

I find this syntax more favourable, as all other eslint plugins and the official ESlint documentation also use module syntax instead of commonJS in their documentation.

Why did you decide to use commonJS exclusively? And would it also be possible to support the module syntax? Perhaps a section in the documentation would be enough to start with?

I would be happy about that!

**Comment by json-derulo** [comment]
Angular projects don't have `"type": "module"` in their `package.json`. For this reason, you need to use CommonJS syntax in your `eslint.config.js`. However you can rename the file to `eslint.config.mjs`, which allows usage of module syntax.

**Comment by rzschoch** [comment]
At the moment, I have stayed in the commonJS syntax because, unfortunately, I have not been able to configure the same functionality in ESModule syntax. But I would love to because many ESlint plugin projects deliberately omit the commonJS syntax in their documentation and recommend the ESModule syntax.

I would appreciate it if one could choose whether you prefer commonJS or ESModule syntax when creating a new Angular project. Depending on this, an `eslint.config.js` or `eslint.config.mjs` could then be created.

For the moment, however, a working example configuration with typescript-eslint and angular-eslint would be very helpful. Unfortunately, I couldn't manage that.

**Comment by JasonWeinzierl** [comment]
At the very least, it would be nice if the builder allowed `eslint.config.mjs` and `eslint.config.cjs` config files.  Right now it's hard-coded to only `eslint.config.js`, despite ESLint working fine with mjs/cjs too.

**Comment by csvn** [comment]
I also found this confusing, since [ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file) explicitly stated that `.js`, `.mjs` and `.cjs` should all work without extra config.

**Comment by hakimio** [comment]
It's extremely confusing that `angular-eslint` doesn't support `eslint.config.mjs` which seems to be the default format since [ESLint migration script](https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file) converts `json` config to `mjs`:
```
npx @eslint/migrate-config .eslintrc.json
```

**Comment by JamesHenry** [comment]
ESM syntax in configs, `eslint.config.js`, `eslint.config.cjs` and `eslint.config.mjs` are all supported as of https://github.com/angular-eslint/angular-eslint/releases/tag/v18.4.0
