### ISSUE TITLE
Rule proposal: Template syntax order

### ISSUE THREAD

**Issue by guilhermetod** [angular-eslint/angular-eslint#186]
Since I find that HTML is usually a bit confusing to read, I try to keep it organized when my tag items like variable declarations, directives, properties and events. Personally, I usually sort them by type with the following order:

Variable declaration
Structural directives
Directive declarations (with no input)
Unbinded properties (native propeties, inputs without square brackets)
Binded properties
Binded events

Then, in between the types, I sort them alpabetically

So just as example to show all types of syntaxes, an unsorted component like this:

```html
<app-list-item
  *ngFor="let item of items"
  list-item-on-sale
  #list-item
  color="red"
  [aria-title]="item.name"
  *ngIf="itemIsOnSale(item)"
  class="lits-item--collapsed"
  (click)="expandItem(item)"
  [disabled]="itemExceedsBudget(item)"
>
  {{ item.name }}
</app-list-item>

```

Would be organized like this:

```html
<app-list-item
  #list-item
  *ngFor="let item of items"
  *ngIf="itemIsOnSale(item)"
  list-item-on-sale
  class="lits-item--collapsed"
  color="red"
  [aria-title]="item.name"
  [disabled]="itemExceedsBudget(item)"
  (click)="expandItem(item)"
>
  {{ item.name }}
</app-list-item>
```

However, I currently have to keep checking and organizing manually everytime I change something. It would be nice to have a tool that would do this automatically and I don't see a tool like prettier doing this since this doesn't make much sense in plain HTML, so I feel like this would be a nice addition to this plugin.

The idea is similar to [typescript-eslint/member-ordering](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md), and so I think the configuration could be.

**Comment by SebastianPodgajny** [comment]
Proposal for this feature already exist https://github.com/angular-eslint/angular-eslint/issues/127

**Comment by JamesHenry** [comment]
As @SebastianPodgajny points out this is a duplicate, please check for existing issues before filing new ones.

**Comment by JamesHenry** [comment]
I would definitely accept a PR for this rule!
