### ISSUE TITLE
ng lint fails for new workspace created with Angular CLI and flat-config

### ISSUE THREAD

**Issue by schreibse** [angular-eslint/angular-eslint#1862]
**Description and reproduction of the issue**

- `ng new test-v18` (scss, no SSR)
- `cd test-v18/`
- `ng add @angular-eslint/schematics`
- `ng lint` fails
```sh
Linting "test-v18"...
An unhandled exception occurred: No ESLint configuration found in C:\Dev\playground\test-v18\src\app.
```

**But works with eslint v8**
Creating a new workspace, but adding  `"eslint": "8"` to dev-dependencies before running `ng add @angular-eslint/schematics` results in the following dependencies as well as .eslintrc.json
```sh
 "@angular-eslint/builder": "18.0.1",
 "@angular-eslint/eslint-plugin": "18.0.1",
 "@angular-eslint/eslint-plugin-template": "18.0.1",
 "@angular-eslint/schematics": "18.0.1",
 "@angular-eslint/template-parser": "18.0.1",
 "@typescript-eslint/eslint-plugin": "7.11.0",
 "@typescript-eslint/parser": "7.11.0",
 "eslint": "8.57.0",
```
`ng lint` runs without error:
```sh
Linting "test-v18"...
All files pass linting.
```

**Also fails for monorepo workspaces**
- `ng new test-18-mono --no-create-application` (scss, no SSR)
- `cd test-18-mono/`
- `ng g application my-app` (scss, no SSR)
- `ng add @angular-eslint/schematics`
- `ng lint` fails with different error
```sh
Linting "my-app"...
An unhandled exception occurred: ESLint configuration in --config is invalid:
        - Property "" is the wrong type (expected object but got `[{...}]
```

**Versions**
| package                            | version |
| ---------------------------------- | ------- |
| angular-eslint                 |18.0.1 |
| eslint                               |^9.3.0 |
| `node`                             | v20.13.0 |

```sh
Angular CLI: 18.0.2
Node: 20.13.0
Package Manager: npm 9.6.6
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1800.2 (cli-only)
@angular-devkit/core         18.0.2 (cli-only)
@angular-devkit/schematics   18.0.2 (cli-only)
@schematics/angular          18.0.2 (cli-only)
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by rainerhahnekamp** [comment]
@schreibse, I just tried it out on my machine and it works.

I have the same versions except for npm (10.2.3) and node (20.10).

Although it shouldn't make a difference, I've used these commands for the setup:

```shell
npm init @angular@latest test-v18
cd test-v18/
npx ng add @angular-eslint/schematics
npx ng lint
```

**Comment by schreibse** [comment]
thank you for trying it, it works on Linux and also Windows for a colleague but not on my machine )already tried to reinstall node)
