### ISSUE TITLE
Migration configuration plugins

### ISSUE THREAD

**Issue by gSarciotto** [angular-eslint/angular-eslint#187]
So I created a new project to test the migration and configure it to my liking.

In the eslint configuration that was generated from the default tslint configuration in the .ts override, the configuration is extending 3 plugins that I can't seem to find what they are:
```
"extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates",
      ],
```

I expected them to extends something like eslint:recommended but according to my testing they dont. What are the purpose of these plugins?

**Comment by JamesHenry** [comment]
I have added a section to the docs about this: https://github.com/angular-eslint/angular-eslint#premade-configs-provided-by-this-project

The migration is focused on being as smooth as possible, so the configs generated by the conversion schematics are about matching up with the Angular CLI's TSLint config as closely as possible.

Please let me know if you have any further questions
