### ISSUE TITLE
Unclear warning message for "no-empty-lifecycle-method"

### ISSUE THREAD

**Issue by vaindil** [angular-eslint/angular-eslint#188]
The error for the `no-empty-lifecycle-method` rule is currently "Declaring {{methodName}} lifecycle method in a class is not recommended", but this is confusing, as I thought the rule being flagged was actually `no-conflicting-lifecycle`. The warning message should be something like "{{methodName}} lifecycle method should not be empty".

**Comment by napei** [comment]
See #181 and it's associated PR #183 
Just waiting on it to be merged.

**Comment by vaindil** [comment]
Crap, I'm sorry, I thought I searched before opening this issue but I guess I didn't. Thank you!

**Comment by JamesHenry** [comment]
No worries, the fix is out in 0.8.0-beta.2
