### ISSUE TITLE
Updating to @angular-eslint/builder@npm:17.4.1 hangs linting if having .nx.json file

### ISSUE THREAD

**Issue by rbirkgit** [angular-eslint/angular-eslint#1889]
I have a repo using Lerna 8.1.3. I had @angular-eslint/builder@npm:17.4.0 and running eslint was working all great. The moment I updated to @angular-eslint/builder@npm:17.4.1, linting hangs.

It seems that when using 17.4.0, Nx 18.3.5 was used, but with 17.4.1 the Nx 18 dependency was removed and now using 19.3.0. I am guessing this is why linting with eslint started hanging. I don't understand why though.

I run the linting command. It pass the linting, output it and then hangs. The command line prompt never comes back. 

```
ng lint

Linting "lib"...

All files pass linting.
```

I downgrade to @angular-eslint/builder@npm:17.4.0 and everything works again. Not sure why version of Nx makes eslint work or not, but that the only other difference when updating to 17.4.1 when looking at the lock file.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `17.4.1` |
| `ESLint`                           | `8.57.0` |
| `node`                             | `20.13.0` |

```sh
Angular CLI: 17.3.8
Node: 20.13.0
Package Manager: yarn 4.0.1
OS: win32 x64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@schematics/angular             17.3.8
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by rbirkgit** [comment]
I tried the same thing in a repo without lerna, and there it works fine. Updating to 17.4.1 updates Nx from 18.x to 19.3.0 and linting still works.

For some reason in my lerna repo when doing the same thing, eslint hangs at the end. Neverf comes back to command prompt.

**Comment by rbirkgit** [comment]
If I add this to my lerna repo, linting works again. I.e. forcing @angular-eslint to use nx 18.3.5

```
  "resolutions": {
    "@nx/devkit@npm:^17.2.8 || ^18.0.0 || ^19.0.0": "^19.0.0",
    "nx@npm:^17.2.8 || ^18.0.0 || ^19.0.0": "^19.0.0"
  },
```

The moment I remove this and @angular-eslint is using Nx 19.3.0, eslint hangs every time using it. It outputs `All files pass linting.` and then nothing more happens.

**Comment by rbirkgit** [comment]
Added Lerna 8.1.3 to my working repo, and now eslint hangs there too.

**Comment by rbirkgit** [comment]
After more testing I found it's not related to Lerna, but having a `.nx.json` file. Even one with empty content like
```
{
}
```

The moment you have an `.nx.json` file, eslint hangs at the end. Removing the nx file, eslint works again.

**Comment by rbirkgit** [comment]
Hopefully someone has some ideas of workaround. We cannot update to latest versions until then.

**Comment by Akkowicz** [comment]
We don't use Lerna directly (it's used by resolve, a dependency of angular cli), we also don't have any .nx.json file laying around and the execution of eslint on Linux-based machines hangs just after linting is completed.

While running lint in our case, there are warnings about WASI being used:
```
(node:8358) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

We've tried disabling WASM completely with --noexpose_wasm, but then running lint will fail instantly somewhere in nx:

```
[error] Error: Failed to load native binding
    at Object.<anonymous> (/home/MY_NAME/Repos/REPO_NAME/node_modules/nx/src/native/native-bindings.js:359:11)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module._load (/home/MY_NAME/Repos/REPO_NAME/node_modules/nx/src/native/index.js:85:25)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/MY_NAME/Repos/REPO_NAME/node_modules/nx/src/native/index.js:91:21)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
```

For our case, the workaround was to add the following to package.json:
```
  "overrides": {
    "@nx/devkit": "18.3.5",
    "nx": "18.3.5"
  },
```

After doing this, warnings about WASI disappear and eslint exits successfully.

**Comment by Viserius** [comment]
Same problem here, also without .nx.json file. Same results as @Akkowicz, linting hangs indefinitely even though the output shows that it finished.

**Comment by mdodds93** [comment]
Also experiencing this problem, exactly as outlined above

**Comment by faltfe** [comment]
> Same problem here, also without .nx.json file. Same results as @Akkowicz, linting hangs indefinitely even though the output shows that it finished.

We have the same problem after upgrading to Angular 18.1.3. We don't use NX. The curiosity we have is that the linting fails only on certain systems and on other machines it is working just fine. At the moment we have no idea what causes this behaviour.

**Comment by mawiwolf** [comment]
We observe the same problem without NX. Builds are running on a build farm and started becoming flaky

**Comment by JoseRamonMartinez** [comment]
Same issue, there is any solution?

**Comment by JamesHenry** [comment]
Hi Folks, I appreciate the feedback here, I decided to remove Nx from the runtime of angular-eslint and just leave it to enhancing my development time concerns in the repo, so there is no direct dependency in the `@angular-eslint/builder` and `@angular-eslint/schematics` any longer as of `18.3.0`.

Please upgrade to the latest `18.3.0` and if you still experience problems, please open fresh issues with full updated context.

Thanks all!

**Comment by rbirkgit** [comment]
If you are still on Angular 17, I assume you have to use 17.x. Any chance we can get an updated 17.x version?

**Comment by Deitsch** [comment]
I have this same issue not using nx. After updating from Angular15 to Angular17 the linter started to hang. 
Locally (Mac) it works - Locally in Docker it hangs

**Comment by sagrawal31** [comment]
We are having the same issue. We are using all the latest deps of v17. `ng lint` works fine locally on Mac but not in GitLab's CI.

- Using `timbru31/node-chrome:hydrogen-slim` image in CI
- Multi repo build

![image](https://github.com/user-attachments/assets/5528e580-927f-45ef-b8cb-9a2192d43dad)

![image](https://github.com/user-attachments/assets/29b6066a-00fc-4b51-9a48-26fea641898f)

**Comment by sagrawal31** [comment]
I deleted the `node_modules` & `package-lock` files and did a fresh install, and this issue disappeared.

**Comment by JamesHenry** [comment]
I just cut `17.5.3` under the `previous` tag as a back port of the change to remove the runtime dependency on Nx utilities, so I trust that helps all folks who are stuck on Angular 17

**Comment by MatTerra** [comment]
Can confirm `17.5.3` on angular-eslint packages solves the issue of some systems hanging (github actions hanging for me)
