### ISSUE TITLE
angular-eslint cannot be used with typescript-eslint@^7

### ISSUE THREAD

**Issue by mshima** [angular-eslint/angular-eslint#1896]
`angular-eslint` has a hard dependency on `typescript-eslint@^8` making it incompatible with `typescript-eslint@^7`

https://github.com/angular-eslint/angular-eslint/blob/72e2d8df777c3d918d5be96af5821551b9049763/packages/angular-eslint/package.json#L23

This is intended to have eslint v9 support by default?

**Comment by JamesHenry** [comment]
It’s documented that angular-eslint is a new package that is used for ESLint v9 and typescript-eslint v8 and not older versions.

typescript-eslint does not support ESLint v9

**Comment by mshima** [comment]
It's working correctly with eslint@8 and typescript-eslint@7.
`typescript-eslint@8` is still in alpha state.

Using unsupported `typescript-eslint@7` looks less troubling than `typescript-eslint@8` alpha.
Is there any known issue in using `typescript-eslint@7`?
