### ISSUE TITLE
Incompatible rules with html files / @angular-eslint/template

### ISSUE THREAD

**Issue by ajcrites** [angular-eslint/angular-eslint#190]
Apologies if this is not the right place to report these issues, but I have discovered several rules that result in eslint crashing with errors that look like `TypeError: Cannot read property $PROPERTY of undefined` usually reported in the template file itself. This applies to inline template files and inline templates. The actual property trying to be read depends on the rule.

If need be, I can report these to the corresponding libraries themselves, but I thought I would start with the list here:

eslint:
* no-implicit-globals

[eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import):
* import/no-unused-modules
* import/first
* import/exports-last

[eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs):
* sonarjs/no-element-overwrite
* sonarjs/no-same-line-conditional
* sonarjs/prefer-object-literal

For anyone who may encounter these issues, you can just disable them for `html` files and things should work fine. They should still work for the corresponding `.ts` files themselves, even if they are components. Here is my example config:

```
module.exports = {          
  overrides: [  
    {         
      files: ['*.ts'],
      extends: ['plugin:@angular-eslint/recommended'],
    },           
    {             
      files: ['*.html'],
      extends: ['plugin:@angular-eslint/template/recommended'],
      rules: {               
        'no-implicit-globals': 'off',
        'import/no-unused-modules': 'off',
        'import/first': 'off',
        'import/exports-last': 'off',                                                                      
        'sonarjs/no-element-overwrite': 'off',
        'sonarjs/no-same-line-conditional': 'off',
        'sonarjs/prefer-object-literal': 'off',
      },
    },
    {
      files: ['*.component.ts'],
      extends: ['plugin:@angular-eslint/template/process-inline-templates'],
    },
  ],
```

**Comment by JamesHenry** [comment]
There must be some config missing from your example above. The only way that those rules could be applying to all files is if they have been configured to do so.

I have updated the documentation on ESLint config, and added an extra section which I think applies here: 

https://github.com/angular-eslint/angular-eslint#seriously-move-mostly-all-configuration-into-overrides

There should not really be any configuration at the top level, it should (mostly) all be within overrides when it comes to Angular + ESLint.

Thanks!
