### ISSUE TITLE
[prefer-standalone] New option: ignoreAbstract

### ISSUE THREAD

**Issue by ersimont** [angular-eslint/angular-eslint#1910]
**Description and reproduction of the issue**

It would be great to have an option to turn off the `prefer-standalone` rule for abstract classes.

I sometimes create superclasses for my Angular components. In these cases they must have an Angular decorator, like below, just to trigger all the right Angular magic during compilation. Any attributes set in the decorator are meaningless - they are replaced with what decorates the subclasses. So I leave them empty, as below, but that triggers the `prefer-standalone` rule.

```TS
// eslint-disable-next-line @angular-eslint/prefer-standalone
@Directive()
abstract class MyComponentSuperclass {
  // some interesting stuff shared across subclasses
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `angular-eslint`    | `18.1.0` |
| `typescript-eslint`        | `8.0.0-alpha.38` |
| `ESLint`                           | `^9.6.0` |
| `node`                             | `20.9.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 18.0.6
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 18.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cdk                    18.0.6
@angular/cli                    18.0.6
@angular/fire                   18.0.1
@angular/material               18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by P4** [comment]
Might be a similar case to https://github.com/angular-eslint/angular-eslint/issues/353, where empty directive decorator needs special treatment?
