### ISSUE TITLE
Nx shouldn't be a dependency for schematics and builder

### ISSUE THREAD

**Issue by Iworb** [angular-eslint/angular-eslint#1919]
**Description and reproduction of the issue**

I don't have nx in my projects, but installing this plugin makes nx post-install script run and creates nx-related cache and files. After that, those files may accidentally be added to the git by someone from the team.

We need a workaround that allows non-nx users to install and use this package without the inconvenience that comes from the dependencies. 

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `17.3.0` |
| `@angular-eslint/schematics`          | `17.3.0` |
| `ESLint`                           | `8.57.0` |
| `node`                             | `20.11.0` |

```sh
Angular CLI: 17.3.8
Node: 20.11.0
Package Manager: pnpm 9.4.0
OS: win32 x64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@angular/material               17.3.10
@schematics/angular             17.3.8
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by migueltercero** [comment]
same here.

**Comment by MarkusGnigler** [comment]
I have the same problem, but a bit worse. 
Npm has a known bug with platform specific packages [@angular/cli Issue](https://github.com/angular/angular-cli/issues/27367)
With this issue our angular project build in a docker container runs forever without any message. 
the quick but dirty solution is to just copy the package.json without the package-lock.json to the container image.

Please remove the dependency. We are not using NX in our project. 
Thanks in advance

**Comment by imirkin** [comment]
There's also the unfortunate situation where `nx` tries to execute a binary in its post-install script. When this is running on a `/tmp` mounted with `noexec`, it results in a very odd failure. There are various ways to work around this, but yet another reason to remove `nx` from the dependencies, esp when it's entirely unnecessary.

**Comment by kirillgroshkov** [comment]
Same

**Comment by imirkin** [comment]
Is there some strong reason why the builder was implemented with `convertNxExecutor`? Would a change be considered to redo it without making use of the various nx facilities? I'm happy to give it a shot, but I also don't want to waste my time if nx is viewed as a hard dependency.

**Comment by karptonite** [comment]
I'm having a similar/related issue when using Angular-eslint on a Mac OS (Sonoma) system. We also  When I try to run the eslint (with the Angular plugin) in our pre-commit hook, I get the following error message:
`“19.5.2-nx.darwin-arm64.node” can’t be opened because Apple cannot check it for malicious software.` 
Then in the Security section of preferences, I see `“19.5.2-nx.darwin-arm64.node” was blocked from use because it is not from an identified developer`. I can click Allow Anyway, but the error just comes back next time I try to run the linter.

**Comment by JamesHenry** [comment]
Hi Folks, I appreciate the feedback here, I decided to remove Nx from the runtime of angular-eslint and just leave it to enhancing my development time concerns in the repo, so there is no direct dependency in the `@angular-eslint/builder` and `@angular-eslint/schematics` any longer as of `18.3.0`, and `nx` and `@nx/devkit` will only be pulled into your workspaces if you choose to use it as your own dev tool (which I naturally highly recommend 😄)

Thanks all!

**Comment by MarkusGnigler** [comment]
Many thanks!
highly appreciate the fast answer and change 👍
