### ISSUE TITLE
 No matching version found for @nrwl/devkit@19.5.0.

### ISSUE THREAD

**Issue by JoseStadler** [angular-eslint/angular-eslint#1920]
**Description and reproduction of the issue**
ng add @angular-eslint/schematics and also previously installed package is not working on npm install for the project as this error is coming up:
 No matching version found for @nrwl/devkit@19.5.0.

To try it out I just created a new angular project with ng new and then executing ng add @angular-eslint/schematics, the example of the response is: 

ng add @angular-eslint/schematics
✔ Determining Package Manager
  › Using package manager: npm
✔ Searching for compatible package version
  › Found compatible package version: @angular-eslint/schematics@18.1.0.
✔ Loading package information from registry
✔ Confirming installation
✖ Unable to install package

npm error code ETARGET
npm error notarget No matching version found for @nrwl/devkit@19.5.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `18.1.0 and 18.0.1 (other project)` |
| `ESLint`                           | `Latest and 9.4.0`|
| `node`                             | `20.12.1 and 20.15.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.1.1
Node: 20.15.1
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.5.3
zone.js                         0.14.8

```

- [x ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @JoseStadler this error should be impossible as of `18.3.0`, please try upgrading to the latest and trying again. Many thanks!
