### ISSUE TITLE
Feature Request: Integrate @html-eslint into @angular-eslint/template-parser

### ISSUE THREAD

**Issue by wizardnet972** [angular-eslint/angular-eslint#1927]
## Summary
Integrate [@html-eslint](https://html-eslint.org/) into the `@angular-eslint/template-parser` to leverage additional linting rules that enhance Accessibility, SEO, and other aspects of HTML code quality.

## Motivation
Currently, `@angular-eslint/template-parser` provides a set of linting rules specific to Angular templates. By integrating @html-eslint, we can further improve the quality of Angular projects by enforcing a broader range of best practices and standards, particularly in the areas of Accessibility and SEO.

## Benefits
- **Enhanced Accessibility:** @html-eslint includes rules that ensure HTML content is accessible to all users, including those with disabilities.
- **Improved SEO:** The integration would help ensure that Angular applications adhere to best practices for search engine optimization.
- **Consistency:** Developers can benefit from a consistent set of rules across HTML and Angular templates.
- **Code Quality:** The additional linting rules will help maintain high code quality and reduce bugs related to HTML structure and attributes.

## References
- [@html-eslint Documentation](https://html-eslint.org/)
- [@angular-eslint/template-parser Documentation](https://github.com/angular-eslint/angular-eslint)

Integrating @html-eslint into `@angular-eslint/template-parser` will significantly enhance the linting capabilities of Angular projects, ensuring they adhere to best practices for Accessibility, SEO, and overall code quality.

**Comment by CarlosBayarri** [comment]
I want this feature. I think this is important.
