### ISSUE TITLE
Angular CLI: 18.1.2 + Node: 18.19.1 + Package Manager: npm 10.2.4

### ISSUE THREAD

**Issue by dana1632000** [angular-eslint/angular-eslint#1947]
i changed to angular 18, and after config all necessary things about installing the versions of cli & node, all were good, but i tried to make a new application but it takes to much time , And while i write this the cmd still at ( \ Installing packages (npm)... ) and didn't done ? what should i do ?

**Comment by JamesHenry** [comment]
Please retry with the latest `18.3.0` that was released today as I've made some changes recently.

If you still experience problems please open a fresh issue and respect the issue template and provide the information it requests.
