### ISSUE TITLE
Eslint9: Issue with ng lint - eslint.config.js file is not recognized in often times, but works with typescipt-eslint's npx eslint command

### ISSUE THREAD

**Issue by johnson-joney** [angular-eslint/angular-eslint#1969]
When trying to execute lint using ng lint command, eslint configuration file eslint.config.js file is not recognized often times, but it is recognized by typescript-eslint's npx eslint command and works fine. Below the error caused by ng lint command,

> [error] Error: No ESLint configuration found in E:\research\angular\certification\harry-potter-movies\src\app.
>     at CascadingConfigArrayFactory._finalizeConfigArray (E:\research\angular\certification\harry-potter-movies\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:4026:19)
>     at CascadingConfigArrayFactory.getConfigArrayForFile (E:\research\angular\certification\harry-potter-movies\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3817:21)
>     at FileEnumerator._iterateFilesRecursive (E:\research\angular\certification\harry-potter-movies\node_modules\eslint\lib\cli-engine\file-enumerator.js:475:52)
>     at _iterateFilesRecursive.next (<anonymous>)
>     at FileEnumerator._iterateFilesRecursive (E:\research\angular\certification\harry-potter-movies\node_modules\eslint\lib\cli-engine\file-enumerator.js:497:33)
>     at _iterateFilesRecursive.next (<anonymous>)
>     at FileEnumerator.iterateFiles (E:\research\angular\certification\harry-potter-movies\node_modules\eslint\lib\cli-engine\file-enumerator.js:299:49)
>     at iterateFiles.next (<anonymous>)
>     at CLIEngine.executeOnFiles (E:\research\angular\certification\harry-potter-movies\node_modules\eslint\lib\cli-engine\cli-engine.js:808:48)
>     at LegacyESLint.lintFiles (E:\research\angular\certification\harry-potter-movies\node_modules\eslint\lib\eslint\legacy-eslint.js:593:23)

Version I have installed is, angular-eslint@18.2.0

**Comment by johnson-joney** [comment]
Why angular lint is looking for old config file .eslintrc.js instead eslint.config.js?

**Comment by hakimio** [comment]
If anyone else stumbles upon this issue trying to figure out why they are getting `No ESLint configuration found in src/app` error: the most likely reason is that you are using unsupported `eslint.config.mjs` ESLint config variant. `mjs`, `cjs` and `ts` configs are not supported by `angular-eslint`, only the `js` one is: `eslint.config.js`.
Related issue: #1859

**Comment by JamesHenry** [comment]
`eslint.config.js`, `eslint.config.cjs` and `eslint.config.mjs` are all supported as of https://github.com/angular-eslint/angular-eslint/releases/tag/v18.4.0
