### ISSUE TITLE
Docs for individual rules

### ISSUE THREAD

**Issue by gSarciotto** [angular-eslint/angular-eslint#197]
Hello everyone,

is there a plan for adding docs to individual rules? Something similar to what [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules) has. 

If yes, how can I help?

**Comment by JamesHenry** [comment]
This would be a very welcome contribution! Feel free to take inspiration and code from typescript-eslint as the starting point

**Comment by gSarciotto** [comment]
@JamesHenry  Fantastic! I will try to do something going this week.

Where should I put the docs? I thought something like {{plugin}}/docs/rules

And how should we proceed, I create an issue for each rule or just the PR?

**Comment by JamesHenry** [comment]
Sounds good on the location, no need for extra issues, you can just start with a draft PR.

Maybe do 1 PR per plugin for now

**Comment by sam-s4s** [comment]
Am just moving from tslint to eslint for angular, and am finding it very difficult to do with no documentation on the rules lol. I guess for now you just have to go and look at the rules' source code to figure out how it works.

Looks like there's "only" 32 rules.

Perhaps if we all work together we can get the docs done?

**Comment by jfgreffier** [comment]
It seems that the strategy is to auto-generate docs from rules, although there were no progress since May https://github.com/angular-eslint/angular-eslint/pull/507#issuecomment-848048082

**Comment by JamesHenry** [comment]
Thanks for your patience on this everyone - I have just merged the first version of the automated docs generation logic. We will continue to improve on it from here, but for now it addresses this issue.

Thanks again!

**Comment by jfgreffier** [comment]
That's great ! Thank you @JamesHenry
