### ISSUE TITLE
Rules no longer work after plugin:@angular-eslint/template/recommended has been activated.

### ISSUE THREAD

**Issue by SerkanSipahi** [angular-eslint/angular-eslint#199]
First of all many thanks for the work :smiling_face_with_three_hearts: :smiling_face_with_three_hearts: :smiling_face_with_three_hearts:

I've been using angular-eslint for a while but I never managed to get the `@angular-eslint/template` together with `@angular-eslint` to work. I was able to reduce the `issue/bug` so that I know when the template linting works or not. 

As soon as the `plugin:@angular-eslint/template/recommended` is activated in extends, the following rule `@angular-eslint/component-selector` should still work, but it does not. It seems that the `angular/template` plugin disables the rules for `@angular-eslint`.  

I do not get an error message either. As soon as the following `plugin:@angular-eslint/template/recommended` is removed, everything works fine and the linting error for `@angular-eslint/component-selector` works again.

If you run eslint in --debug mode there is nothing special to see. Everything seems to be ok. So no errors.

What am I doing wrong? :sassy_man:

.esllintrc
```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "project": "tsconfig*.json"
  },
  "plugins": [
    "@angular-eslint",
    "@angular-eslint/template"
  ],
  "extends": [
    "plugin:@angular-eslint/recommended",
    "plugin:@angular-eslint/template/recommended"
  ],
  "rules": {
    "@angular-eslint/component-selector": [
      "error", { "type": "element", "prefix": "avo", "style": "kebab-case" }
    ]
  }
}
```
package.json
```json
{
  "devDependencies": {
    "@angular-eslint/eslint-plugin": "0.8.0-beta.2",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.2",
    "@angular-eslint/template-parser": "0.8.0-beta.2",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "eslint": "7.6.0",
    "typescript": "4.0.5"
  }
}
```

**Comment by SerkanSipahi** [comment]
I used the `premade configs` as described on the readme page. I assume there is no need the "blocks of configuration" (overrides) for this! right?

**Comment by JamesHenry** [comment]
> I used the premade configs as described on the readme page. Therefore I assume there is no need the "blocks of configuration" (overrides) for this! right?

No, that is not right, as explained in the README. I have just enhanced it even further today with more information, but the README has always said how it is critical to keep source code and template rules/plugins/parsers separated by using `overrides`, and to _not_ use the root of your config object to configure things.

https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration

https://github.com/angular-eslint/angular-eslint#seriously-move-mostly-all-configuration-into-overrides

https://github.com/angular-eslint/angular-eslint#going-fully-manual-not-recommended

Please take a look at all those sections and let me know if you have any more issues.

**Comment by SerkanSipahi** [comment]
Thank you @JamesHenry .
