### ISSUE TITLE
Updating to @angular-eslint/builder@npm:17.4.1 hangs linting if having .nx.json file

### ISSUE THREAD

**Issue by rbirkgit** [angular-eslint/angular-eslint#2003]
We cannot use @angular-eslint 17.4.1 or higher as it hangs. It was fixed in 18.3.0. See #1889. We have no solution for those still on Angular 17. Unfortunately we can not yet update to Angular 18 (3rd party dependency we are waiting for). 

Can we get a fix for 17.x version please?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `17.4.1` |
| `ESLint`                           | `8.57.0` |
| `node`                             | `20.13.0` |

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by ccondrup** [comment]
Just a heads up that some nx issues are fixed by including optional npm packages, aka:
```bash
npm install --include=optional
# was: npm install --omit=optional
```

With that change, I could run both of these with Angular v17-lts (17.3.12 atm, node 20.16.0, eslint 8.57.0):
- @angular-eslint/* 18.3.0
- @angular-eslint/* 17.5.2

Ref [[1]](https://stackoverflow.com/questions/77989039/error-cannot-find-module-nx-nx-linux-x64-gnu), [[2]](https://github.com/nrwl/nx/issues/15452)

**Comment by JamesHenry** [comment]
I just cut 17.5.3 under the `previous` tag, this no longer has the runtime dependency on Nx utilities, so if you are not using Nx directly then you will not have it in your workspace.

I don't fully understand the title of this issue (A) `.nx.json` is not a valid file related to Nx (`nx.json` is) (B) if you have `nx.json` then that means you _are_ using Nx outside of the context of angular-eslint.

Nevertheless, I trust the `17.5.3` release will resolve this for you.

**Comment by rbirkgit** [comment]
Thanks for this!! Much appreciated.

I updated subject. A mistake, I meant `nx.json`. I have one because of using `lerna`. I also created an empty angular-cli created project. The moment I added an `nx.json` file linting started hanging. Removing the file, linting worked. Both in my empty project and lerna project.

**Comment by JamesHenry** [comment]
@rbirkgit Ah I see, thanks, glad it worked for you!
