### ISSUE TITLE
Error when migrating to eslint

### ISSUE THREAD

**Issue by madoar** [angular-eslint/angular-eslint#201]
## Problem Description

I'm currently trying to migrate the library [angular-archwizard](https://github.com/madoar/angular-archwizard) from tslint to eslint.

When following the first step of the migration guide:

> ### Step 1 - Add relevant dependencies
> 
> The first step is to run the schematic to add @angular-eslint to your project:
> 
> ```
> ng add @angular-eslint/schematics
> ```
> 
> This will handle installing the latest version of all the relevant packages for you and adding them to the devDependencies of your package.json.

I see the following error message:

```bash
$ ng add @angular-eslint/schematics
Installing packages for tooling via npm.
Installed packages for tooling via npm.

Error: Angular CLI v10.1.0 and later (and no `tsconfig.base.json`) is required in order to run this schematic. Please update your workspace and try again.
```

Both my local setup and `angular-archwizard` use Angular 11.
In addition `angular-archwizard` contains a `tsconfig.base.json` file.

## Expected Result

The first migration step succeeds

## Reproduction Steps

1.  clone `angular-archwizard` (run: `git clone git@github.com:madoar/angular-archwizard.git`)
2.  install all necessary dependencies (run: `npm i`)
3.  execute first migration step (run: `ng add @angular-eslint/schematics`)

## Local Setup

My local setup looks like the following:

```bash
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 12.12.0
OS: linux x64

Angular: 11.0.2
... cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by alexanderhanssen** [comment]
I'm getting the same error.

**Comment by LeoLfL** [comment]
the same for me

**Comment by nzacca** [comment]
This may be of some help: https://github.com/angular-eslint/angular-eslint/issues/195

cc: @alexanderhanssen @LeoLfL

**Comment by JamesHenry** [comment]
I have added extra context around this issue high up in the docs:

https://github.com/angular-eslint/angular-eslint#why-angular-1010

It's a shame that this churn in config type came about, but using `ng update` when updating Angular versions is the way to avoid such issues.

**Comment by madoar** [comment]
Hi @JamesHenry, thank you for clarifying. This is interesting because I updated the Angular version of `angular-archwizard` with `ng update` for at least the last 4 Angular versions. I think when updating to Angular 10 I was kind of surprised because I read about the the change from `tsconfig.json` to `tsconfig.base.json` on angular.io, but because I could not see the renaming being done after `ng update`, I did this renaming myself if I remember correctly.

It may also be important to note that I created the `angular-archwizard` project when Angular 2 was a thing. Therefore the project structure may not be 100% conform to what a newly created Angular 10+ project looks like. This also forced me to "repair" the project multiple times after upgrading Angular via `ng update` to a newer version. By repairing I mean that I created a new Angular project with the current Angular version and search for differences in the configuration files which I then apply on the `angular-archwizard` project.

Summarized I don't think that I can go back to a state from where I could get a Angular 11 project that does not contain a `tsconfig.base.json` file. In your changes to the README file you mentioned that the necessary changes to the `tsconfig` can also be done by hand. Can you walk me through these by chance?

**Comment by JamesHenry** [comment]
@madoar in situations like that I would recommend generating a new workspace and then either porting the differences into your project, or applying your source code to the new workspace and using it from now on.

Again this is not something that relates to me or this library in any way, so I won’t be able to provide detailed advice, but the above “tip” is always the ultimate fallback option to get back on track with the latest

**Comment by itayperry** [comment]
I've started a new project with Angular 11 and the `tsconfig.base.json` is there, I wrote about it here: https://github.com/angular-eslint/angular-eslint/issues/195#issuecomment-830820754
