### ISSUE TITLE
Add changelog.md

### ISSUE THREAD

**Issue by splincode** [angular-eslint/angular-eslint#204]

**Comment by JamesHenry** [comment]
This will come once we hit 1.0 soon

**Comment by red2678** [comment]
1.0 is out yay! Is there breaking changes as the version bump suggests? Why no changelog or at a minimum some release notes?

**Comment by JamesHenry** [comment]
v1.1.0 is now out and as previously stated, being the first release post v1 it has a changelog and release notes.

FYI rhe release notes for v1 itself were there in a simplified form and called out the breaking change around stylistic rules.
