### ISSUE TITLE
Add support of --no-config-lookup in Builder

### ISSUE THREAD

**Issue by hennihaus** [angular-eslint/angular-eslint#2054]
Hello everyone,

It would be great to introduce a --no-config-lookup flag, which could eventually replace the --no-eslintrc flag. In our project, we use this flag to prevent the recursive lookup of additional configuration files, which could override our root-level project configuration.

For more details, refer to the migration guide:
https://eslint.org/docs/latest/use/configure/migration-guide#cli-flag-changes

And the CLI documentation:
https://eslint.org/docs/latest/use/command-line-interface#--no-eslintrc

**Comment by JamesHenry** [comment]
This was confusing to try and trace through the ESLint code. It is not an option on the ESLint class itself (which the builder is based on). I added support for it in https://github.com/angular-eslint/angular-eslint/pull/2045

**Comment by JamesHenry** [comment]
Released in https://github.com/angular-eslint/angular-eslint/releases/tag/v18.4.0
