### ISSUE TITLE
ghost dependency on @typescript-eslint/types

### ISSUE THREAD

**Issue by Tezra** [angular-eslint/angular-eslint#2059]
[@angular-eslint/eslint-plugin-template](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/package.json) -> [utils/get-nearest-node-from.js](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/src/utils/get-nearest-node-from.ts) has a ghost dependency on @typescript-eslint/types (line 6) which is not listed in the package.json.

Output from trying to run lint with Yarn
```console
[error] Error: @angular-eslint/eslint-plugin-template tried to access @typescript-eslint/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @typescript-eslint/types
Required by: @angular-eslint/eslint-plugin-template

Require stack:
- /workspaces/.../@angular-eslint-eslint-plugin-template-virtual-56a1737fa1/0/cache/@angular-eslint-eslint-plugin-template-npm-18.3.1-c5732add6c-43cbdbb42c.zip/node_modules/@angular-eslint/eslint-plugin-template/dist/utils/get-nearest-node-from.js
- /workspaces/.../@angular-eslint-eslint-plugin-template-virtual-56a1737fa1/0/cache/@angular-eslint-eslint-plugin-template-npm-18.3.1-c5732add6c-43cbdbb42c.zip/node_modules/@angular-eslint/eslint-plugin-template/dist/utils/is-hidden-from-screen-reader.js
- /workspaces/.../@angular-eslint-eslint-plugin-template-virtual-56a1737fa1/0/cache/@angular-eslint-eslint-plugin-template-npm-18.3.1-c5732add6c-43cbdbb42c.zip/node_modules/@angular-eslint/eslint-plugin-template/dist/rules/click-events-have-key-events.js
- /workspaces/.../@angular-eslint-eslint-plugin-template-virtual-56a1737fa1/0/cache/@angular-eslint-eslint-plugin-template-npm-18.3.1-c5732add6c-43cbdbb42c.zip/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js
- /workspaces/.../angular-eslint-virtual-209954b993/0/cache/angular-eslint-npm-18.3.1-37c6166d22-7033120cc4.zip/node_modules/angular-eslint/dist/index.js
- /workspaces/.../eslint.config.js
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `18.3.1` |

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by blazkovicz** [comment]
Have same issue. Yarn pnp shows it clearly.

**Comment by JamesHenry** [comment]
I added the peerDependency in https://github.com/angular-eslint/angular-eslint/pull/2046

**Comment by JamesHenry** [comment]
Released in https://github.com/angular-eslint/angular-eslint/releases/tag/v18.4.0
