### ISSUE TITLE
[Migration Guide Support] angular-eslint migration guidance on major Angular version upgrades 

### ISSUE THREAD

**Issue by tadpole2077** [angular-eslint/angular-eslint#2077]
Suggest adding / extending documentation section on migration from prior angular-eslint versions.

For example on project migration from Angular V15 to V16 ,  the angular upgrade will fail (ng update @angular/core@16 @angular/cli@16)  due to existing dependences within angular-eslint   (@angular-eslint/schematics dependency to @angular/cli)

Typical option is then to force upgrade of Angular CLI,  then manual update packages references related to @angular-eslint to V16, adjust config settings (or swap to flat file structure).   But this potential opens futureproof issues, for example if @angular-eslint package names change or additional packages are added.

It would be helpful to offer some quick guidance to users on optimal update/migration plans for angular-eslint packages - key changes between major releases (angular VX to VX+1) that require manual steps (such as config changes), or potential package changes.  

I myself made the assumption that @angular-eslint/schematics would have had some update facility to update all packages and relevant dependencies related to eslint and related plug-ins Or possible warn of plugins that requires manual decisioning and updates.

**Comment by JamesHenry** [comment]
The command to run is always reiterated in the release notes, along with information about the breaking changes in the release:

E.g. https://github.com/angular-eslint/angular-eslint/releases/tag/v18.0.0

Are you saying running the update with the packages listed together does not work?

**Comment by tadpole2077** [comment]
Problem is that  { ng update @angular/core@16 @angular/cli@16 @angular-eslint/schematics } 
Targets project migration to Angular V16, but unfortunately attempts to updates schematics to latest package and fails.

I tried specific @angular-eslint/schematics@16 target but to no avail, reverting to manual package updates and config changes.

**Comment by JamesHenry** [comment]
Yes, it's definitely expected that you would have to provide `@16` or `@{THE SAME VERSION}` on all 3, you cannot have `@angular-eslint/schematics` use a different major version (e.g. here the implied version of that is `@latest`) when compared to the Angular packages.

This relationship is documented right at the top of the README: https://github.com/angular-eslint/angular-eslint?tab=readme-ov-file#supported-angular-cli-versions and further links to: https://github.com/angular-eslint/angular-eslint/blob/c0e9b9168944d57c3c7b97560deda856d84e73ac/docs/ANGULAR_VERSION_SUPPORT.md

As for specific issues with updating to v16 I'm afraid that's a bit too far into the past for it to be scalable for me to support in my very limited spare time.

I'm glad you've been able to find a manual workaround to whatever issue you faced. The fact that this doesn't/hasn't come up more suggests to me that what we have in place is pretty well understood, but I will keep an eye out of for any future reports.

Many thanks!
