### ISSUE TITLE
feature request: new role "prefer-inject-over-constructor-injection

### ISSUE THREAD

**Issue by mikelgo** [angular-eslint/angular-eslint#2095]
I would like to propose a new rule to prefer using `inject` over constructor based injection.

Some reasons behind this feature request:
- constructor based injection does not align with TypeScript standards afaik.
- afaik the Angular team itself will soon promote to use inject in favor of constructor-injection

**Comment by JamesHenry** [comment]
I raised this exact topic with the team last year and at that time Alex was not willing to say that it was the team's recommendation.

As of now there is still no recommendation in this area: https://github.com/angular/angular/discussions/58412#discussioncomment-11093822

We can definitely adjust once there is but I'll close for now
