### ISSUE TITLE
unhandled exception occurred: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')

### ISSUE THREAD

**Issue by frosales14** [angular-eslint/angular-eslint#2097]
Creating a new Angular project with ng new and add angular-eslint with the command ng add @angular-eslint/schematics
after that i try to run the ng lint command and i get the following error 

An unhandled exception occurred: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')

i'm using angular 18 as base for the project and angular eslint 18.4.0 versions

**Comment by bluehexagons** [comment]
Looks like it's an issue in typescript-eslint: https://github.com/typescript-eslint/typescript-eslint/issues/10338

I found this issue searching for the error message and thought I'd pass the root cause along.

**Comment by JamesHenry** [comment]
Thanks folks yep it was in typescript-eslint, you can bump to `8.15.0` of it to get the fix

**Comment by davideprevosto** [comment]
I am using the following packages versions, but unfortunately I am still getting the error:

```
An unhandled exception occurred: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /.src/app/app.resolvers.ts
```

```
"angular-eslint": "18.4.1",
"eslint": "^9.15.0",
"eslint-config-prettier": "^9.1.0",
"eslint-plugin-prettier": "^5.2.1",
"typescript": "5.6.3",
"typescript-eslint": "8.15.0"
```
