### ISSUE TITLE
[Naming Question]: Would `eslint-angular` be better than `angular-eslint`

### ISSUE THREAD

**Issue by JounQin** [angular-eslint/angular-eslint#21]
It would be more consistent with `tslint-angular` or any other `ESLint` related plugins.

And the GitHub/npm name is still available.

**Comment by mgechev** [comment]
Looking at npm the suggestion makes sense to me. Most of the plugins are with `eslint-` prefix. @JamesHenry, since you've been involved in this ecosystem for a while now would you chip in?

**Comment by JamesHenry** [comment]
It’s not an apples to apples comparison.

‘eslint-‘ has a special meaning for resolving plugins, and we do indeed leverage that here.

The name of the organisation/monorepo is orthogonal to that. “angular-eslint” is not the name of a package here, you don’t install that ever.

@angular-eslint as a namespace under which our packages live is much easier to scan for in an an eslint config file IMO and it matches the @typescript-eslint namespace upon which this project builds.

My opinion would strongly be for _not_ changing it.

**Comment by JamesHenry** [comment]
(I’m away from my computer otherwise I would have provided more config and code examples to illustrate my point but hopefully it’s clear, happy to expand further later)
