### ISSUE TITLE
Missing peer dependency of "@typescript-eslint/types" @ "^7.11.0 || ^8.0.0"

### ISSUE THREAD

**Issue by dangrussell** [angular-eslint/angular-eslint#2123]
**Description and reproduction of the issue**
Command:
ng update @angular-eslint/schematics

Warning:
Package "@angular-eslint/eslint-plugin-template" has a missing peer dependency of "@typescript-eslint/types" @ "^7.11.0 || ^8.0.0".

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `18.4.1` |
| `@angular-eslint/template-parser`         | `18.4.1` |
| `@typescript-eslint/parser`               | `7.18.0` |
| `ESLint`                                  | `8.57.1` |
| `node`                                    | `20.17.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.2.12
Node: 20.17.0
Package Manager: yarn 1.22.22
OS: win32 x64

Angular: 18.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cdk                    18.2.13
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
I don't believe this happens on the newly released v19. Additionally, this is only a warning, so if things are working for you, it's all good.
