### ISSUE TITLE
templateRecommended, templateAccessibility configs are not defined

### ISSUE THREAD

**Issue by babajonni** [angular-eslint/angular-eslint#2124]
When installing angular-eslint with the: ``` ng add @angular-eslint/schematics ``` it creates a eslint.config.js file. 

The default config which uses the templateRecommended, templateAccessibility  properties is not working since those are not defined. The config object in the library only has the properties: ```all``` and ```recommended```
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `18.4.1` |
| `@typescript-eslint/parser`        | `X.Y.Z` |
| `ESLint`                           | `9.15.0` |
| `node`                             | `20.11.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


```

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
You'll have to provide more information about your setup, we have e2e coverage for this and obviously if something so fundamental were always broken, we would have a lot more issues/+1s on this issue. Please help me to help you

**Comment by JamesHenry** [comment]
Please feel free to reopen if you can provide some information or a reproduction
