### ISSUE TITLE
Refreshed design for angular-eslint logo to be in line with new Angular brand

### ISSUE THREAD

**Issue by jjmhalew** [angular-eslint/angular-eslint#2129]
Since Angular 17 was announced a while ago, Angular has a new brand. They encourage the community to adapt their logo to their branding and they provided guidelines, as can be seen here: https://angular.dev/press-kit.

I thought I could help with a new logo according to Angular's new brand guidelines. I made some variations, but picked my favorite ones which I think fit best. 

I combined the shape of the new Angular logo and the Eslint logo. The Angular logo is adjusted to be aligned and within the bounds of the inner hexagon of the Eslint logo, while also maintaining the same type of border rounding as the Eslint logo. Also the eslint inner hexagon has a different lighter color, which is why I also applied that to the 2nd and 3rd variation.

I hope this helps :)

<img src="https://github.com/user-attachments/assets/2cb39b3a-7a08-4801-b15d-aa3fffb6918f" width="250">  
<img src="https://github.com/user-attachments/assets/241f1546-2555-43b3-93a7-0932a49648d6" width="250">  
<img src="https://github.com/user-attachments/assets/27850175-79ef-47ce-bae9-57795a96e455" width="250">

**Comment by JamesHenry** [comment]
Thank you @jjmhalew but we will be going with @muuvmuuv's design again:

https://github.com/angular-eslint/angular-eslint/issues/111#issuecomment-2247236083

@muuvmuuv please could you provide a version without the white background?

**Comment by JamesHenry** [comment]
Everything is updated with the v19 release, thanks again @muuvmuuv
