### ISSUE TITLE
ng lint with eslint Unknown option: '--files'

### ISSUE THREAD

**Issue by koenig-dominik** [angular-eslint/angular-eslint#213]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The --files option of ng lint is not working, this should be added to be consistent with the old tslint
(The Angular CLI Team already rejected the issue from their side, I incidentally thought this has to be implemented there: https://github.com/angular/angular-cli/issues/19563)

## 🔬 Minimal Reproduction

1. create a new project with `ng new foo`
2. install the recommended eslint linter with `ng add @angular-eslint/schematics` and `ng g @angular-eslint/schematics:convert-tslint-to-eslint foo`
3. run the linter with the --files option `ng lint --files="src/app/app.module.ts" `

## 🔥 Exception or Error
<pre><code>Unknown option: '--files'
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 11.0.3
Node: 10.22.1
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by JamesHenry** [comment]
The intention of this project is not to provide a 1:1 mapping to all options found in the TSLint.

You can achieve the behaviour you want using the `lintFilePatterns` option in the ESLint builder, which ultimately is passing the array of files or globs to ESLint's Node API to resolve (this parameter here behind the scenes: https://eslint.org/docs/developer-guide/nodejs-api#parameters-1)

**Comment by xaviergxf** [comment]
Hi,

  What is the solution here? On the docs i see the option --files. How to run ng lint only on a folder?

Thanks

**Comment by bbarry** [comment]
```sh
ng lint --lint-file-patterns ./src/app/
```
