### ISSUE TITLE
[prefer-signals] rule is not exported

### ISSUE THREAD

**Issue by quentinderoubaix** [angular-eslint/angular-eslint#2149]
**Description and reproduction of the issue**

The new rule `@angular-eslint/prefer-signals` added in 19.0.0 cannot be used as it is not exported by the config / index file of package `eslint-plugin`.  
Missing export is found [in this index.ts file](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/src/index.ts).

**Comment by Frotty** [comment]
@JamesHenry Thanks for the quick fix. For some reason, the CI build is taking exceptionally long, is this expected? https://github.com/angular-eslint/angular-eslint/actions/runs/12166615891/job/33933260816
