### ISSUE TITLE
[no-input-rename] can not be turned off

### ISSUE THREAD

**Issue by e-oz** [angular-eslint/angular-eslint#2151]
This rule can be turned off in 19.0.0-alpha.4, but not in 19.0.0.

```JSON
{
  "rules": {
    '@angular-eslint/no-input-rename': 'off',
  }
}
```

```
 error  Input bindings should not be aliased (https://angular.dev/style-guide#style-05-13)  @angular-eslint/no-input-rename
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `19.0.0` |
| `@typescript-eslint/parser`        | `8.16.0` |
| `ESLint`                           | `9.16.0` |
| `node`                             | `22.9.0` |

```sh
Angular CLI: 19.0.2
Node: 22.9.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@angular/pwa                    19.0.2
@angular/ssr                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.7.2
zone.js                         0.15.0
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Please provide a reproduction, you can fork this and share the updated link: https://stackblitz.com/edit/angular-eslint-repros?file=eslint.config.js&view=editor

**Comment by e-oz** [comment]
Thanks for that link. I've tried and could not reproduce. Looks like something is wrong with my configs. 
Sorry for wasting your time, and thanks for that link again!
