### ISSUE TITLE
Invalid rule result: Instance of class Promise.

### ISSUE THREAD

**Issue by jakehockey10** [angular-eslint/angular-eslint#226]
I'm attempting to move to eslint from tslint.  I'm on the step where we have to enter:
```
ng g @angular-eslint/schematics:convert-tslint-to-eslint {my-project}
```
When I run this command, I get no output other than:
```
Invalid rule result: Instance of class Promise
```
My Angular version is:
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.4
Node: 12.13.1
OS: win32 x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@angular/cdk                    11.0.2
@schematics/angular             8.3.28
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
```

When I search the web for this particular error message, it seems to make people think that I have mismatched schematics and angular versions.  But I'm not quite sure what I should do to rectify my situation.  It seems the @angular-eslint packages that were added to my package.json file in the previous step are on a beta version.

**Comment by jakehockey10** [comment]
Also, @schematics/angular and @schematics/update show up in the output of `ng --version`, but I don't see those in my package.json file.  Should they be there?  Is that the mismatch?

**Comment by JamesHenry** [comment]
@jakehockey10 yes you certainly need to git rid of the large mismatches stated above. Seeing Angular and schematics dependencies with different major numbers is the red flag.

Everything above should be either 11.x.x or 0.11xx.x - no 7s or 8s like you have currently.

I would advise looking up the version on npm, e.g. https://www.npmjs.com/package/@schematics/angular shows 11.0.4

Hope that helps.

**Comment by jakehockey10** [comment]
When I run `npm outdated`, `@angular/schematics`, for example, does not show up as needing an update.  This makes sense because it isn't even listed in my package.json.  I'm not quite sure how to update that if it isn't in my package.json.  I'm going to reference this ticket in the one that is open for this exact same issue
