### ISSUE TITLE
Cannot find tslint.json when running ng g @angular-eslint/schematics:convert-tslint-to-eslint

### ISSUE THREAD

**Issue by skyleguy** [angular-eslint/angular-eslint#228]
I am trying to convert from tslint to eslint in my Angular 10.1.3 project and then upgrade to angular 11+. After running the command:

```
ng g @angular-eslint/schematics:convert-tslint-to-eslint {{YOUR_PROJECT_NAME_GOES_HERE}}
```

 with my project it simply prints 'Cannot find tslint.json'.

My project structure is:

```
myProject ---
    | tsconfig.json
    | package.json
    | angular.json
    | src ---
            | tsconfig.app.json
            | tslint.json
```

None of us on the team can remember why we have tslint.json in src but would be nice to get this working without moving it.

I have even tried adding:

```
angular.json

project: {
  architect: {
    lint: {
      options: {
        tslintConfig: "src/tslint.json"
```

And i still see the error

Im running the command from the myProject folder and getting that error. I assume its because my tslint.json is in the src folder instead of at the root. Is there a way to specify a location for the tslint.json file when running convert-tslint-to-eslint? It works when i move that file but I'm trying to avoid doing so.

Thanks!

**Comment by JamesHenry** [comment]
Ah interesting, yeah this wasn't anticipated as being something users would have done...

We need to be able to distinguish between the root tslint.json and project tslint.json files (because of angular cli's support for multiple projects in a single workspace).

Naturally right now the assumption is the root tslint.json is at the root.

Does your workspaces have additional projects in? Please could you share the remaining config for that specific project above? I'm wondering how we could still infer it is the "root project" in your case

**Comment by surajmandalcell** [comment]
If you want VSCode specific fix,

```
{
  "eslint.workingDirectories": [
      {
        "directory": "yourProjectDir",
        "changeProcessCWD": true
      }
  ]
}
```
This does switch your current working directory

So instead you can add this to `.eslintrc.json`
```
...
{
    "files": ["*.ts"],
        "parserOptions": {
                 ...
                  "tsconfigRootDir": "directory_where_your_tsconfig_resides",
         }
}
```

**Comment by JamesHenry** [comment]
@surajmandalcell You seem to be talking about `tsconfig.json`, whereas this issue is about `tslint.json`

**Comment by surajmandalcell** [comment]
Well my bad 🤦🏻 , did face similar issue so thought this would help. Should I delete the comment?

**Comment by JamesHenry** [comment]
@surajmandalcell No worries, yeah sure that will help keep the issue focused. I'll delete my applicable comments after you

**Comment by skyleguy** [comment]
yes we do have multiple projects but they are actually all set up pretty much the same way except for some slight modifications (we have a deploy, dev, and mobile project).

All three of them have the root as "" and sourceRoot as "src"

I am trying to convert the dev project to eslint (which will basically be the same as converting the others except for some changes in the angular.json for each specific project).

i am pretty new to the actual setting up of the angular workspace but i did notice a property of the "lint" section called tslintConfig. maybe if we do something like this:

```
"dev": {
   "architect": {
      ...
      "lint": {
         "builder": "@angular-eslint/builder:lint",
         "tslintConfig": "tslint.json"
         "options": {
            "..."
          }
   }
}
```

then there could be a way to know that the tslint.json is found at tslintConfig's location?

**Comment by JamesHenry** [comment]
Just to make sure I’ve understood:

Are you saying you have 1 application but you build it multiple times for different environments?

And you have sought to achieve this by setting up multiple projects in your angular.json and point them all at the same set of source files?

**Comment by skyleguy** [comment]
pretty much. mostly for use in our package.json file where for example the "build" script will build our dev project but "build:ci" will build the deploy project with more specific settings to help with automation.

**Comment by JamesHenry** [comment]
@skyleguy Ok based on that I would strongly recommend you change your approach here.

What you are describing sounds much better suited to being a single project, with multiple build targets defined.

E.g. in your `angular.json` you would have something like this:

```jsonc
{
  "version": 1,
  "projects": {
    "ngappone": {
      "projectType": "application",
      // ... once source of truth for the same set of source files
      "root": "apps/ngappone",
      "sourceRoot": "apps/ngappone/src",
      "prefix": "app",
      "architect": {
        "build": {
          // ... standard build "target" stuff to give you an idea of how the targets are configured
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            // ... options here
          },
          "configurations": {
            // ... more options here
          }
        },
        "serve": {
          // ...  serve "target" configuration
        },
        "lint": {
          // ...  lint "target" configuration
        },
        "test": {
          // ...  test "target" configuration
        },

       // ... your additional build related targets, they can be called whatever you want
       "build-ios": {
         // ...  your "build-ios" "target" configuration
       },

      "build-foo": {
         // ...  your "build-foo" "target" configuration
       }
     },

// ... more config
```

I would say over and above this, I would ideally shoot for more of the "12 factor app" approach, where you build the app _once_, and applicable config comes from the environment rather than from differentiated build commands. However, we are then into the territory of completely changing your approach and I don't have full visibility to advise further.

What I have recommended above would appear to align to your current approach, but be greatly more idiomatic with how the Angular CLI configuration and primitives like builder are intended to be used and I think will be much easier for you to maintain and auto-update over time as well.

Hope that helps!

**Comment by cb-mmohammad** [comment]
I do have the same issue.
I too have the same project structure what kyle has mentioned above.

**Comment by GaryChamberlain** [comment]
I have the same issue, too.  Why ask for the project name if project-based configurations are not supported?

**Comment by JamesHenry** [comment]
@GaryChamberlain Your comment is undeservedly aggressive, and also nonsensical. This project is downloaded 100,000s of times per month and has a range of integration tests demonstrating that project based configurations are supported.

All I (as an unpaid volunteer creating all of this tooling and an experienced consultant in the Angular world) can do is reiterate that it is strongly inadvisable to structure your workspace as outlined above and it is not something I will be able to put my time towards supporting.

It is simply unreasonable to expect automated tooling - tackling a challenge as large as migrating users between two unrelated libraries - to be able to magically work for all of your customisations. Assumptions and trade-offs have to be made.

The only way that community run projects like this one move forward is with empathy and collaboration. I am very happy to consider a PR that updates the tooling in a way that applies to your custom use-case, as long as it does not degrade the workflow in any way for the majority of users of the standard Angular CLI approach.

Alternatively, you can of course consider some of my feedback in previous comments on this thread and refactoring your approach, which I believe will improve the overall maintability of the workspace in question over and above linting conversion concerns.

Thanks all!

**Comment by Romulo-S** [comment]
I have the same issue but with angular.json:
![image](https://user-images.githubusercontent.com/1325820/140686661-051fd36a-363b-4eaa-bee1-0efacadeee56.png)

**Comment by Romulo-S** [comment]
> I have the same issue but with angular.json: ![image](https://user-images.githubusercontent.com/1325820/140686661-051fd36a-363b-4eaa-bee1-0efacadeee56.png)

Solved by removing the dot "." in front of the file

**Comment by ThinleyJimmyDorji** [comment]
@skyleguy I had the same issue as yours. My workspace have multiple projects and the first time I ran this command 
`ng g @angular-eslint/schematics:convert-tslint-to-eslint {{YOUR_PROJECT_NAME_GOES_HERE}}`, the `tslint.json` file at the root directory is removed. I am not sure if there's a way to migrate all of the projects' tslint to eslint at a time but, the next time I migrated for another project I just created an empty `tslint.json` file at the root directory and migrated for the rest of the projects. Maybe you should try that out.
