### ISSUE TITLE
Consistent naming for accessibility rules

### ISSUE THREAD

**Issue by dev054** [angular-eslint/angular-eslint#238]
I saw that some accessibility rules starts with `accessibility-*`, but others not, like:

- click-events-have-key-events
- mouse-events-have-key-events
- no-autofocus
- no-distracting-elements
- no-positive-tabindex

I'd want to propose to naming them consistently starting with `accessibility` or even create a subpackage like `eslint-plugin-template-accessibility`.

**Comment by dev054** [comment]
Not related to accessibility, but I think `prefer-on-push-component-change-detection` could be better spelled as `prefer-component-on-push-change-detection` to be in sync with `prefer-*` rules.

**Comment by bbarry** [comment]
I am not sure if a separate suppackage is warranted but I think a config that includes all of them would be good.

**Comment by rafaelss95** [comment]
@JamesHenry Now that Angular v13 is closer and we'll probably have a major version shortly thereafter, do you have any thoughts on this?

**Comment by rafaelss95** [comment]
Indeed this prefix doesn't seem like a good idea. However, today we already have 21 template rules, most of them (more specifically, 11) focused on accessibility, not to mention the rules that we can possibly port from the https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/master/docs/rules (TBH, I miss  the _role_ related rules here).

With that in mind, would a new package called something like `@angular-eslint/accessibility` or `@angular-eslint/template-accessibility` be such a weird idea?

IMHO, it'd be good to separate which rules/utilities are geared exclusively to Angular (basically its styleguide or best practices) and those geared towards accessibility in a more general context.

In any case, I'll be fine either way, as long as we keep a standard.

**Comment by JamesHenry** [comment]
v16 is now the latest release and the `accessibility-` prefix has been stripped from the rules which had it. Accessibility related rules can be easily discovered via the new accessibility config

See the release notes for me: https://github.com/angular-eslint/angular-eslint/releases/tag/v16.0.0
