### ISSUE TITLE
use-pipe-decorator seems to be unnecessary

### ISSUE THREAD

**Issue by rafaelss95** [angular-eslint/angular-eslint#241]
If you try to declare a `@Pipe` in a `@NgModule` without the decorator, you'll get a compile-time error:

> The class 'XXXPipe' is listed in the declarations of the NgModule 'XXXModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.

Reference: https://github.com/mgechev/codelyzer/issues/592

**Comment by JamesHenry** [comment]
Resolved in the newly published `v2.0.0`, see releases or changelog for more information.
