### ISSUE TITLE
Builder: Add possibility to configure ignorePath of ESLint CLI

### ISSUE THREAD

**Issue by biolauri** [angular-eslint/angular-eslint#26]
In ESLint, it is possible to use a `.gitignore`-like file as an ignore file. According to its [docs on ESLint ignore configuration](https://eslint.org/docs/user-guide/configuring#using-an-alternate-file), it's possible to specify a path to an ignore file with `--ignore-path`.

I would like to configure this via this builder in the builder options and configurations and use the `.gitignore` file itself. In the [schema.json](../blob/master/packages/builder/src/schema.json), I couldn't find this as an option.

**Comment by JamesHenry** [comment]
PRs always welcome! :)

**Comment by JamesHenry** [comment]
Thanks to @paulotokimatu this is available in `0.0.1-alpha.27`!
