### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by BO41** [angular-eslint/angular-eslint#28]
Please update the readme to include more information.
Maybe the current status, the estimated first release, what needs to be done, how people can test existing lints, ...

**Comment by BO41** [comment]
Big thank you @JamesHenry !
I think this (mostly) counts as resolved :tada:

**Comment by JamesHenry** [comment]
Cool, I will continue to add more over the coming week @BO41 - I have a broken foot right now, and typing while having my leg up is really uncomfortable so I have limited stamina atm
