### ISSUE TITLE
Remove no-empty-lifecycle-method from recommended config

### ISSUE THREAD

**Issue by cyrilletuzi** [angular-eslint/angular-eslint#282]
Thanks for the hard work! 👍🏻 

Having the rule `no-empty-lifecycle-method` in `@angular-eslint/recommended` configuration is very surprising, as the Angular CLI always generates components with an empty `ngOnInit()`. Which is a very good thing, as it makes people aware you should do the things in `ngOnInit()` and not in the constructor.

But that means the Angular CLI is generating files which are not compliant with the recommended rules.

So I think it would be better to remove this rule from the recommended configuration, especially considering it is not an important rule at all (I think once webpack has done its job, having an empty `ngOnInit()` or nothing at all in the first place results in the exact same build).

I can take care of the PR.

**Comment by JamesHenry** [comment]
@mgechev Please could I get your thoughts on this one?

**Comment by mgechev** [comment]
This is a tricky one.

I agree it's a good idea to generate a component with `ngOnInit` lifecycle, but at the same time empty lifecycle hooks have a runtime cost.

Generally, in software development, there are limited occasions which require definition of a method with an empty body.

I don't think we should remove this rule from the recommended configuration. I'll have a chat with other folks from the tooling and framework teams to hear their thoughts on the auto generation of empty hook.

**Comment by cyrilletuzi** [comment]
If you choose to keep the rule in the lint configuration, fine by me, but please don't remove the auto generation of `ngOnInit()` from the CLI. The CLI has always done that, with reason, and that would be a huge step back to remove it.

As an Angular teacher, I can tell you that it would result for all beginners to code in the constructor, leading to a lot of issues.

An alternative would be for the lint rule to have an auto-fix. That way, the `ngOnInit()`s would be generated so people do things the right way, and the linter could easily get rid of the unused ones.

@mgechev Could you explain why empty lifecycles have a runtime cost? Aren't the build optimizations (like tree-shaking or else) supposed to get rid of them?

**Comment by cyrilletuzi** [comment]
Given the feedback from Minko, I'll close this issue, as I don't want it to result in the exact opposite of what I asked in the first place.

Still I would be interested to know why empty lifecycles have a runtime cost and why they aren't stripped by the build optimizations (like tree-shaking or else).
