### ISSUE TITLE
Running convert-tslint-to-eslint causes Invalid rule result: Instance of class Promise.

### ISSUE THREAD

**Issue by LudovicPecquot** [angular-eslint/angular-eslint#283]
Migrating TSLint (^6.1.3) of an Angular 11 project:
I've run : 
`ng add @angular-eslint/schematics `
It successfully adds the following dev dependencies:

> "eslint": "^7.6.0",
> "eslint-plugin-import": "2.22.1",
> "eslint-plugin-jsdoc": "30.7.6",
> "eslint-plugin-prefer-arrow": "1.2.2",
> "@angular-eslint/builder": "1.0.0",
> "@angular-eslint/eslint-plugin": "1.0.0",
> "@angular-eslint/eslint-plugin-template": "1.0.0",
> "@angular-eslint/schematics": "1.0.0",
> "@angular-eslint/template-parser": "1.0.0",
> "@typescript-eslint/eslint-plugin": "4.3.0",
> "@typescript-eslint/parser": "4.3.0"

Then, when I run 
`ng g @angular-eslint/schematics:convert-tslint-to-eslint app`  
I've got the following error:
**Invalid rule result: Instance of class Promise.**

My tslint.json file:
[tslint.zip](https://github.com/angular-eslint/angular-eslint/files/5786935/tslint.zip)

What happens ?
Thanks

**Comment by fmdavid** [comment]
I have the same issue.

**Comment by jakehockey10** [comment]
I have the same issue, but my ticket was closed.  Referencing it here to continue the conversation: https://github.com/angular-eslint/angular-eslint/issues/226

Apparently, my issue is due to old versions of dependencies.  But those dependencies don't even appear in my package.json.  Here is my angular versions for reference:

``` shell

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 12.13.1
OS: win32 x64

Angular: 11.0.2
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@angular/cdk                    11.0.0
@angular/cli                    11.0.5
@angular/compiler-cli           11.0.0
@angular/language-service       11.0.0
@schematics/angular             8.3.28
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

```

**Comment by jakehockey10** [comment]
Installing `@angualr-devkit/core` and `@angular-devkit/schematics` globally gave me the version 11 versions of those libraries, but still didn't change the output of `ng version` for me.  Do I just add `devDependencies` for these two libraries?  What about `@schematics/angular`?

**Comment by jakehockey10** [comment]
`npm i --save-dev @angular-devkit/core @angular-devkit/schematics @schematics/angular` indeed updates my `ng version` output.  Now when I run `ng g @angular-eslint/schematics:convert-tslint-to-eslint wheres-my-order`, I don't get that error.

I still would like to know if it was necessary for me to explicitly add that to my package.json's `devDependencies` like that.  But if so, hope that helps folks!

**Comment by JamesHenry** [comment]
Thanks folks, there is no real way to know how some workspaces ended up in this state. Perhaps a mixture of global vs local dependencies diverging over time?

Clearly new projects do not suffer with this issue, but I also do not want older projects that may have somehow ended up with this mismatch to not find a solution so I have now baked in guidance on this into each and every github issue template I just created.

Thanks again!

**Comment by superole** [comment]
I had almost identical `ng version`-output as @jakehockey10 and also just like him I did not have any of those three dependencies in my package.json. So I ran `npm ls` on each of them and found that the wrong version was a transitive dependency of another library (devextreme-angular) that I **do** depend on.

    +-- @angular/cli@11.2.7
    | `-- @schematics/angular@11.2.7
    `-- devextreme-angular@20.2.4
      `-- devextreme-schematics@1.2.10
        `-- @schematics/angular@8.3.29

However, the correct versions are also clearly there (and here I thought npm did not allow multiple versions of the same package 🤔), so I wonder why it fails for @angular-eslint/schematics when it works for the default schematics...

Anyway, I think this issue and the guidance for solving it should be mentioned not only in the issue templates, but also in the README.md in the section "Migrating an Angular CLI project from Codelyzer and TSLint", to save others from digging it up or preparing a new ticket, or giving up this tool altogether on a "not-worth-the-effort"-basis.

**Comment by typescripterpro** [comment]
https://typescripter.space/questions/common-errors-in-angular-2-due-to-tslint
