### ISSUE TITLE
.eslintrc.json file isn't updated if it already exists

### ISSUE THREAD

**Issue by localh0rzd** [angular-eslint/angular-eslint#284]
I currently work on a project that already has a `.eslintrc.json` configuration. When running `ng g @angular-eslint/schematics:convert-tslint-to-eslint [project name]`, only the `angular.json` configuration gets updated. The `.eslintrc.json` file, however, is left untouched. This caught me by surprise, because there was no warning indicating that the file hasn't been adapted.

It'd be great to add a warning message to the schematic, or at least a warning in the step-by-step instructions described in `README.md`

**Comment by JamesHenry** [comment]
I'm very sorry for how long it took for this to looked at @localh0rzd. I think this might potentially be outdated now as I can't see anywhere in the latest code where that would occur.

Please feel free to reopen if you have steps to reproduce. Or if anybody else sees this and is impacted by it, please open a new issue with full steps to reproduce.

Many thanks 🙏
