### ISSUE TITLE
Column numbers are off by one

### ISSUE THREAD

**Issue by rafaelss95** [angular-eslint/angular-eslint#294]
As reported in https://github.com/mgechev/codelyzer/issues/859, https://github.com/angular-eslint/angular-eslint/pull/205#discussion_r532132323 and https://github.com/angular-eslint/angular-eslint/pull/269#discussion_r548901096, column numbers are off by one.

Sample:

https://github.com/angular-eslint/angular-eslint/blob/b7ea86c6516d3ef8e07f98cfbd0c453970018b64/packages/eslint-plugin-template/tests/rules/no-call-expression.test.ts#L44-L45

<hr>

I noticed that we have a _hacky_ way to handle this in `no-negated-async`:

https://github.com/angular-eslint/angular-eslint/blob/c8dd14c95f881593d7b6ca9f7ba80b37b7eaf40f/packages/eslint-plugin-template/src/rules/no-negated-async.ts#L40 and https://github.com/angular-eslint/angular-eslint/blob/c8dd14c95f881593d7b6ca9f7ba80b37b7eaf40f/packages/eslint-plugin-template/src/rules/no-negated-async.ts#L57-L58

**Comment by drakenfly** [comment]
This is related to https://github.com/angular-eslint/angular-eslint/issues/292

If you turn on preserveWhitespaces, this off-by-one is resolved.

**Comment by JamesHenry** [comment]
I'll migrate @rafaelss95 comment to that issue, I have reported it to the Angular tooling team and asked for a process
