### ISSUE TITLE
@angular-eslint/builder@1.1.0 warning peer dependency with @angular-devkit/architect@0.1100.7

### ISSUE THREAD

**Issue by ahnpnl** [angular-eslint/angular-eslint#296]
`@angular-eslint/builder@1.1.0` warns about peer dependency with `@angular-devkit/architect@0.1100.7`. I got the warning

```
   Package "@angular-eslint/builder" has a missing peer dependency of "@angular-devkit/architect" @ "~0.1001.4 || ~0.1100.1".
```

when upgrading `@angular-eslint/builder@1.1.0`

**Comment by JamesHenry** [comment]
Hi @ahnpnl

I can only assume this was a temporary issue, or potentially an issue with your package manager tooling which you will need to look into.

You can see in your message that the range is `"~0.1001.4 || ~0.1100.1"`.

Clearly, `0.1100.7` satisfies the right hand side of that range so something else must be going on for you and I don't believe it's something that the library can control.

You can even validate that the version satisfies the range using NPM's visual tool here: https://semver.npmjs.com/

![image](https://user-images.githubusercontent.com/900523/104807824-d8197980-57d9-11eb-856a-c4837e2414bd.png)
