### ISSUE TITLE
Update Documentation for Performance Testing

### ISSUE THREAD

**Issue by bmbell** [angular-eslint/angular-eslint#297]
In the documentation, it says:

> Here are some steps you can take if you're linting process feels "unreasonably" slow:
> 
> Run the process with debug information from typescript-eslint enabled:
> DEBUG=typescript-eslint:* ng lint

But it is very unclear to me what this means.  Is there way to run this in the VS Code terminal?  Something like: ng lint -c <turn-debug-on>?  

Any help would be greatly appreciated!  Thanks!

**Comment by JamesHenry** [comment]
Hi @bmbell

The command in the snippet above is exactly what you need to run in your terminal of choice, such as VSCode's terminal, it is ready for you to copy and paste.

I have additionally added a full breakdown of what it does in https://github.com/angular-eslint/angular-eslint/pull/299
