### ISSUE TITLE
Installing on different directory

### ISSUE THREAD

**Issue by daniloesk** [angular-eslint/angular-eslint#307]
Error or unexpected behavior when creating a project using the directory argument.

When running on current directory, creates Angular files, installs dependencies and then displays "Cannot convert undefined or null to object". Example:
```shell
ng new --collection=@angular-eslint/schematics --directory . app2
```

When running on another directory, runs on workspace name instead of directory name. Since I had both directories it modified the wrong files. Example:
```shell
ng new --collection=@angular-eslint/schematics --directory app2_new app2
```

I used ` --prefix app2 --routing --skip-git --strict --style scss` as well, but I am not sure they are needed to reproduce.

**Workaround**: do not use `--directory` when generating the project.

**Comment by JamesHenry** [comment]
Hi @alan-agius4 @kyliau, I don't think it's possible for me to solve this currently because the Angular CLI does not pass the `directory` option to the 3rd party schematic collection at any point:

https://github.com/angular/angular-cli/blob/c2c9a4169c8fd6474c92f6fe73fbe372f72545c4/packages/schematics/angular/ng-new/index.ts#L43

Is it possible for us to add that in time for v12?

**Comment by alan-agius4** [comment]
The `directory` Is just like any other option.

it is provided if the schematic has is it in the schema.

https://github.com/angular/angular-cli/blob/c2c9a4169c8fd6474c92f6fe73fbe372f72545c4/packages/schematics/angular/ng-new/index.ts#L39:L41

**Comment by JamesHenry** [comment]
@alan-agius4 On line 72 the workspace schematic is specifically invoked with a subset of the options, specifically the ones I linked to above

**Comment by alan-agius4** [comment]
That's because the workspace schematic doesn't have a directory option and hence it cannot be provided.

**Comment by JamesHenry** [comment]
Passing `--collection=@angular-eslint/schematics` to `ng new` is no longer supported as of v4, which was just released.

This means we have one consistent way to add `@angular-eslint` to a workspace - run `ng add @angular-eslint/schematics` - regardless of whether that workspace is brand new or has existed for a while.

If you attempt to do it you will get a clear error with instructions on what to do instead.

It was not possible for all these different customizations of `ng new` to be supported when using a custom collection so the best thing is to optimize the `ng add` + docs (which have also been updated as part of v4).
