### ISSUE TITLE
Put only angular-eslint/* rules in recommended config

### ISSUE THREAD

**Issue by dev054** [angular-eslint/angular-eslint#322]
Currently if we extend the `angular-eslint/recommended`, it comes with some rules that doesn't belong in this package, so my proposal is that to expose only `angular-eslint` rules.

**Comment by JamesHenry** [comment]
This is not super clear cut - yes it is more expected in the ESLint ecosystem that a recommended config comes with the plugin's own rules configured, but in the Angular ecosystem there is an expectation that recommended configurations are comprehensive.

I think to try and get the best of both worlds I will spin out the current "extra" rules into a `recommended--extra` config which user's can optionally extend from
