### ISSUE TITLE
@angular-eslint/builder@1.1.0 warning peer dependency with @angular-devkit/architect@0.1101.2

### ISSUE THREAD

**Issue by joe1990** [angular-eslint/angular-eslint#323]
Update to Angular 11.1.1 is not possible because @angular-eslint/builder@1.1.0 uses @angular-devkit/architect "~0.1001.4 || ~0.1100.1" but Angular 11.1.1 wants to update to 0.1101.2.

Error: 
` Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular-devkit/architect" (requires "~0.1001.4 || ~0.1100.1", would install "0.1101.2").`

Update done with:
`ng update @angular/core @angular/cli`

**Comment by hamfastgamgee** [comment]
I definitely agree with this bug and it needs to be resolved, but as a datapoint, if I manually update the packages without using "ng update", it does appear to work fine with Angular 11.1+.

**Comment by sebastian-zarzycki-es** [comment]
FYI @angular-devkit/architect is now on 0.1101.3

**Comment by sebastian-zarzycki-es** [comment]
Sadly not fixed in recent 1.2.0 release.

**Comment by undrivendev** [comment]
> I definitely agree with this bug and it needs to be resolved, but as a datapoint, if I manually update the packages without using "ng update", it does appear to work fine with Angular 11.1+.

You could also use the `--force` option to ignore the peer dependencies.

**Comment by sebastian-zarzycki-es** [comment]
They would still appear with each subsequent npm install, though. I mean, that warning is there for a reason.

**Comment by BePo65** [comment]
Just as an update: the same problem exists with the current version of angular 11 (11.2.3) using @angular/cli (Version 11.2.2) requiring @angular-devkit/architect Version 0.1102.2.

**Comment by jpelton-stroud** [comment]
anybody know if there's some breaking change in `@angular-devkit/architect` above v0.1100.1 that would justify the hardcap?

**Comment by sebastian-zarzycki-es** [comment]
My guess it's just a cap to be on the safeside, but there's nothing inherently breaking. Still, annoying to see these warnings.

**Comment by BePo65** [comment]
Momentarily I use it in combination with `@angular-devkit/architect v0.1102.3` without any problems.

**Comment by JamesHenry** [comment]
This is addressed in v2, because we rely on some recent fixes within the angular compiler, so our version support is changing there.

The PR for v2 is here: https://github.com/angular-eslint/angular-eslint/pull/358

I am publishing prereleases from it for those who are feeling brave - no migration advice will be provided until it is complete, but for anyone who cannot live with the peerDep warning, that is another option for you.

My plan is for v2 stable to go out sometime this week

**Comment by OrangeDog** [comment]
Note that npm 7 makes this an error rather than a warning.

**Comment by JamesHenry** [comment]
Resolved in the newly published `v2.0.0`, see releases or changelog for more information.
