### ISSUE TITLE
i18n rule - non-textual content filter

### ISSUE THREAD

**Issue by janousek** [angular-eslint/angular-eslint#329]
Currently there is a pattern ("boundTextAllowedPattern" option) to filter out non-textual content. But it works only for bound text (for example: `<span>+{{data_from_backend}}</span>`). 
https://github.com/angular-eslint/angular-eslint/blob/eeb49d491bb92e470f505a699ef3e12963ff351b/packages/eslint-plugin-template/src/rules/i18n.ts#L252

But it is not applied to text nodes (for example: `<span>+</span>`).
https://github.com/angular-eslint/angular-eslint/blob/eeb49d491bb92e470f505a699ef3e12963ff351b/packages/eslint-plugin-template/src/rules/i18n.ts#L249

So there is currently no way to filter out this content. There are currently two options:
1. Apply "checkBoundTextAllowedPattern" to the text nodes.
2. Add new option ("checkTextAllowedPattern") and apply it to the text nodes.

**Comment by rafaelss95** [comment]
Closing in favor of #298.
