### ISSUE TITLE
Not getting template errors like "<component> is not a known element". (.html file not inline)

### ISSUE THREAD

**Issue by bogacg** [angular-eslint/angular-eslint#340]
Following recommended method, on a fresh project creation with `ng new --collection=@angular-eslint/schematics` I've created a component and start playing with it and I've noticed if I type things wrong in template, like its component tag, I get no error on VsCode. (That is in `app.component.html` typing newly created component name with a typo)

With TsLint that mistake gives `<component> is not a known element` **ngtsc** error.

Even worse, it's not just VsCode issue. If I do `ng lint` command line check I still don't get an error for template typo.

What does EsLint / Angular-Eslint check with templates? Am I missing something?

**Comment by snebjorn** [comment]
That does work for me 

![image](https://user-images.githubusercontent.com/1266245/108908711-eb630480-7623-11eb-9ce5-267e05673a2f.png)

**Comment by JamesHenry** [comment]
`ngtsc` and the screenshot shown are not related to linting. I assume what you are discussing is the angular language service.

The angular language service is maintained by the Angular team and is not in scope for ESLint, angular-eslint, typescript-eslint or any of the tooling in this repo.

**Comment by bogacg** [comment]
@JamesHenry thank you for your hard work. While you are right about both projects not being tied together / directly related, if `angular-eslint` will be in the future of Angular development and is the only common denominator for an important development feature being disabled/broken at this moment I'd expect better investigation on the subject. I am pretty sure if I open an issue on the Angular Language Service side I'll be redirected here again and we'll be in a chicken & eggs situation.

**Comment by JamesHenry** [comment]
@bogacg I believe that is not correct - the language service has no overlap with the linter and never has done. They are different projects doing different things, they both just happen to give feedback in similar looking dialogs within VSCode.

If you are having issues with the language service there is also no reason they would redirect you here - unlike with TSLint, the language service is being actively maintained by the Angular Team.

**Comment by JamesHenry** [comment]
If your error were related to linting you would see “tslint” in the place where it currently says “ngtsc”.
