### ISSUE TITLE
"plugin:chai-friendly/recommended" not working

### ISSUE THREAD

**Issue by msalzig** [angular-eslint/angular-eslint#341]
The rule "plugin:chai-friendly/recommended" from the eslint-plugin-chai-friendly npm packages have not effects.

Example Cucumber Steps:
Then('The Choose User page is still open', async function(): Promise<void> {
    const userName = await userPage.isOpen();
    **expect(userName.length > 0).to.be.true;**
    return Promise.resolve();
});
I have problems like "Expected an assignment or function call and instead saw an expression."

![image](https://user-images.githubusercontent.com/5517638/108309033-1aefb800-71b1-11eb-9f9b-122e3edfe41a.png)

**Comment by JamesHenry** [comment]
Hi @msalzig, this project provides plugins and and a parser for Angular-specific ESLint rules, and isn't responsible for how other unrelated ESLint rules behave.

If you feel you have encountered an issue with the chai or @typescript-eslint packages then you will need to open an issue on the appropriate repo.

Thanks!
