### ISSUE TITLE
convert-tslint-to-eslint incorrectly converts no-parameter-reassignment to @typescript-eslint/no-param-reassign

### ISSUE THREAD

**Issue by snebjorn** [angular-eslint/angular-eslint#344]
According to https://github.com/typescript-eslint/typescript-eslint/blob/c8a4dadeab8a64fb4768deda8f65475435dd2cad/packages/eslint-plugin/ROADMAP.md#typescript-specific `no-parameter-reassignment` should be converted into `no-param-reassign`.

However it's converted into `@typescript-eslint/no-param-reassign` causing this error to be show at the top of every ts file in VSCode

![image](https://user-images.githubusercontent.com/1266245/108403775-617bfb80-721f-11eb-9fe2-8e7081fdba43.png)

**Comment by JamesHenry** [comment]
HI @snebjorn, please can you report this to/fix this in: https://github.com/typescript-eslint/tslint-to-eslint-config

That's where the source of truth for conversions comes from

**Comment by JamesHenry** [comment]
Thanks! We can leave this open so that we know when we need to update the version we use

**Comment by JamesHenry** [comment]
Looks like the fix has been merged, just waiting on a new release

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/tslint-to-eslint-config/releases/tag/v2.3.0 - sorry for the delay @JamesHenry @snebjorn!

**Comment by JamesHenry** [comment]
Great, thanks @JoshuaKGoldberg !
