### ISSUE TITLE
Clicking @angular-eslint/template/<rule> in VSCode gives "Unable to open file" error

### ISSUE THREAD

**Issue by snebjorn** [angular-eslint/angular-eslint#345]
Clicking the eslint rule link (`eslint(@angular-eslint/template/click-events-have-key-events)`) in the popup tooltip in VSCode causes an error to occur instead of opening an URL to the rule definition.

![image](https://user-images.githubusercontent.com/1266245/108482882-54e8b900-729a-11eb-85eb-0755faede69d.png)

![image](https://user-images.githubusercontent.com/1266245/108480422-39c87a00-7297-11eb-9f2b-0451eb0f7374.png)

**Comment by JamesHenry** [comment]
Thanks you @snebjorn, we can fix this by adding a URL on each rule, I have a PR open to address that
