### ISSUE TITLE
"Parsing error: Unexpected token <" for inline template

### ISSUE THREAD

**Issue by berezinSerghei** [angular-eslint/angular-eslint#346]
Receiving this error, when try use eslint in my Angular project.
Seems like olugin for inline templates is not applied.

![image](https://user-images.githubusercontent.com/12122902/108497856-c2094800-72b4-11eb-86df-6cd499449513.png)
![image](https://user-images.githubusercontent.com/12122902/108497890-ca618300-72b4-11eb-8651-cd6e9ea6f0ed.png)

.eslintrc.json:
```json
{
  "root": true,
  "env": {
      "es6": true,
      "browser": true
  },
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "src/test2.ts"
      ],
      "parserOptions": {
        "project": "./tsconfig.json",
        "createDefaultProgram": true,
        "ecmaVersion": 6,
        "sourceType": "module"
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "parser": "@typescript-eslint/parser",
      "plugins": [
        "@typescript-eslint",
        "modules-newline"
      ],
      "rules": {...}
    }
  ]
}
```

**Comment by JamesHenry** [comment]
You are missing the override for html files which wires up the template parser.

The inline templates get processed to be treated as HTML, but you currently do not have anything set up to handle HTML. Please see the README for how to apply it.

**Comment by berezinSerghei** [comment]
Thank you for quick response.
Works good.
