### ISSUE TITLE
Should eslint-plugin-prefer-arrow still be a peer dependency?

### ISSUE THREAD

**Issue by reduckted** [angular-eslint/angular-eslint#348]
`eslint-plugin-prefer-arrow` is listed as a peer dependency, but since #179 it's only used in the `ng-cli-compat.json` configuration.

If you're not using that configuration, then it's a bit annoying having warnings appear during npm install.

**Comment by guilhermetod** [comment]
I raised this today in #178 with an example of another config package that has gone through the same issue.

I don't know how close this package is to the Angular team, but maybe this will need a take of the cli team, so I'm not sure how easy it would be to find a solution here. Maybe they'll consider streamlining the recommended configs for a new release. I definetly agree more with the base recommended config than with the ng-cli-compat.

**Comment by guilhermetod** [comment]
Just as an update: If you're using npm 7, there's no warning anymore since it automaticallt install peer deps, se the only problem would be the extra potentially useless packages

**Comment by JamesHenry** [comment]
This will be addressed in v3, those extra plugins will only be dynamically installed if you are converting from tslint. They will no longer be peerDeps and no longer be installed during `ng add`.

**Comment by JimLynchCodes** [comment]
I am still getting these errors from the missing libs when trying to run eslint...  😣
