### ISSUE TITLE
Vulnerability in tslint-to-eslint-config 2.0.1 (lodash 4.17.20)

### ISSUE THREAD

**Issue by Akkora** [angular-eslint/angular-eslint#363]
`@angular-eslint/schematics` has a dependency to an old version of `tslint-to-eslint-config` which loads the vulnerable lodash version 4.17.20. They released version 2.2.0, which makes use of lodash 4.17.21 and therefore fixes the vulnerability issue.

Can you please update the version of tslint-to-eslint-config to 2.2.0? I can also try to create a pull request.

You can find more information about the vulnerability: https://snyk.io/vuln/npm:lodash

**Comment by JamesHenry** [comment]
It will be released in v2 this week,

**Comment by JamesHenry** [comment]
Resolved in the newly published `v2.0.0`, see releases or changelog for more information.
