### ISSUE TITLE
--format output is always invalid

### ISSUE THREAD

**Issue by OrangeDog** [angular-eslint/angular-eslint#375]
The fixes for #303 and #361 have made it worse in 2.0

Both a status message (Linting "project"...) and the report output are written to STDOUT.
The `--silent` flag now suppresses the report instead of just the status messages.

Theoretically there's a workaround if you grep out the invalid lines, but it's trickier than the previous workaround.

**Comment by JamesHenry** [comment]
Your summary is not accurate, nothing about stdout vs any other output channel changed in v2. What you are seeing is down to a very simple mistake that I made: https://github.com/angular-eslint/angular-eslint/pull/376

**Comment by JamesHenry** [comment]
Please give `2.0.2` a try

**Comment by OrangeDog** [comment]
That works now, thanks.

It was the behaviour of the ` --silent` flag that had changed.
