### ISSUE TITLE
migration from 1 to 2 creates .eslintrc.json when you have a .eslintrc.js file already

### ISSUE THREAD

**Issue by bbarry** [angular-eslint/angular-eslint#380]
steps to reproduce:

1. have `@angular-eslint` 1.2.0 installed and configured with `.eslintrc.js` file
2. update with `ng update @angular-eslint/schematics`

after update you will have a file `.eslintrc.json` with the contents `{}`

**Comment by bbarry** [comment]
I think if you have an `.eslintrc.js` file, the migration should skip the part about updating `.eslintrc.json` and direct you to read about the breaking changes,

**Comment by ahnpnl** [comment]
I observed the same thing. After migration, I was a bit lost of what should be changed I  my js configuration to be compatible with v2

**Comment by bbarry** [comment]
@ahnpnl (and anyone else finding this issue) remove `use-pipe-decorator ` from your config if you have it there and delete the .json file that was added.

**Comment by JamesHenry** [comment]
I have explicitly documented our policy on custom ESLint config file types: https://github.com/angular-eslint/angular-eslint#notes-on-supported-eslint-configuration-file-types

Additionally, I will endeavor to make release notes for major versions as clear as possible for folks who are not using the automated migrations from now.

Many thanks 🙏
