### ISSUE TITLE
New Angular App with Eslint Schematic as Configuration Throws Error

### ISSUE THREAD

**Issue by mtpultz** [angular-eslint/angular-eslint#395]
**Description and reproduction of the issue**
When creating a new Angular using the eslint schematic it throws an error of:

```
ng new example-app --collection=@angular-eslint/schematics --directory=frontend --routing --skip-git --strict --style=scss
```

![image](https://user-images.githubusercontent.com/599498/113783656-eac09200-96e8-11eb-966a-9367b16871e4.png)

And afterwards if you run `ng lint` you get this error:

![image](https://user-images.githubusercontent.com/599498/113784096-abdf0c00-96e9-11eb-9c0e-e1a6fa543ca8.png)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 11.2.7
Node: 14.15.4
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.7 (cli-only)
@angular-devkit/core         11.2.7 (cli-only)
@angular-devkit/schematics   11.2.7 (cli-only)
@schematics/angular          11.2.7 (cli-only)
@schematics/update           0.1102.7 (cli-only)

```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by mtpultz** [comment]
Seems to work if I only use `ng new example-app --collection=@angular-eslint/schematics` with no other flags.  If this is expected then it should be indicated in the README that afterwards if you want to rename the install folder, or not have strict mode on, etc; you need to manage this yourself

**Comment by janzeppenfeld** [comment]
Hi, I stumbled over the same issue yesterday. The issue seems to be related to the `directory` flag. I tried it with
- `--directory=./` and
- `--directory=frontend`,

both resulting in the described error. It works just fine without the flag. As a workaround I renamed the folder after creating the project but IMHO it should work with the `directory` flag as well.

**Comment by JamesHenry** [comment]
Passing `--collection=@angular-eslint/schematics` to `ng new` is no longer supported as of v4, which was just released.

This means we have one consistent way to add `@angular-eslint` to a workspace - run `ng add @angular-eslint/schematics` - regardless of whether that workspace is brand new or has existed for a while.

If you attempt to do it you will get a clear error with instructions on what to do instead.

It was not possible for all these different customizations of `ng new` to be supported when using a custom collection so the best thing is to optimize the `ng add` + docs (which have also been updated as part of v4).
