### ISSUE TITLE
Bad RULE_NAME in eslint-plugin prefer-output-readonly.ts

### ISSUE THREAD

**Issue by stephen-dirtcreative** [angular-eslint/angular-eslint#40]
Source file with issue: packages/eslint-plugin/src/rules/prefer-output-readonly.ts

Existing line: export const RULE_NAME = 'no-output-on-prefix';

Should probably be?: export const RULE_NAME = 'prefer-output-readonly';

**Comment by JamesHenry** [comment]
Thanks @stephen-dirtcreative, I've created a PR to fix it. Feel free to just submit a PR for small fixes like this in future, I will make sure they get merged!
