### ISSUE TITLE
[i18n] fix adds errors to templates

### ISSUE THREAD

**Issue by DaSchTour** [angular-eslint/angular-eslint#400]
**Description and reproduction of the issue**

I have a section in my template that looks like this
```
<div [hidden]="compact">
      {{ totalAssets | ngrxPush }} <span class="hidden small:inline" i18n="@@assets.list.total">total</span> /
      <ng-container *ngrxLet="selectedAmount$; let selectedAmount">
        <button class="show-selected" [disabled]="selectedAmount === 0" (click)="openSelectionOverlay()">
          {{ selectedAmount }}
          <span class="hidden small:inline" i18n="@@assets.list.selected">selected</span>
        </button>
      </ng-container>
    </div>
```

ESLint fix adds an i18n to the surounding div which then results in `Cannot mark an element as translatable inside of a translatable section. Please remove the nested i18n marker.`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.20.0` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.23.0` |
| `node`                             | `14.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 11.2.6
Node: 14.16.0
OS: darwin x64

Angular: 11.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.6
@angular/cdk                    11.2.7
@angular/cli                    11.2.6
@angular/material               11.2.7
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.1.5
webpack                         4.46.0

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by rafaelss95** [comment]
Hi @DaSchTour, thanks for reporting this. Would you mind to share your eslint config?

**Comment by rafaelss95** [comment]
Ok, so I was able to reproduce this even with the default config. I've submitted the PR #411 to fix this, but you will still see reports regarding to this as we currently don't have a way to filter non-bound texts, as it was prevously stated in #298 and #329.
