### ISSUE TITLE
ng new example --collection=@angular-eslint/schematics with Angular 12 fails

### ISSUE THREAD

**Issue by NealGooch** [angular-eslint/angular-eslint#401]
I realise Angular 12 is currently in RC state but wanted to try it out with eslint and found I couldn't!.

**Angular 11 Sample - Works**
```
npm i -g @angular/cli @angular-devkit/core  @angular-devkit/schematics @angular-eslint/schematics
+ @angular-eslint/schematics@2.0.2
+ @angular-devkit/core@11.2.8
+ @angular-devkit/schematics@11.2.8
+ @angular/cli@11.2.8

ng new example1 --collection=@angular-eslint/schematics --skip-git --strict --style=css --routing=true
```

**Angular 12 Sample - Fails (schematics@2)**
```
npm i -g @angular/cli@next @angular-devkit/core@next @angular-devkit/schematics@next @angular-eslint/schematics
+ @angular-eslint/schematics@2.0.2
+ @angular-devkit/core@12.0.0-next.8
+ @angular-devkit/schematics@12.0.0-next.8
+ @angular/cli@12.0.0-next.8

ng new example2 --collection=@angular-eslint/schematics --skip-git --strict --style=css --routing=true
Path "/tslint.json" does not exist.
```

**Angular 12 Sample - Fails (schematics@3)**
```
npm i -g @angular/cli@next @angular-devkit/core@next @angular-devkit/schematics@next @angular-eslint/schematics@next
+ @angular-eslint/schematics@3.0.0-alpha.2
+ @angular-devkit/core@12.0.0-next.8
+ @angular-devkit/schematics@12.0.0-next.8
+ @angular/cli@12.0.0-next.8

ng new example3 --collection=@angular-eslint/schematics --skip-git --strict --style=css --routing=true
Path "/tslint.json" does not exist.
```

**Comment by NealGooch** [comment]
This appears to be caused by https://github.com/angular-eslint/angular-eslint/blob/322e33ba66719d497d50b4d4fe75b5c03bf3bb45/packages/schematics/src/utils.ts#L302 which just tries to delete tslint.json without checking if it exists.

**Comment by JamesHenry** [comment]
@NealGooch Please note Angular 12 is _not_ in RC.

Support for Angular 12 will come in due course

**Comment by JamesHenry** [comment]
Additionally, I had already made the update to remove this error in v3: https://github.com/angular-eslint/angular-eslint/pull/388

It just hasn't been released yet.

**Comment by kennethkeim** [comment]
I'm getting the same error on Angular 11 (ONLY if I use `skip-tests` and `minimal` flags). Let me know if I should open a new issue.

```
@angular-eslint/schematics@2.1.0
@angular-devkit/core@11.2.8
@angular-devkit/schematics@11.2.8
@angular/cli@11.2.8

ng new name --collection=@angular-eslint/schematics --package-manager=npm --routing --strict --style=scss --skip-tests --minimal
```

Error:
`Path "/tslint.json" does not exist.`

Again, this exact command works if I omit the last two flags.
