### ISSUE TITLE
[sort-ngmodule-metadata-arrays] add auto fix

### ISSUE THREAD

**Issue by splincode** [angular-eslint/angular-eslint#406]
`'@angular-eslint/sort-ngmodule-metadata-arrays': 'error'`

![image](https://user-images.githubusercontent.com/12021443/114319041-6d49b700-9b18-11eb-9818-5da637706e37.png)

we have a huge code base in our project, however, manually changing everything is very difficult and time-consuming

**Comment by JamesHenry** [comment]
Impressive that you are already using such a new rule! Would you like to submit a PR for this @splincode?

**Comment by splincode** [comment]
I will try to )

**Comment by splincode** [comment]
Is there somewhere documentation and examples of how you have already used such auto-fixes (in your project code)?

**Comment by JamesHenry** [comment]
@splincode Yes a number of rules have auto fixes, just search the codebase for “fixer” and take a look at the docs on https://eslint.org/docs/developer-guide/working-with-rules
