### ISSUE TITLE
recommended--extra configuration can not be loaded

### ISSUE THREAD

**Issue by jnizet** [angular-eslint/angular-eslint#417]
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.22.0` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.24.0` |
| `node`                             | `12.20.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 11.2.9
Node: 12.20.1
OS: darwin x64

Angular: 11.2.10
... common, compiler, compiler-cli, core, forms, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
rxjs                            6.6.7
typescript                      4.1.5
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

Replacing `"plugin:@angular-eslint/recommended"` by `"plugin:@angular-eslint/recommended--extra"` in the `.eslintrc.json` and running `ng lint` fails with the following error message (on macOS):

```
An unhandled exception occurred: Failed to load config "plugin:@angular-eslint/recommended--extra" to extend from.
```

Trying to load unother configurations (`all`for example) works fine.

I've noted that, unlike the other configurations, `recommended--extra` is not listed in the `dist/index.d.ts` file.

**Comment by JamesHenry** [comment]
Sorry about that @jnizet, you're absolutely right. I'll get it fixed up shortly
