### ISSUE TITLE
lint builder doesn't accept multiple files or glob-like from the CLI

### ISSUE THREAD

**Issue by aboodz** [angular-eslint/angular-eslint#421]
**Description and reproduction of the issue**

I have an Angular project configured with eslint. When I execute `ng lint` on the workspace the linters seems to work fine. However, when I try linting a files list, using `lint-staged`, it keeps producing an error. The below is an example of what I am trying to achieve (I tried also replacing files with glob-like `src/app/*.ts`, I got the same error):
```shell
ng lint my-application --lint-file-patterns src/app/file1.ts src/app/file2.ts src/app/file3.ts

Unknown option: 'src/app/file2.ts'
Unknown option: 'src/app/file3.ts'
```

The same command works if it is a single file. 
```shell
ng lint my-application --lint-file-patterns src/app/file1.ts 
```

It looks like it's treating the files list as command options.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.16.1` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `4.0.0` |
| `node`                             | `v15.14.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 11.2.9
Node: 15.14.0
OS: darwin x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.9
@angular-devkit/build-angular      0.1102.9
@angular-devkit/core               11.2.9
@angular-devkit/schematics         11.2.9
@angular/cdk                       11.2.9
@angular/cli                       11.2.9
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.9
@angular/material-moment-adapter   11.2.9
@schematics/angular                11.2.9
@schematics/update                 0.1102.9
rxjs                               6.6.3
typescript                         4.0.5
      4.0.5
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
This is more of a question for the Angular CLI itself, it is not specific to our builder:

`lintFilePatterns` is an array and I believe the only supported way to pass array values to Angular CLI builders via CLI arguments is to specify the argument multiple times. E.g. for your example above it should be:

```sh
ng lint my-application --lint-file-patterns=src/app/file1.ts  --lint-file-patterns=src/app/file2.ts  --lint-file-patterns=src/app/file3.ts
```

I have tested this on a local project and it works

**Comment by rokerkony** [comment]
@JamesHenry on the other side, there could be fallback param `lintFilePatternsStringified` or something similar, which would split the string with space and take it from those pre-commit hook tools as:

```
ng lint my-application --lint-file-patterns-stringified src/app/file1.ts src/app/file2.ts src/app/file3.ts
```

but it would have to be greedy and eat all the rest of the command as one string value...

Is there a way to do such a thing? And would it make sense?

In the meantime, for anyone reading this thread, I think it is ok to use https://github.com/paleite/eslint-plugin-diff

**Comment by juanmendes** [comment]
Note that this makes this incompatible with a tool like [lint-staged](https://github.com/okonet/lint-staged#readme).  The tool just appends the staged filenames to your command. The suggested usage in package.json is something like the following:


```json
  "lint-staged": {
    "**/*.ts": [
      "eslint --fix"
    ],
    "*.{ts,scss,css,html,json,js}": [
      "prettier --write"
    ]
  },
```

Which will run `eslint --fix file1 file2 file3` and `prettier --write file1 file2 file3`

I see only two benefits to using `ng lint` instead of `eslint` directly:

* Having potentially different rules for each monorepo subproject
* Having some help from angular if they start using another lint tool (though converting from tslint to eslint was not that simple)

If you don't care about either of the above I suggest you just use lint-staged, prettier and eslint.
