### ISSUE TITLE
esLint rule for return type of the Angular project is not working

### ISSUE THREAD

**Issue by Sampath-Lokuge** [angular-eslint/angular-eslint#441]
Hi,

I would like to have an esLint rule to notify about the return type of the method. But I was not able to do that. I have tried this `"@angular-eslint/explicit-function-return-type": "on"` But no effect. Any clue here?

I would like to have an error (rule) here hence no return type;

```
signUp() 
{
}
```

I like to adjust it like so after warning or error

 ```
    signUp() : void
    {
    }
```

`.eslintrc.json`

```
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-class-suffix": [
          "error",
          {
            "suffixes": [
              "Page",
              "Component"
            ]
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "app",
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "app",
            "style": "camelCase"
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}

```

`package.json`

```
{
  "name": "A",
  "version": "0.0.1",
  "author": "A",
  "homepage": "A",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.13",
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@capacitor/core": "2.4.7",
    "@ionic/angular": "^5.5.2",
    "aws-amplify": "^3.3.27",
    "primeicons": "^4.1.0",
    "primeng": "^11.4.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.4",
    "@angular-eslint/builder": "2.0.2",
    "@angular-eslint/eslint-plugin": "2.0.2",
    "@angular-eslint/eslint-plugin-template": "2.0.2",
    "@angular-eslint/template-parser": "2.0.2",
    "@angular/cli": "~11.2.4",
    "@angular/compiler": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@angular/language-service": "~11.2.0",
    "@capacitor/cli": "2.4.7",
    "@ionic/angular-toolkit": "^3.1.1",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "ts-node": "~8.3.0",
    "typescript": "~4.0.2"
  },
  "description": "A"
}
```

**Comment by JamesHenry** [comment]
@Sampath-Lokuge The rule you are looking for comes from @typescript-eslint:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md

So it's `"@typescript-eslint/explicit-function-return-type": ["error"]` that you want

**Comment by Sampath-Lokuge** [comment]
Hi @JamesHenry 

Still no luck. Any clue, please?

`.eslintrc.json`

```
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-class-suffix": [
          "error",
          {
            "suffixes": [
              "Page",
              "Component"
            ]
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "app",
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "app",
            "style": "camelCase"
          }
        ],
        "@typescript-eslint/explicit-function-return-type": [
          "error"
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}
```

**Comment by JamesHenry** [comment]
@Sampath-Lokuge No, I'm afraid I cannot reproduce - with that eslint config I do get the feedback that a function needs an explicit return type:

![image](https://user-images.githubusercontent.com/900523/118132097-5d234100-b410-11eb-9353-7f443aa2c2ce.png)

If the issue persists (and it's also not entirely clear what the issue is? An error? Or you just don't get feedback relating to that rule), please create a minimal reproduction repo and link it here.

Many thanks!

**Comment by Sampath-Lokuge** [comment]
Hi @JamesHenry 

Please see it here: https://github.com/Sampath-Lokuge/esLint

This is an `Ionic/ Angular` project. You can see this file: https://github.com/Sampath-Lokuge/esLint/blob/main/src/app/folder/folder.page.ts 

Thanks for your support here.

**Comment by JamesHenry** [comment]
@Sampath-Lokuge I'm afraid again I cannot reproduce...

All I did was clone your repo, run `npm i` and then run `ng lint` - I made no modifications - and I get the lint result in both the `ng lint` output and in VSCode:

![image](https://user-images.githubusercontent.com/900523/118362833-63e1bd80-b5a2-11eb-9e66-4ca3cdcdb093.png)

**Comment by Sampath-Lokuge** [comment]
Hi @JamesHenry 

I didn't know about the `ng lint` CLI. When I was working with TSLint it shows directly on the VS Code. i.e. without running any CLI.

I have 2 questions here.

1. Now I can see errors after running `ng lint`. But it doesn't show those errors on the VS Code like yours. Any clue for that? Are you using any VS Code plugin here?

2. Can't we see those errors when I do that error immediately or something like that? i.e. without running `ng lint` separately.

Here you can see that on the TSLint era message without running anything and also immediately after the issue.

![ts](https://user-images.githubusercontent.com/5206526/118364845-d741fa00-b5b7-11eb-9106-63e1e5986158.png)



Thanks a lot for your support here.

**Comment by JamesHenry** [comment]
@Sampath-Lokuge To be clear, `ng lint` and VSCode are entirely separate concerns - they do not interact in any way.

I simply combined them into a single screenshot for brevity.

Yes, you have to have the official ESLint VSCode extension installed: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

You do not need to run any CLI commands to trigger the messages from that extension, but it does need to be installed first.

**Comment by JamesHenry** [comment]
Be sure to also read the README on using that extension with HTML files: https://github.com/angular-eslint/angular-eslint#linting-html-files-and-inline-templates-with-the-vscode-extension-for-eslint

**Comment by Sampath-Lokuge** [comment]
Hi @JamesHenry 

Thanks a lot for your great support. Have your 3 coffees from me. :)

**Comment by JamesHenry** [comment]
That’s very kind, thank you @Sampath-Lokuge 🙏 happy to help

**Comment by Sampath-Lokuge** [comment]
You're welcome!
