### ISSUE TITLE
@angular-eslint not compatible with Angular 12

### ISSUE THREAD

**Issue by jtsom** [angular-eslint/angular-eslint#443]
**Description and reproduction of the issue**

Trying to update project that was migrated from TSLint to ESLint fails installing packages due to dependency conflicts between Angular 12 and @angular-eslint packages.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ng10-test@0.0.0
npm ERR! Found: @angular/cli@12.0.0
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"^12.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 11.2.0 < 12.0.0" from @angular-eslint/builder@4.3.0
npm ERR! node_modules/@angular-eslint/builder
npm ERR!   dev @angular-eslint/builder@"^4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/john/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2021-05-13T00_40_07_296Z-debug.log
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.16.1` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `^7.6.0` |
| `node`                             | `16.1.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 16.1.0
Package Manager: npm 7.12.1
OS: darwin x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.0.0 (cli-only)
@angular-devkit/schematics      12.0.0 (cli-only)
@angular/cli                    12.0.0 (cli-only)
@schematics/angular             12.0.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      4.2.4 (cli-only)

```

- [X ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by phalgunv** [comment]
I have just upgraded my project to use Angular 12, I still see the same issue noted above while trying to update to the latest release of angular-eslint. As this issue is closed, I was assuming this issue to have been fixed, can you let me know if I am missing something?

**Comment by destus90** [comment]
@phalgunv 
I have updated my project with the newest version of Angular and angular-eslint with no problems above. First of all, try to run 
`ng update @angular/core @angular/cli --force` and then update the rest of the packages as well.

**Comment by phalgunv** [comment]
@destus90 
Yes, I have tried updating angular and the rest of the packages using "--force". It would be good if the users of the package are not required to use "--force" option if Angular 12 is supported officially.
