### ISSUE TITLE
Add `npm run lint` script when running `ng add @angular-eslint/schematics`

### ISSUE THREAD

**Issue by MitchellCash** [angular-eslint/angular-eslint#452]
**Description and reproduction of the issue**

On an Angular v12 project when running `ng add @angular-eslint/schematics` I would like it to also add a `npm run lint` script to `package.json` to save me adding that line.

Example:

```json
...
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"    <-- ADD THIS LINE
  },
...
```

This is much like in Angular v11 where the `npm run lint` script was provided by default on a new project and I use that command in certain CI/CD pipelines so am now just adding it back manually on new v12 apps.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.23.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.26.0` |
| `node`                             | `14.17.0` |

```sh
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Thanks @MitchellCash, should be straightforward to add, would you like to try submitting a PR for this to the `@angular-eslint/schematics` package?
