### ISSUE TITLE
Angular 12 workspace: Failed to load config "../../.eslintrc.json" to extend from

### ISSUE THREAD

**Issue by prabh-62** [angular-eslint/angular-eslint#462]
**Description and reproduction of the issue**

When creating an angular 12 workspace, `@angular-eslint/schematics@12.0.0` schematics incorrectly writes `eslintrc.json`

```sh
❯ npx @angular/cli@12 new web-apps --create-application false --strict
❯ cd web-apps
❯ yarn ng g app command-center
❯ yarn ng add @angular-eslint/schematics
❯ yarn ng lint
```
```log
Linting "command-center"...
An unhandled exception occurred: Failed to load config "../../.eslintrc.json" to extend from.
Referenced from: /Users/<username>/dev/web-apps/projects/command-center/.eslintrc.json
```
<img width="1022" alt="angular_12_eslint_error" src="https://user-images.githubusercontent.com/13006107/118370136-57df0700-b574-11eb-9a60-de24dce925a2.png">

**Versions**
```sh
# yarn ng version:
Angular CLI: 12.0.0
Node: 16.1.0
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

```
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by metaloha** [comment]
Same issue here. The generated `.eslintrc.json` file in a project tries to refer to a root level file to extend from (`../../.eslintrc.json`) which isn't created.

In my case, I created an application in the `/projects` folder instead of using the default `/app` location for a single project.

**Comment by JamesHenry** [comment]
I was not familiar was this workflow and how the Angular CLI completely changes it's mind on project creation when you do things this way round!

There is no root level project in your workflow, so the root level config is never generated.

Clearly the workarounds for now are:
- Let the Angular CLI create the root project for you initially
- Create the root `.eslintrc.json` yourself

But we will need to update the assumptions in angular-eslint to fully address this

**Comment by prabh-62** [comment]
@JamesHenry What would be the next steps if @angular/cli workspace with multiple projects needs to be supported?

**Comment by JamesHenry** [comment]
@prabh-62 Have you followed the guidance here? https://github.com/angular-eslint/angular-eslint#using-eslint-by-default-when-generating-new-projects-within-your-workspace

Once you have used one of the workarounds for the root, you can just use angular-eslint to generate any subsequent projects

**Comment by Blackbaud-SteveBrush** [comment]
Stupid question: what would an ideal root-level `.eslintrc.json` file look like in this scenario (blank workspace with multiple projects)?

**Comment by prabh-62** [comment]
Root `.eslintrc.json`
```json
{
    "root": true,
    "ignorePatterns": ["projects/**/*"],
    "plugins": [],
    "overrides": [
      {
        "files": ["*.ts"],
        "parserOptions": {
          "project": ["tsconfig.json"],
          "createDefaultProgram": true
        },
        "extends": [
          "plugin:@typescript-eslint/recommended",
          "plugin:@typescript-eslint/recommended-requiring-type-checking",
          "plugin:@angular-eslint/all"
        ],
        "rules": {
          "@angular-eslint/sort-ngmodule-metadata-arrays": "off"
        }
      },
      {
        "files": ["*.html"],
        "extends": ["plugin:@angular-eslint/template/all"],
        "rules": {
          "@angular-eslint/template/i18n": "off"
        }
      }
    ]
  }
  
```


Project specific eslint: `projects/dashboard/.eslintrc.json`
```json
{
  "extends": "../../.eslintrc.json",
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "projects/dashboard/tsconfig.app.json",
          "projects/dashboard/tsconfig.spec.json"
        ],
        "createDefaultProgram": true
      },
      "rules": {
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "td",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "td",
            "style": "kebab-case"
          }
        ]
      }
    },
    {
      "files": ["*.html"],
      "rules": {}
    }
  ]
}
```

**Comment by guillermoarellano** [comment]
@prabh-62 You are a wonderful soul and magnificent individual. Your answer helped me tremendously. Thank you!

**Comment by Francesco-Manicardi** [comment]
**Here's the intended way to install eslint in a multi project workspace setup:**

in root directory, run
`ng add @angular-eslint/schematics
`
For each child project, run:
`ng g @angular-eslint/schematics:add-eslint-to-project <your-project-name-goes-here>`

**Comment by sagrawal31** [comment]
@Francesco-Manicardi, seems the 2nd command is not needed. It's automatically doing it-

![image](https://user-images.githubusercontent.com/1804514/153847044-3b9d3c2d-5bb4-42f3-b69f-7ec75718a0d8.png)

So the root `.eslintrc.json` is still not being created automatically.

**Comment by JamesHenry** [comment]
Thanks a lot for covering the workarounds on this folks, I'm pleased to say that the tooling will now do the right thing in the `--create-application=false` case automatically as of `13.2.0`

**Comment by guillermoarellano** [comment]
Outstanding! Thank you @JamesHenry.

**Comment by sagrawal31** [comment]
Amazing, thanks!
