### ISSUE TITLE
[eqeqeq] schematic added non-existant rule to .eslintrc.json file

### ISSUE THREAD

**Issue by trdyer** [angular-eslint/angular-eslint#483]
I ran `ng g @angular-eslint/schematics:convert-tslint-to-eslint` with Angular 11.2.14 and it added 
```json
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {
        "@angular-eslint/template/eqeqeq": "error"
      }
    }
```
To my `.eslintrc.json` file.

and v4.3 of the @angular-eslint/* plugins.

When I run `ng lint` I get the following error
`  1:1  error  Definition for rule '@angular-eslint/template/eqeqeq' was not found  @angular-eslint/template/eqeqeq`

Updating the package to v12 does add the rule. Should the schematic be installing v12, or should it not be adding the rule for the template plugin?

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.16.1` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `7.6.0` |
| `node`                             | `14.15.1` |

```sh
Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    10.1.3
@angular/cli                    11.2.13
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.13
@schematics/update              0.1102.13
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.5

```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by antch** [comment]
The rule clearly doesn't exist in v4.x -- it seems that it shouldn't be added during the migration.

**Comment by JamesHenry** [comment]
@trdyer I'm really sorry about this issue and that it couldn't be resolved at the time. With the tooling having moved on so much since then, it won't be practical to investigate the exact circumstances around this issue.

Please feel free to open a new issue if you ever encounter anything like this in the future and I'll be sure to get back to you as soon as possible.

Sorry again!
