### ISSUE TITLE
eslint alternate configurations, similar to --tslintConfig

### ISSUE THREAD

**Issue by sam-s4s** [angular-eslint/angular-eslint#508]
**Description and reproduction of the issue**

I have an angular directory with 6 projects. Each one has the standard 
```
"architect": {
    "lint": {
        "builder": "@angular-eslint/builder:lint",
        "options": {
            "lintFilePatterns": [
                "./zzz//**/*.ts",
                "./zzz//**/*.html"
            ]
        }
    }
}
```

When I run `ng lint zzz` it works fine. No problems here.

But I'm just upgrading from tslint to eslint, and tslint had the ability to use alternate configurations, and I can't find an equivalent for angular-eslint.

eg. for tslint you could do this...
```
ng lint zzz --tslintConfig tslint.alt.json
```
and it would use the "tslint.alt.json" configuration, instead of the default "tslint.json" config.

I cannot find any mechanism  to do this in angular-eslint.

I believe normal eslint has a `--config` option - but I don't think this has been hooked up to ng lint / angular-eslint ?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint       `        | `12.0.0` |
| `@typescript-eslint       `        | `4.23.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.27.0` |
| `node`                             | `14.17.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.5.5
typescript                      4.2.4
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@sam-s4s the schema for the builder is available here: https://github.com/angular-eslint/angular-eslint/blob/master/packages/builder/src/schema.json the option you are looking for is called `eslintConfig`.

I have a docs website in the works, that will pull in the schema to show off all the options too.

Thanks!

**Comment by sam-s4s** [comment]
haha, I should have guessed that! :D

Also I note that the param has changed from `--eslintConfig` to `--eslint-config`.

Thank you!
