### ISSUE TITLE
@angular-eslint/template-parser requires Angular v12 even when using @angular-eslint/schematics@4.3.0.

### ISSUE THREAD

**Issue by BrunnerLivio** [angular-eslint/angular-eslint#532]
**Description and reproduction of the issue**

1. Create an Angular 11 project `ng new`
2. `ng add @angular-eslint/schematics@4.3.0`
3. You'll receive the following error:

```
$ ng add @angular-eslint/schematics

ℹ Using package manager: npm
✔ Found compatible package version: @angular-eslint/schematics@4.3.0.
✔ Package information loaded.
✖ Package installation failed: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @angular/compiler@12.0.3
npm ERR! node_modules/@angular-eslint/schematics/node_modules/@angular/compiler
npm ERR!   peer @angular/compiler@">= 12.0.0 < 13.0.0" from @angular-eslint/template-parser@12.1.0
npm ERR!   node_modules/@angular-eslint/schematics/node_modules/@angular-eslint/template-parser
npm ERR!     peer @angular-eslint/template-parser@"*" from @angular-eslint/eslint-plugin-template@4.3.0
npm ERR!     node_modules/@angular-eslint/schematics/node_modules/@angular-eslint/eslint-plugin-template
npm ERR!       @angular-eslint/eslint-plugin-template@"4.3.0" from @angular-eslint/schematics@4.3.0
npm ERR!       node_modules/@angular-eslint/schematics
npm ERR!         dev @angular-eslint/schematics@"4.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@">= 11.2.0 < 12.0.0" from @angular-eslint/eslint-plugin-template@4.3.0
npm ERR! node_modules/@angular-eslint/schematics/node_modules/@angular-eslint/eslint-plugin-template
npm ERR!   @angular-eslint/eslint-plugin-template@"4.3.0" from @angular-eslint/schematics@4.3.0
npm ERR!   node_modules/@angular-eslint/schematics
npm ERR!     dev @angular-eslint/schematics@"4.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See xxx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!    xxx/.npm/_logs/2021-06-07T14_05_32_449Z-debug.log
Package install failed, see above.
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/template-parser`  | `12.1.0` |
| `ESLint`                           | `none` |
| `node`                             | `12.8.13` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.14
Node: 12.18.3
OS: darwin x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.0.7
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by BrunnerLivio** [comment]
It seems like the issue is caused because it pulls the wrong version of `@angular-eslint/template-parser`. I haven't figured out a way I can force `ng add` to use the appropriate version

**Comment by timdeschryver** [comment]
Hi @BrunnerLivio, have you tried using `ng add @angular-eslint/schematics@4.3.0`?
I might be wrong here, but I suppose v12 is compatible with angular v12, but it isn't backwards compatible with angular v11. That's why we'll have to install v4.3.0.
Again, I might be wrong 😅.

**Comment by P4** [comment]
I found a workaround of manually installing the right version of `@angular-eslint/template-parser` before running `ng add`:
```
npm i -D @angular-eslint/template-parser@4
```

**Comment by BrunnerLivio** [comment]
@timdeschryver 
> Hi @BrunnerLivio, have you tried using ng add @angular-eslint/schematics@4.3.0?

That is exactly what I did! Sorry wrote the wrong command above (corrected now)
You can see it in the logs above - here it uses the correct version:

```
npm ERR! peer @angular/compiler@">= 11.2.0 < 12.0.0" from @angular-eslint/eslint-plugin-template@4.3.0
```

... but then it tires to resolve the template parser incorrectly (v12.1.0)

```
npm ERR!   peer @angular/compiler@">= 12.0.0 < 13.0.0" from @angular-eslint/template-parser@12.1.0
```

--- 

@P4 perfect!! That fixes it.


For me this workaround is fine -- I'll keep it open and let you choose what actions take from this. Feel free to close if you see this as a non-issue though.

**Comment by JamesHenry** [comment]
Lerna does not help us with updating peerDependencies when we version the packages in our monorepo. Therefore the relationship in peerDependencies uses `*` to ensure we don't have to update this manually before each release.

You can see this in your logs above:
`peer @angular-eslint/template-parser@"*" from @angular-eslint/eslint-plugin-template@4.3.0`

Therefore because of the changes in npm v7 regarding peerDependencies and because of `*` I think it is pulling the latest package (v12). This then makes sense for everything else you are seeing.

Does anybody have any alternative suggestions for how to handle this so that multiple major versions are supported simultaneously without the need for manual package.json maintenance as part of releases?

P.S. Why are y'all starting brand new projects with a previous major version of Angular? 😅

**Comment by BrunnerLivio** [comment]
@JamesHenry 

> Does anybody have any alternative suggestions for how to handle this so that multiple major versions are supported simultaneously without the need for manual package.json maintenance as part of releases?

It's maybe a too-obvious solution, but changing [this section in the docs](https://github.com/angular-eslint/angular-eslint#quick-start-with-angular-before-v12) to include the solution above would work 😅

It's just a bit annoying to maintain that, since that section will need to be updated after every major release - but for now it would work. 🤷 


> P.S. Why are y'all starting brand new projects with a previous major version of Angular? 😅

I am not working on a new project & migrating to v12 is not possible yet since there is still a dependency not upgraded :)

**Comment by leolio86400** [comment]
Made a branch with a fix for this one, would be great if we could get it in.

**Comment by JamesHenry** [comment]
I'm very sorry for the long delay on this, I manually cut 4.3.1 which pins the template-parser peer dep to between 4 and 12 per @leolio86400 PR and I tested it with a new Angular 11 workspace using Node 14 and npm 7.

**Comment by amit2206** [comment]
Hi, I am also getting same error with my angular version 13, I tried above suggestion (npm i -D @angular-eslint/template-parser@12), but getting following error-
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: sdwan-ui-refactor@0.0.0
npm ERR! Found: @angular-devkit/build-angular@12.0.1
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^13.2.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"^13.2.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.3.9
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.6
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^13.2.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/guest/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guest/.npm/_logs/2022-05-18T20_12_19_427Z-debug.log

Any suggestion please ?
