### ISSUE TITLE
An unhandled exception occurred: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dana-ngis** [angular-eslint/angular-eslint#533]
I am getting An unhandled exception occurred: Cannot read property '0' of undefined error when I run ng lint in my application and the error is happening whenever I have a trailing-space in my code.

That is fine and I want to get a linting error when there is trailing space in the code but the issue is I am getting this problem even on the comented code in my HTML template as well as when I break down a line of HTML element to separate lines I am getting that error as well.
This problem starts happening once I upgrade my project Angular version to version 12.
 
This is my root level .eslintrs.json file
```
{
  "root": true,
  // "plugins": ["@typescript-eslint/eslint-plugin"],
  "rules": {
    "@typescript-eslint/explicit-function-return-type": "error",
    "no-console": "warn",
    "no-empty": "off",
    "no-var": "error",
    "prefer-arrow-callback": "error",
    "no-trailing-spaces": [
      "error",
      {
        "ignoreComments": true
      }
    ],
    "semi": "error",
    "quotes": "warn"
  }
}
```
So as you can see I include no-trailing-space with the options of ignoreComments but this is not picking up the comments in my HTML template.
Here is the client-side .eslintc.json that I have
```
 {
  "root": false,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "error",
          {
            "prefix": "app",
            "style": "kebab-case",
            "type": "element"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "prefix": "app",
            "style": "camelCase",
            "type": "attribute"
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}
```
Here is two example of when that error is happening
![image](https://user-images.githubusercontent.com/70558260/121293955-219c6980-c91f-11eb-9437-40ceedb36f58.png)
![image](https://user-images.githubusercontent.com/70558260/121294286-b3a47200-c91f-11eb-8b37-f996d7d7d652.png)

and here is the version of all packages that I have
![image](https://user-images.githubusercontent.com/70558260/121294160-80fa7980-c91f-11eb-8d4f-67cd212c7f39.png)

**Comment by rafaelss95** [comment]
@dana-ngis Please, try to follow the issue template the next time. For example, with this I don't know what version of `@angular/eslint*` you're using.

<hr>

That being said, if I understand your problem correctly:

> So as you can see I include no-trailing-space with the options of ignoreComments but this is not picking up the comments in my HTML template.

... are you expecting that `no-trailing-space` lint html files? If so, that would not work. You could get more context on [this issue](https://github.com/angular-eslint/angular-eslint/issues/202).

I don't know if the config above is complete, but you may want add `"overrides": { "files": ["*.ts"] }` to the root .eslintrc.json as you can see in https://github.com/angular-eslint/angular-eslint#seriously-move-mostly-all-configuration-into-overrides.

**Comment by JamesHenry** [comment]
@dana-ngis Everything regarding ESLint configuration for Angular projects is comprehensively documented in the README. Please read: https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration-itself and https://github.com/angular-eslint/angular-eslint#seriously-move-mostly-all-configuration-into-overrides

Those sections explain how you cannot apply rules to the root level of a config as you do above when Angular templates are involved. You have to differentiate between TS/JS and HTML files - they require entirely different parsers/plugins/rules.

When you apply things at the root level you are logically telling ESLint - these things _all_ apply to _everything_ I am linting. Overrides allow you to instead say "these pieces just for these files, these other pieces just for these files".

Again please have a read of those sections and let us know if anything is unclear or could be added.
