### ISSUE TITLE
Parsing fatal error in Visual Studio 2019

### ISSUE THREAD

**Issue by Bykiev** [angular-eslint/angular-eslint#536]
Hi, I'm migrating angular 11 project from tslint. Almost all is working as expected. except angular plugins: all angular linting rules not working and getting parsing fatal error on the first line of ts files (first import statement). I'm using in-built VS 2019 (16.10.1) linting and I'm not sure the issue with angular-eslint plugins or Visual Studio.

I've not specified Node JS version, because Visual Studio 2019 internally using Node JS 12.18.4 for JS and TS features (IntelliSense, linting and etc)

Error message:  Error(ESLint) fatal-error Error in ESLint during analysing (It's an approximate translation). 

eslintrc.json:
```
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module",
        "project": [
          "tsconfig.app.json"
        ],
        "createDefaultProgram": true
      },
      "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "error",
          {
            "prefix": "app",
            "style": "kebab-case",
            "type": "element"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "prefix": "app",
            "style": "camelCase",
            "type": "attribute"
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}
```

tsconfig.app.json:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "baseUrl": "./",
    "module": "es2020",
    "target": "es5",
    "types": [],
    "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ]
    }
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": true,
    "enableIvy": true
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "target": "es2018",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "esnext",
      "dom"
    ],
    "plugins": []
  }
}

```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `4.3.0`  |
| `@typescript-eslint/parser`        | `4.16.1` |
| `ESLint`                           | `7.6.0` |
| `node`                             | `X.Y.Z` |

*ng version ouput*

```
Angular CLI: 11.2.14
Node: 15.4.0
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.0.7
```

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Sorry you are having trouble but why remove the issue template contents we’ve provided for you?

Help us to help you. You are missing important information such as your angular package versions and node environment that the were requested by the template.

We will definitely need to see what error you are getting to begin to consider what might be wrong.

**Comment by Bykiev** [comment]
> Sorry you are having trouble but why remove the issue template contents we’ve provided for you?
> 
> Help us to help you. You are missing important information such as your angular package versions and node environment that the were requested by the template.
> 
> We will definitely need to see what error you are getting to begin to consider what might be wrong.

Sorry about it, I'm using angular 11 and I didn't specified Node version because I have not it in project dependencies, as I can see VS 2019 internally using Node 12.18.4.0

**Comment by JamesHenry** [comment]
@Bykiev Angular has a number of packages which are relevant, and we’ve seen in the past how discrepancies between them can lead to issues.

Therefore please provide the full output of :

npx ng version

…as per the template.

Additionally, you still haven’t actually provided the error message and/or stack trace you are encountering

**Comment by Bykiev** [comment]
@JamesHenry, thank you, I've modified my first message, hope it's ok now

**Comment by JamesHenry** [comment]
I’m sorry but the error message seems like something that Visual Studio is giving you, not ESLint.

> Error message: Error(ESLint) fatal-error Error in ESLint during analysing (It's an approximate translation).

Please can you try and see if the ESLint extension within Visual Studio has some kind of output you can find? Eg in VSCode the ESLint extension logs can found in the Output tab of the terminal view.

Please can you also share what happens when you run linting from the command line for the same project rather in Visual Studio?

**Comment by Bykiev** [comment]
@JamesHenry, unfortunately I didn't find any way to view linting log in Visual Studio, because it's not an extension, it's built-in VS. 
I've tried via console (ng lint) and it's working as expected.

**Comment by JamesHenry** [comment]
In which case I’m afraid this sounds very specific to Visual Studio and I can only suggest you try and enlist the help of other users of that IDE for how to troubleshoot further.

If you are able to find out more information which points to an issue with this toolset then please feel free to reopen.

**Comment by Bykiev** [comment]
Thank you for your time, I'll continue investigate the issue

**Comment by JamesHenry** [comment]
Best of luck!
