### ISSUE TITLE
Cannot import RuleTester from @angular-estlint/utils 

### ISSUE THREAD

**Issue by ramarivera** [angular-eslint/angular-eslint#537]
I recently started writing custom ESlint rules for Angular projects, before realizing that writing rules for templates was even possible, which got me curious on how to do that.

After reviewing this repo and the code for the template plugin, I ran into issues when trying to test my rules.

As mentioned and discussed in this issue #113, the package `@angular-estlint/utils` is a private package.

What would be the way for template rule authors to test their rules with the current private status of the package? Or should we submit our rules to this monorepo? For some generic rules (e.g. `ensure-buttons-have-type-attribute`) it might make sense, but not for every project custom rule.

Thanks in advanced!

**Comment by rafaelss95** [comment]
IMHO if we really want to make it public, we should rename it before as this package deals exclusively with tests, so probably `@angular-eslint/testing` is a better name. What do you think, @JamesHenry?

**Comment by JamesHenry** [comment]
It currently deals exclusively with tests, but I don't think we need to limit it to that and having it be a catch all for useful utilities would be valuable I think.

I will expose the package in the next minor version, PR incoming

**Comment by JamesHenry** [comment]
@ramarivera Sorry that this took a long time to be resolved, I'm delighted you are up and running with writing your own rules

**Comment by ramarivera** [comment]
Hey @JamesHenry no worries, thanks a lot for making it available :D 
It was a bit of trial and error to get the setup working, but once I got it (plus the RuleTester), writing custom rules was amazingly simple, kudos to you
