### ISSUE TITLE
[prefer-on-push-component-change-detection] Throws TypeError while typing

### ISSUE THREAD

**Issue by TomTomB** [angular-eslint/angular-eslint#553]
**Description and reproduction of the issue**

Adding the following rule to my eslint config throws an `TypeError: Cannot read property 'type' of undefined` error while typing.

```JSON
{
  "rules": {
    "@angular-eslint/prefer-on-push-component-change-detection": ["error"]
  }
}
```
Note here: The uncompleted `ChangeDetectionS` is on purpose. Typing here will throw the error on every keystroke.
```TS
@Component({
  selector: 'app-test',
  template: `<p>Test</p>`,
  styles: [``],
  changeDetection: ChangeDetectionS
})
export class TestComponent {}

```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `~12.2.0` |
| `@typescript-eslint/parser`        | `4.27.0` |
| `ESLint`                           | `7.28.0` |
| `node`                             | `14.17.3` |

```sh
Angular CLI: 12.0.5
Node: 14.15.5
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic     
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.4
@angular/fire                   6.1.5
@nguniversal/builders           12.0.2
@nguniversal/express-engine     12.0.2
@schematics/angular             12.0.5
ng-packagr                      12.0.6
rxjs                            6.6.7
typescript                      4.2.4


```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by TomTomB** [comment]
After updating eslint to `7.29.0` the issue seems to be fixed. But I doubt that was the problem. Rather some corrupted node modules, I guess. Anyways, closing this.

**Comment by rafaelss95** [comment]
Hey @TomTomB, would you mind sharing the error stack trace? Maybe it's worth taking a look to see if it's actually a real problem, and if so, it would affect not just what you mentioned, but some rules that look the decorator's arguments.
