### ISSUE TITLE
FR: input-event-group

### ISSUE THREAD

**Issue by AvshT** [angular-eslint/angular-eslint#556]
In order to keep the template code effective and readable, I'm suggesting this rule, that will warn if there is misordering between input and events in the html template:

**<some-componenet (someEvent2)="aaaEvent2()" [someInput1]="aaa" (someEvent1)="aaaEvent1()" [someInput2]="bbb" >** 
will rise the warning - "inputs & events should be grouped"
**<some-componenet [someInput1]="aaa"  [someInput2]="bbb" (someEvent2)="aaaEvent2()" (someEvent1)="aaaEvent1()"  >**

**Comment by rafaelss95** [comment]
Hey @AvshT, I guess this is the same thing requested in #127, so I'm closing this. Feel free to comment if not.
