### ISSUE TITLE
NPM package does not link to repository

### ISSUE THREAD

**Issue by dpraul** [angular-eslint/angular-eslint#57]
Hi there! I noticed that the NPM releases for the packages here don't link back to the code repository. For example: [@angular-eslint/eslint-plugin](https://www.npmjs.com/package/@angular-eslint/eslint-plugin) does not have any repository information on the right sidebar. This would be beneficial as it adds nice statistics to the NPM page, and allows dependency-update bots like [dependabot](https://dependabot.com/) or [greenkeeper](https://greenkeeper.io/) to automatically pull information into the pull requests they create.

I believe this would be fixed by adding the [`repository` key to the `package.json`](https://docs.npmjs.com/files/package.json#repository). By example, Babel does something similar in [their monrepo](https://github.com/babel/babel/blob/3fc904e1d4674effa0b948b454ce8789f5d4c089/packages/babel-core/package.json#L12) and it [works perfectly on the NPM page](https://www.npmjs.com/package/@babel/core).

**Comment by JamesHenry** [comment]
Thanks @dpraul, would you like to submit a PR for this?

**Comment by dpraul** [comment]
Sure, I'll see what I can do
