### ISSUE TITLE
Readme for old angular projects correct?

### ISSUE THREAD

**Issue by Razzeee** [angular-eslint/angular-eslint#572]
The readme for https://github.com/angular-eslint/angular-eslint#quick-start-with-angular-before-v12 seems to be a copy and paste from the one before. So it seems to want us to create a new workspace, which doesn't make much sense, if I want to update a project that I already have?

**Comment by JamesHenry** [comment]
Not everyone is creating new projects with the version 12 of Angular CLI yet, unfortunately. All the documentation around creating new projects is grouped together.

All the information around converting existing projects is also documented: https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint
