### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by BO41** [angular-eslint/angular-eslint#59]
since v23, many `*.ts` files throw
`0:0  error  Parsing error: Cannot read property 'start' of undefined`

**Comment by JamesHenry** [comment]
Are you using version 23 of all the packages including the builder? It’s important that they are all updated together.

If this were generally an error I would’ve expected the integration tests to produce this result as well, so I would think that this is a configuration issue.

Please share your configuration and steps to reproduce

**Comment by BO41** [comment]
my bad, had the wrong parser in the `"*.component.ts"` override
