### ISSUE TITLE
Angular 12 : Failed to load config "../../.eslintrc.json" from a scoped library

### ISSUE THREAD

**Issue by meriturva** [angular-eslint/angular-eslint#593]
Step to reproduce issue:

- ng new eslint-library
- cd eslint-library
- ng add @angular-eslint/schematics
- ng g library test
- ng lint test

Everything is ok as output but if you now create a new library with a scope:

- ng g library @meriturva/test
- ng lint @meriturva/test

you will see: 

```
Linting "@meriturva/test"...
An unhandled exception occurred: Failed to load config "../../.eslintrc.json" to extend from.
Referenced from: D:\Projects\daButtare\eslint-library\projects\meriturva\test\.eslintrc.json
See "C:\Users\diego\AppData\Local\Temp\ng-siZZqi\angular-errors.log" for further details.
```

Version:
angular 12.1.1

"@angular-eslint/builder": "12.2.2",
    "@angular-eslint/eslint-plugin": "12.2.2",
    "@angular-eslint/eslint-plugin-template": "12.2.2",
    "@angular-eslint/schematics": "12.2.2",
    "@angular-eslint/template-parser": "12.2.2",

**Comment by guillermoarellano** [comment]
I am having the same issue.

**Comment by guillermoarellano** [comment]
@meriturva I solve this issue by following the steps described by @prabh-62 on this issue link: <https://github.com/angular-eslint/angular-eslint/issues/462#issuecomment-858073819>. 

Hopefully, this helps others.

**Comment by meriturva** [comment]
Same issue with version "@angular-eslint": "12.3.1"

Actually, there is no workaround, I mean, you have just to adjust extends path on eslintrc.json file created.

Please run commands:

- ng g library @meriturva/test
- ng lint @meriturva/test

to replicate error.

**Comment by JamesHenry** [comment]
Thanks folks, this should now be supported as of `13.2.0`
