### ISSUE TITLE
Enhancement: automatically update every installed @angular-eslint package during `ng update @angular-eslint/schematics`

### ISSUE THREAD

**Issue by alebx** [angular-eslint/angular-eslint#596]
When I'm trying to update the @angular-eslint dependencies via @angular-eslint/schematics the dependencies are not updated.

**Description and reproduction of the issue**
```sh
ng update @angular-eslint/schematics
Using package manager: 'npm'
Collecting installed dependencies...
Found 99 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-eslint/schematics @ "12.3.0" (was "12.2.2")...
  UPDATE package.json (9173 bytes)
✔ Packages successfully installed.

npm outdated               
Package                                 Current  Wanted  Latest  Location
@angular-eslint/builder                  12.2.2  12.3.0  12.3.0  webapp
@angular-eslint/eslint-plugin            12.2.2  12.3.0  12.3.0  webapp
@angular-eslint/eslint-plugin-template   12.2.2  12.3.0  12.3.0  webapp
@angular-eslint/template-parser          12.2.2  12.3.0  12.3.0  webapp
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/schamtics`          | `12.2.2` |
| `ESLint`                           | `7.30.0` |
| `node`                             | `14.17.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
ng-packagr                      12.1.2
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by nsgundy** [comment]
Same here, updating from `12.2.0` to `12.3.1`.

**Comment by JamesHenry** [comment]
Thanks folks I've updated the description to better reflect the ask here. We've never implemented a feature for this but I think it's a good idea and we can add it.

**Comment by dushkostanoeski** [comment]
This should work the same way `ng update @angular/core` works

**Comment by JamesHenry** [comment]
Thanks folks, this has been in addressed in the v13 prereleases so will be the case with every version going forward

**Comment by jasonhulbert** [comment]
> still not working @angular-eslint/schematics@latest only updates the schematics and not other related eslint dependencies am I missing something here?

Works fine for me:

```
npx @angular/cli update @angular-eslint/schematics@^16
```

**Comment by mcvendrell** [comment]
Hi, I have the same issue. I tried:

`npx @angular/cli update @angular-eslint/schematics@latest` (in my case, 18)
`ng update @angular-eslint/schematics@18`

but doesn't update other related eslint dependencies.

I finally did it manually.

**Comment by titocr** [comment]
This worked for me just now:
npx ng update @angular-eslint/*@^17

Output was:
Using package manager: npm
Collecting installed dependencies...
Found 60 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-eslint/builder @ "17.5.3" (was "17.3.0")...
    Updating package.json with dependency @angular-eslint/eslint-plugin @ "17.5.3" (was "17.3.0")...
    Updating package.json with dependency @angular-eslint/eslint-plugin-template @ "17.5.3" (was "17.3.0")...
    Updating package.json with dependency @angular-eslint/schematics @ "17.5.3" (was "17.3.0")...
    Updating package.json with dependency @angular-eslint/template-parser @ "17.5.3" (was "17.3.0")...
UPDATE package.json (4766 bytes)
✔ Packages successfully installed.

**Comment by JamesHenry** [comment]
Folks please don't comment on a very old closed issue. Clearly this _is_ working in the vast majority cases, otherwise there would be a lot more activity.

Besides this is an Angular CLI feature that angular-eslint simply hooks into by specifying certain metadata in the `package.json` (https://github.com/angular-eslint/angular-eslint/blob/8d0c6f31fbfc6b001b6a274ccf3cd87e93698e04/packages/schematics/package.json#L21-L34), so if it isn't working at this point it's really an Angular CLI complaint.

Note that dependencies such as `eslint` and `typescript-eslint` that are not maintained in this repo will not be automatically bumped on every single `ng update`, only on certain majors and significant changes (when I manually add migrations into this project to do it).
