### ISSUE TITLE
Error coming while I exec- ng lint - "PropertyNameExpected in JSON at position 3855" after I updated @angular-eslint/builder from 12.2.0 to 12.3.1

### ISSUE THREAD

**Issue by ErVishalM** [angular-eslint/angular-eslint#608]
Hi,

An error is coming when I run command `ng lint` after I updated `@angular-eslint/builder` from 12.2.0 to 12.3.1.
![image](https://user-images.githubusercontent.com/43669644/126974263-ecfcb44e-c55d-467b-a03a-fa6b3eb03509.png)

![image](https://user-images.githubusercontent.com/43669644/126974289-550b85ca-3c1f-44c0-bca4-c244ab9cc51d.png)

This command is working in `@angular-eslint/builder` 12.2.0 version but when I update it to 12.3.1. it throws upper attached error.
Please check and advise.
Thanks.

**Comment by JamesHenry** [comment]
@ErVishalM Please can you provide your angular.json? That is what it is likely erroring on

**Comment by ErVishalM** [comment]
Hi, Sorry for little delay.
Here is my angular.json file

`{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "myProject": {
            "projectType": "application",
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss",
                    "skipTests": true,
                    "inlineStyle": true
                },
                "@schematics/angular:application": {
                    "strict": true
                }
            },
            "root": "",
            "sourceRoot": "src",
            "prefix": "app",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist/myProject",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "polyfills": "src/polyfills.ts",
                        "tsConfig": "tsconfig.app.json",
                        "assets": [
                            "src/favicon.ico",
                            "src/assets",
                            "src/app/mylibrary/mysharedimages",
                            "src/web.config"
                        ],
                        "styles": [
                            "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
                            "src/styles.scss",
                            "src/app/mylibrary/mysharedstyle/myopensansfont.css",
                            "src/app/mylibrary/mysharedstyle/mygridui.scss",
                            "src/app/mylibrary/mysharedstyle/mypageui.scss"
                        ],
                        "scripts": [
                            "./node_modules/jquery/dist/jquery.min.js",
                            "./node_modules/jquery-ui-dist/jquery-ui.js"
                        ],
                        "allowedCommonJsDependencies": [
                            "xlsx"
                        ],
                        "vendorChunk": true,
                        "extractLicenses": false,
                        "buildOptimizer": false,
                        "sourceMap": true,
                        "optimization": false,
                        "namedChunks": true
                    },
                    "configurations": {
                        "production": {
                            "fileReplacements": [{
                                "replace": "src/environments/environment.ts",
                                "with": "src/environments/environment.prod.ts"
                            }],
                            "baseHref": "/myProject/",
                            "optimization": true,
                            "outputHashing": "all",
                            "sourceMap": false,
                            "namedChunks": false,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "budgets": [{
                                    "type": "initial",
                                    "maximumWarning": "10Mb",
                                    "maximumError": "15mb"
                                },
                                {
                                    "type": "anyComponentStyle",
                                    "maximumWarning": "2kb",
                                    "maximumError": "4kb"
                                }
                            ]
                        },
                        "development": {}
                    },
                    "defaultConfiguration": "production",
                },
                "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {},
                    "configurations": {
                        "production": {
                            "browserTarget": "myProject:build:production"
                        },
                        "development": {
                            "browserTarget": "myProject:build:development"
                        }
                    },
                    "defaultConfiguration": "development"
                },
                "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                        "browserTarget": "myProject:build"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "main": "src/test.ts",
                        "polyfills": "src/polyfills.ts",
                        "tsConfig": "tsconfig.spec.json",
                        "karmaConfig": "karma.conf.js",
                        "assets": [
                            "src/favicon.ico",
                            "src/assets",
                            "src/app/mylibrary/mysharedimages",
                            "src/web.config"
                        ],
                        "styles": [
                            "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
                            "src/styles.scss",
                            "src/app/mylibrary/mysharedstyle/myopensansfont.css",
                            "src/app/mylibrary/mysharedstyle/mygridui.scss",
                            "src/app/mylibrary/mysharedstyle/mypageui.scss"
                        ],
                        "scripts": [
                            "./node_modules/jquery/dist/jquery.min.js",
                            "./node_modules/jquery-ui-dist/jquery-ui.js"
                        ]
                    }
                },
                "lint": {
                    "builder": "@angular-eslint/builder:lint",
                    "options": {
                        "lintFilePatterns": [
                            "src/**/*.ts",
                            "src/**/*.html"
                        ]
                    }
                },
                "e2e": {
                    "builder": "@angular-devkit/build-angular:protractor",
                    "options": {
                        "protractorConfig": "e2e/protractor.conf.js"
                    },
                    "configurations": {
                        "production": {
                            "devServerTarget": "myProject:serve:production"
                        },
                        "development": {
                            "devServerTarget": "myProject:serve:development"
                        }
                    },
                    "defaultConfiguration": "development"
                }
            }
        }
    },
    "defaultProject": "myProject",
    "cli": {
        "analytics": "5c78c5ea-91fc-4d9c-a7a9-0c0c0f23e358",
        "defaultCollection": "@angular-eslint/schematics"
    }
}`

**Comment by JamesHenry** [comment]
@ErVishalM You have a trailing comma after `"defaultConfiguration": "production",` - trailing commas are not allowed in JSON.

Please try removing that comma and running the command again

**Comment by ErVishalM** [comment]
Hi @JamesHenry Thank you very much it solved the problem 👏. 
It was not giving me error in previous version and in current version the error was not so descriptive for me to find out 😄
