### ISSUE TITLE
[semi] How to enforce semicolon rule?

### ISSUE THREAD

**Issue by thekhegay** [angular-eslint/angular-eslint#612]
```JSON
{
  "rules": {
    "semi": "off",
    "@typescript-eslint/semi": ["error"],
  }
}
```

Full eslintrc:
```JSON
{
    "root": true,
    "ignorePatterns": ["projects/**/*"],
    "overrides": [
        {
            "files": ["*.ts"],
            "parserOptions": {
                "project": ["tsconfig.*?.json", "e2e/tsconfig.json"],
                "createDefaultProgram": true
            },
            "extends": [
                "plugin:@angular-eslint/recommended",
                "plugin:@angular-eslint/template/process-inline-templates",
                "eslint:recommended",
                "plugin:@typescript-eslint/recommended",
                "plugin:@typescript-eslint/recommended-requiring-type-checking",
                "plugin:prettier/recommended"
            ],
            "rules": {
                "semi": "off",
                "@typescript-eslint/semi": ["error"],
                "@angular-eslint/component-class-suffix": [
                    "error",
                    {
                        "suffixes": ["Component", "Page"]
                    }
                ],
                "@angular-eslint/directive-selector": [
                    "error",
                    {
                        "type": "attribute",
                        "prefix": "gi",
                        "style": "camelCase"
                    }
                ],
                "@angular-eslint/component-selector": [
                    "error",
                    {
                        "type": "element",
                        "prefix": "gi",
                        "style": "kebab-case"
                    }
                ]
            }
        },
        {
            "files": [
                "*.html"
            ],
            "extends": [
                "plugin:@angular-eslint/template/recommended"
            ],
            "rules": {}
        },
        {
            "files": [
                "*.html"
            ],
            "excludedFiles": [
                "*inline-template-*.component.html"
            ],
            "extends": [
                "plugin:prettier/recommended"
            ],
            "rules": {
                "prettier/prettier": [
                    "error",
                    {
                        "parser": "angular"
                    }
                ]
            }
        }
    ]
}

```

**Comment by JamesHenry** [comment]
@thekhegay You are using prettier here, so your preference for semi-colons is already captured by that tool.

What is in your prettier configuration file?

**Comment by thekhegay** [comment]
@JamesHenry thank you for fast response. Here is my prettierrc:
```JSON
{
    "semi": true,
    "bracketSpacing": true,
    "trailingComma": "all",
    "singleQuote": true,
    "printWidth": 120,
    "tabWidth": 4,
    "useTabs": false,
    "endOfLine": "auto"
}

```

**Comment by JamesHenry** [comment]
Yeah so that `"semi": true,` should already be picked up by your `plugin:prettier/recommended` to turn any missing semi-colons into lint errors.

Are you not seeing that? Please could you paste an example of code which is not producing the result you want? (running ng lint and in the IDE?)

**Comment by thekhegay** [comment]
For example: 

```Typescript
set(key: string, value: string): void {
    if (isPlatformBrowser(this.pid)) {
        return localStorage.setItem(key, value) <--- here where error must be shown
    }
}
```

I'm using Webstorm, and there is no any errors.

**Comment by JamesHenry** [comment]
And what about when you run `ng lint` on the command line/CI?

**Comment by thekhegay** [comment]
Oh, ng lint gives errors:
```bash
error  Missing semicolon @typescript-eslint/semi
error  Insert `;` prettier/prettier
```

I think this issue is related with IDE.
Thank you :)

**Comment by JamesHenry** [comment]
Cool, yeah so you can see there you don't need the `@typescript-eslint/semi` rule in addition to prettier. You should just use prettier in your case.

In terms of why it is not working in webstorm, are you using `projects/` / do you have a monorepo by any chance?

It seems the behaviour regarding ESLint monorepos has been wonky for a while in WebStorm, I tracked down a number of issues relating to it.

Grouped under here: https://youtrack.jetbrains.com/issue/WEB-47135#focus=Comments-27-4419848.0-0

The good thing is, in a recent version of WebStorm (2020.3) they resolved a lot of the monorepo support issues by adding a configuration option for working directory.

All you need to do is set it to ./  as referenced on a number of those issue threads and everything works as it does in VSCode:

![image](https://user-images.githubusercontent.com/900523/127831013-01313e59-1f36-4635-beb8-73b90ee8468a.png)

**Comment by thekhegay** [comment]
@JamesHenry thank you for response!
Actually, I'm using 2021.2 version of WebStorm. And after update, all Preferences has reseted. ESLint was disabled for whole IDE. I'm turned on one, and all is working fine now.
Thank you, again!

**Comment by JamesHenry** [comment]
Ok great, thanks, I'll close this then
