### ISSUE TITLE
`banana-in-box` can be deprecated once new Angular compiler checks have auto-fixing

### ISSUE THREAD

**Issue by rafaelss95** [angular-eslint/angular-eslint#660]
According to https://github.com/angular/angular/issues/42966, the compiler will start complain about wrong syntax in `two-way binding`, like we already do in `banana-in-box` rule.

In fact, the check has already been implemented in https://github.com/angular/angular/pull/42984 (https://github.com/angular/angular/commit/d6411c27291b69f46b3b7f648d3445c9c4ba3a4a) and https://github.com/angular/angular/pull/43232 (https://github.com/angular/angular/commit/fc85fa85ba7400b8a9b8a34677c6ada8ad301676).

So, with this in mind, should the `banana-in-box` rule be deprecated? cc @JamesHenry

**Comment by JamesHenry** [comment]
Cool, good catch! Yeah looks like we should mark this as deprecated in v13 onwards

**Comment by JamesHenry** [comment]
FYI Joost from the Angular Team said that these compiler checks are still behind a flag so it’s not time to deprecate it yet

**Comment by JamesHenry** [comment]
Extended diagnostics are available as of Angular 13.2, but until autofixing gets implemented it really isn't a fully viable alternative to the current lint rule.

Autofixing tracked in https://github.com/angular/angular/issues/44941

**Comment by DerZyklop** [comment]
FYI: 
»_support to fix invalid banana in box_« [got merged](https://github.com/angular/angular/pull/47393#issuecomment-1259812423).

**Comment by JamesHenry** [comment]
I don't think it makes sense to press ahead with this.

Even in the newly released Angular v15 does not configured Extended Diagnostics for you, and for them to work you have to have opted into `strictTemplates` type checking, which we cannot rely on the user having done (source https://angular.io/extended-diagnostics)

Overall there are just too many moving pieces here to provide a seamless switchover for users, the vast majority of which will have no idea about Extended Diagnostics at all.

The minority of power users who want to switch over from the lint rule to the Extended Diagnostic can do so by simply disabling the rule in their ESLint config and wiring up the necessary tsconfig config per the above link.

We can potentially revisit this if Angular switches its approach to Extended Diagnostics in the future and sets all users up with them by default.
