### ISSUE TITLE
@angular-eslint/eslint-plugin is disabling the no-unreachable rule of eslint

### ISSUE THREAD

**Issue by jlabaj** [angular-eslint/angular-eslint#664]
unless I explicitely specify no-unreachable rule of eslint it does not take effect even if it is recommanded.
If I remove the @angular-eslint/eslint-plugin it works.

![image](https://user-images.githubusercontent.com/5179937/131860199-101c1ad2-26f9-4ec3-bcea-3b1a9290caf8.png)

**Comment by rafaelss95** [comment]
It isn't disable by `@angular/eslint` but by [**`plugin:@typescript-eslint/recommended`**](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts#L25). This rule is unnecessary as TS automatically give us a compiler error for unreachable code — see [Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAKAlIg3o3iBQeiATgKZQjFICMA3IXhAgM5wA2pAdG3AOaoByKKWZQB6WogD0UxAFUwZAIYQAFkoBGHREwAmpRPuHRSuzqgDsABgBMF9PgC+QA).

Related issue: https://github.com/typescript-eslint/typescript-eslint/issues/1041

**Comment by jlabaj** [comment]
@rafaelss95 ah ok, yeah unless I turn off the check because it delets my code: 
https://github.com/microsoft/vscode-eslint/issues/1325#event-5211159949
https://github.com/microsoft/vscode/issues/109530

**Comment by rafaelss95** [comment]
In the case you don't want it to be removed, IMHO the best option for you is to enable `no-unreachable` manually then.
