### ISSUE TITLE
ESLint 8 support

### ISSUE THREAD

**Issue by KeithGillette** [angular-eslint/angular-eslint#713]
**Description and reproduction of the issue**

`@angular-eslint/eslint-plugin` appears to be incompatible with the [recently released `eslint@8.0.0`](https://eslint.org/blog/2021/10/eslint-v8.0.0-released), as I receive the following error when attempting to lint after updating to it:
```sh
An unhandled exception occurred: Failed to load plugin '@angular-eslint' declared in 'clients/browser/.eslintrc.json » ../../.eslintrc.json#overrides[0]': Class extends value undefined is not a constructor or null
R
```

The relevant portion of `.eslintrc.json:`
```json
      "extends": [
        "eslint:recommended",
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:eslint-plugin-rxjs/recommended"
      ],
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `12.5.0` |
| `@typescript-eslint/parser`        | `5.0.0` |
| `ESLint`                           | `8.0.0` |
| `node`                             | `14.17.6` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 12.2.9
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 12.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
rxjs                            7.4.0
typescript                      4.3.5
```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
I think it is certainly to be expected that major changes to ESLint require major changes to these packages.

#715 is the tracking issue for v13 which will contain ESLint 8 support.

**Comment by JamesHenry** [comment]
v13.0.0 of angular-eslint has been released which contains ESLint 8 support
