### ISSUE TITLE
[template] New rule for spaces arround brackets and pipes

### ISSUE THREAD

**Issue by muuvmuuv** [angular-eslint/angular-eslint#775]
**Description and reproduction of the issue**

New rule to add spaces arround `{{` and `}}` and pipes.

```html
{{var|safeHtml}}
```

becomes

```html
{{ var | safeHtml }}
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `X.Y.Z` |
| `@angular-eslint/template-parser`         | `X.Y.Z` |
| `@typescript-eslint/parser`               | `X.Y.Z` |
| `ESLint`                                  | `X.Y.Z` |
| `node`                                    | `X.Y.Z` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @muuvmuuv, please see this document for a detailed write up of this project's philosophy on using a lint to enforce code formatting concerns: https://github.com/angular-eslint/angular-eslint/blob/master/docs/FORMATTING_RULES.md
