### ISSUE TITLE
Enhancement: Add ability to hide warnings from the output (a quiet option)

### ISSUE THREAD

**Issue by mikg2003** [angular-eslint/angular-eslint#78]
Eslint provides a `--quiet` option that results in only errors being output.  I'm sure some will say that you should just fix your warnings, but when conditions like "having ignored files" result in warnings, it'd be awfully nice to be able to hide those when looking for the error that's preventing your build from succeeding.

**Comment by JamesHenry** [comment]
I would happily accept a PR for this!
