### ISSUE TITLE
Package "@angular-eslint/schematics" has an incompatible peer dependency to "@angular/cli" (requires ">= 12.0.0 < 13.0.0", would install "13.0.1")

### ISSUE THREAD

**Issue by ErVishalM** [angular-eslint/angular-eslint#787]
Hi,

I was trying to update to angular 13 but I am getting this error when I am running below command - 
`npx @angular/cli@13 update @angular/core@13 @angular/cli@13`
Error- 
`Using package manager: 'npm'
Collecting installed dependencies...
Found 52 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-eslint/schematics" has an incompatible peer dependency to "@angular/cli" (requires ">= 12.0.0 < 13.0.0", would install "13.0.1").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\UserName\AppData\Local\Temp\ng-19mICN\angular-errors.log" for further details.`
  
Screenshot also attached for your ref.
  
![image](https://user-images.githubusercontent.com/43669644/140506790-4a9d3ba2-be9d-492a-bc54-ff59b55542c9.png)

Can you please help me how can I update to Angular 13?

**Comment by JamesHenry** [comment]
https://github.com/angular-eslint/angular-eslint/issues/715 it's the first pinned issue
