### ISSUE TITLE
Speed?

### ISSUE THREAD

**Issue by stonecourier** [angular-eslint/angular-eslint#788]
Our current project used tslint and we also used typescript-eslint/eslint-plugin as a secondary check. We have all the strict options turned on in our tsconfig. We are using Angular 12.

So our current build takes 7 and 1/2 minutes on dev-ops.

Switching to use angular eslint, the build time blows out to 19 minutes.

Another project goes from 13 minutes to around 30 minutes.

Is there something we are doing wrong? Any recommendations you could give?

**Comment by JamesHenry** [comment]
Hi @stonecourier, please do read the comprehensive write up on performance in the README: https://github.com/angular-eslint/angular-eslint#notes-on-performance

Once you have been through that and applied the learnings to your project you will hopefully find that you no longer have major issues. If you still do, feel free to open a new issue, but please do not disregard the issue templates and please provide far more information about your specific setup than you have here.
