### ISSUE TITLE
Document usage without `ng lint`

### ISSUE THREAD

**Issue by qkevinto** [angular-eslint/angular-eslint#79]
Some projects may be using this without Angular CLI, would be worth noting in the docs to remember to add `.component.html` file extension option to the `eslint` command, in the same vein as the existing notes regarding `vscode-eslint` usage:
```
eslint --config .eslintrc.js --ext .ts,.component.html
```

Had quite a bit of a head scratcher moment wondering why adding template rules configuration didn't actually do anything. 😅

**Comment by JamesHenry** [comment]
I would gladly accept a PR to document the use of this tooling with non Angular CLI setups!

**Comment by JamesHenry** [comment]
Looks like this was addressed already
