### ISSUE TITLE
wrong package version added to angular 13 project

### ISSUE THREAD

**Issue by autozoom** [angular-eslint/angular-eslint#796]
When you run `ng add @angular-eslint/schematics` to a brand new Angular 13 project, it adds @angular-eslint/schematics@1.2.0

**Comment by bibble235** [comment]
Same here 
iwiseman@OLIVER:bibble-demo-app $ ng add @angular-eslint/schematics@12.6.1 --force --legacy-peer-deps
ℹ Using package manager: npm
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

and using @12.6.1 gives

The package @angular-eslint/schematics@12.6.1 will be installed and executed.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bibble-mydemo-app@0.0.0
npm ERR! Found: @angular/cli@13.0.2
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"~13.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 12.0.0 < 13.0.0" from @angular-eslint/schematics@12.6.1
npm ERR! node_modules/@angular-eslint/schematics
npm ERR!   dev @angular-eslint/schematics@"12.6.1" from the root project

**Comment by nagkumar** [comment]
Also, it adds 12.6.1 NOT 13.x version 

```
    "@angular-eslint/builder": "^12.6.1",
    "@angular-eslint/schematics": "^12.6.1",
```

Hence ng lint fails with 

Linting "untitled2"...
```
An unhandled exception occurred: Failed to load plugin '@angular-eslint' declared in '.eslintrc.json#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: C:\Users\Raja Nagendra Kumar\WebstormProjects\untitled2\.eslintrc.json
See "C:\Users\RAJANA~1\AppData\Local\Temp\ng-1JrG9k\angular-errors.log" for further details.
```

**Comment by nagkumar** [comment]
`[error] TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (..untitled2\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Raja Nagendra Kumar\WebstormProjects\untitled2\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
`

complete log

**Comment by zeljkoantich** [comment]
Hitting the same isseeee on _Linux Mint 20 Cinnamon ( Ubuntu Release )_ .

After running `ng add @angular-eslint/schematics` i got:
```
ℹ Using package manager: npm
✔ Found compatible package version: @angular-eslint/schematics@1.2.0.
✔ Package information loaded.

The package @angular-eslint/schematics@1.2.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/tmp/ng-wNTZDG/angular-errors.log" for further details.
```

Got it resolved by using `ng add @angular-eslint/schematics@latest` instead.

**Comment by P1N2O** [comment]
Should probably use `ng add @angular-eslint/schematics@latest` for the time being.

Got it working without issues with "@angular/cli": "~13.0.2"

**Comment by bibble235** [comment]
This does work with @next Could not get it to work with @latest 

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 12.0.0 < 13.0.0" from @angular-eslint/schematics@12.6.1
npm ERR! node_modules/@angular-eslint/schematics
npm ERR!   dev @angular-eslint/schematics@"12.6.1" from the root project
npm ERR! 

Next installs upcoming version according to
https://docs.npmjs.com/cli/v7/commands/npm-dist-tag

**Comment by JamesHenry** [comment]
v13.0.0 of angular-eslint has been released which contains Angular 13 support and is picked up automatically by `ng add`.
