### ISSUE TITLE
README.md should advertise adding @angular-eslint/schematics as a dev dependency

### ISSUE THREAD

**Issue by nud** [angular-eslint/angular-eslint#80]
Schematics are used by ng-cli to upgrade from one version to the next automatically.

IMO it makes no sense to add it as a regular dependency while all the other packages of angular-eslint are added as dev dependencies.

**Comment by JamesHenry** [comment]
This appears to be the default behaviour of ng-add. I have added an additional step to the schematic to relocate the package to devDependencies as it runs
