### ISSUE TITLE
Found compatible package version: @angular-eslint/schematics@1.2.0 : latest is not pointing to 12.6.1

### ISSUE THREAD

**Issue by nagkumar** [angular-eslint/angular-eslint#801]
G:\DWork\angular\cshop>ng add @angular-eslint/schematics
Node.js version v17.0.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
i Using package manager: npm
√ Found compatible package version: @angular-eslint/schematics@1.2.0.
√ Package information loaded.

The package @angular-eslint/schematics@1.2.0 will be installed and executed.
Would you like to proceed? Yes

**Comment by JamesHenry** [comment]
v13.0.0 of angular-eslint has been released which contains Angular 13 support
