### ISSUE TITLE
After updating to 13.0.0 lint fails to load plugin 'eslint-plugin-import'

### ISSUE THREAD

**Issue by pavankjadda** [angular-eslint/angular-eslint#835]
**Description and reproduction of the issue**

- Clone the [repo](https://github.com/pavankjadda/ngx-cookie-service) 
- Install dependencies and run the lint command
```
$ npm install
$ npm run lint

```

and the result looks like

```
An unhandled exception occurred: Failed to load plugin 'eslint-plugin-import' declared in 'projects/ngx-cookie-service/.eslintrc.json » ../../.eslintrc.json#overrides[0] » plugin:@angular-eslint/ng-cli-compat': Package subpath './lib/util/glob-util' is not defined by "exports" in /Users/jaddap2/WebstormProjects/ngx-cookie-service/node_modules/eslint/package.json
See "/private/var/folders/1v/vz08n4553r56bprqn9gcmqtw7ggw12/T/ng-NfX4rs/angular-errors.log" for further details.


```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/utils`            | `13.0.0` |
| `ESLint`                           | `8.2.0` |
| `node`                             | `16.13.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 13.0.0
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.0
@angular-devkit/build-angular   13.0.0
@angular-devkit/core            13.0.0
@angular-devkit/schematics      13.0.0
@schematics/angular             13.0.0
ng-packagr                      13.0.0-rc.3
rxjs                            7.4.0
typescript                      4.4.4


```

- [ x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
What version of `eslint-plugin-import` do you have installed? I believe support for exports only landed in `2.25.x` so please ensure you are on that version and try again

**Comment by JamesHenry** [comment]
Oh sorry you linked a repo, so yes that's the issue here, `eslint-plugin-import` needs to be bumped. I will look into detecting if users are using that plugin and bumping as part of the `ng update` schematic

**Comment by JamesHenry** [comment]
Published 13.0.1 which will handle this automatically for eslint-plugin-import

**Comment by pavankjadda** [comment]
> Published 13.0.1 which will handle this automatically for eslint-plugin-import

Strange, I still see the error in `13.0.1`. Try this branch https://github.com/pavankjadda/ngx-cookie-service/tree/upgrade-angular-eslint

**Comment by michaelfaith** [comment]
> > Published 13.0.1 which will handle this automatically for eslint-plugin-import
> 
> Strange, I still see the error in `13.0.1`. Try this branch https://github.com/pavankjadda/ngx-cookie-service/tree/upgrade-angular-eslint

The fix only updated the migration that runs when you use `ng update`.  It bumps the version of `eslint-plugin-import`.  If you already ran `ng update`, you're not going to see any difference, and need bump the version manually like he said.

**Comment by JamesHenry** [comment]
Thanks @michaelfaith, that is correct

**Comment by pavankjadda** [comment]
My bad. Updated it. Works fine now. Thanks
