### ISSUE TITLE
[no-input-readonly] new feature - enforce skip readonly

### ISSUE THREAD

**Issue by splincode** [angular-eslint/angular-eslint#856]
**Our problem**:
https://github.com/TinkoffCreditSystems/taiga-ui/pull/1116

**Our fix**:

![image](https://user-images.githubusercontent.com/12021443/146335707-3ff2422c-04ca-49cb-a504-212341f76564.png)

**Solution**:

I think it would be cool if the linter checks things like this so that developers don't accidentally specify readonly.

```JSON
{
  "rules": {
    "@angular-eslint/no-input-readonly": ["error"]
  }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `13.0.0` |
| `@typescript-eslint/parser`        | `5.0.0` |
| `ESLint`                           | `8.0.0` |
| `node`                             | `16.0.0` |

**Comment by rafaeldolfe** [comment]
Isn't it strictly better to enforce readonly? There should be an opposite rule for this.

**Comment by CSchulz** [comment]
> Isn't it strictly better to enforce readonly? There should be an opposite rule for this.

readonly is not possible with strict input access modifiers. But we are developing a rule for checking write access on input fields.

**Comment by JamesHenry** [comment]
Hi Folks, Angular itself protects you from this these days:

<img width="1366" alt="image" src="https://github.com/angular-eslint/angular-eslint/assets/900523/8dc2dfa7-0720-49e4-ac31-8d7f1a94c96d">
