### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by JamesHenry** [angular-eslint/angular-eslint#86]
The tooling in this monorepo has been working pretty well for a while now and is already downloaded a lot.

**Updated to three items now that ESLint 7 and typescript-eslint 3 are out**

**Update 2: Please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief update on my personal situation, I cannot comment on the current availability of my co-contributors**

**Update 3 (Oct 2, 2020): Upgraded to latest Angular 10.1 and TypeScript 4**

In my view, we can promote this tooling to `1.0.0` once we have the following ~two~ three items in place:

-----

- [x] **Update to Angular 10, ESLint 7.x, TypeScript 3.9 and typescript-eslint 3.x**

  - Done as of `v0.1.0-beta.1`

-----

- [x] **Update to Angular 10.1, TypeScript 4 and typescript-eslint 4.x**

  - Done as of `v0.5.0-beta.1`

-----

~~- [ ] **Finalize recommended config**~~
~~- There is an initial recommended config in place as of `v0.0.1-alpha.32` (https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json) which is mostly a reflection of what is in the tslint.json that currently ships with the Angular CLI.~~
~~- @mgechev I would be grateful for your input on this one so that we capture yours and the rest of the Angular Team's latest and greatest recommendations~~

Update: this is not actually required for v1.0 as we will initially be focused on converting existing configs

-----

- [x] **Add schematic for migrating an Angular CLI project from TSLint to ESLint**
  - We can look into the possibility of integrating https://github.com/typescript-eslint/tslint-to-eslint-config within the execution of this schematic
  - cc @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Exciting! Some notes from the tslint-to-eslint-config side:
* We're _just_ about to hit 1.0 _([1.0 Ready 🚀 Milestone](https://github.com/typescript-eslint/tslint-to-eslint-config/milestone/1))_, at which point we can consider the 1.X API stable.
* I just set up an [Angular Support](https://github.com/typescript-eslint/tslint-to-eslint-config/projects/1) project on the tslint-to-eslint-config repo to help track where the rule converters are.
* There isn't a single clean function you can import, pass an object of settings, and get a result back. Feel free to file an issue on repo if you end up needing that instead of just the CLI.
    * [`main`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/899318829335eead390cdbb9dd42b6eb9c873881/src/cli/main.ts#L190) is the closest alternative right now. It takes in an `argv: string[]` (CLI options), but doesn't allow overriding dependencies such as the logger or file system.

**Comment by mgechev** [comment]
Based on the current configuration of Angular CLI, `tslint-to-eslint-config` produces the following ESLint config:

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "tsconfig.json",
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint",
        "@typescript-eslint/tslint"
    ],
    "rules": {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": "off",
        "@typescript-eslint/ban-types": [
            "error",
            {
                "types": {
                    "Object": {
                        "message": "Avoid using the `Object` type. Did you mean `object`?"
                    },
                    "Function": {
                        "message": "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."
                    },
                    "Boolean": {
                        "message": "Avoid using the `Boolean` type. Did you mean `boolean`?"
                    },
                    "Number": {
                        "message": "Avoid using the `Number` type. Did you mean `number`?"
                    },
                    "String": {
                        "message": "Avoid using the `String` type. Did you mean `string`?"
                    },
                    "Symbol": {
                        "message": "Avoid using the `Symbol` type. Did you mean `symbol`?"
                    }
                }
            }
        ],
        "@typescript-eslint/class-name-casing": "error",
        "@typescript-eslint/consistent-type-assertions": "error",
        "@typescript-eslint/indent": [
            "error",
            4,
            {
                "FunctionDeclaration": {
                    "parameters": "first"
                },
                "FunctionExpression": {
                    "parameters": "first"
                }
            }
        ],
        "@typescript-eslint/member-delimiter-style": [
            "error",
            {
                "multiline": {
                    "delimiter": "semi",
                    "requireLast": true
                },
                "singleline": {
                    "delimiter": "semi",
                    "requireLast": false
                }
            }
        ],
        "@typescript-eslint/member-ordering": "error",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-empty-interface": "error",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-assertion": "error",
        "@typescript-eslint/no-parameter-properties": "off",
        "@typescript-eslint/no-use-before-define": "off",
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/quotes": [
            "error",
            "single"
        ],
        "@typescript-eslint/semi": [
            "error",
            "always"
        ],
        "@typescript-eslint/triple-slash-reference": [
            "error",
            {
                "path": "always",
                "types": "prefer-import",
                "lib": "always"
            }
        ],
        "@typescript-eslint/type-annotation-spacing": "error",
        "@typescript-eslint/unified-signatures": "error",
        "arrow-body-style": "error",
        "camelcase": "error",
        "complexity": "off",
        "constructor-super": "error",
        "curly": "error",
        "dot-notation": "error",
        "eol-last": "error",
        "eqeqeq": [
            "error",
            "smart"
        ],
        "guard-for-in": "error",
        "id-blacklist": [
            "error",
            "any",
            "Number",
            "number",
            "String",
            "string",
            "Boolean",
            "boolean",
            "Undefined",
            "undefined"
        ],
        "id-match": "error",
        "import/no-deprecated": "warn",
        "jsdoc/check-alignment": "error",
        "jsdoc/check-indentation": "error",
        "jsdoc/newline-after-description": "error",
        "jsdoc/no-types": "error",
        "max-classes-per-file": "off",
        "max-len": [
            "error",
            {
                "code": 140
            }
        ],
        "new-parens": "error",
        "no-bitwise": "error",
        "no-caller": "error",
        "no-cond-assign": "error",
        "no-console": [
            "error",
            {
                "allow": [
                    "log",
                    "warn",
                    "dir",
                    "timeLog",
                    "assert",
                    "clear",
                    "count",
                    "countReset",
                    "group",
                    "groupEnd",
                    "table",
                    "dirxml",
                    "error",
                    "groupCollapsed",
                    "Console",
                    "profile",
                    "profileEnd",
                    "timeStamp",
                    "context"
                ]
            }
        ],
        "no-debugger": "error",
        "no-empty": "off",
        "no-eval": "error",
        "no-fallthrough": "error",
        "no-invalid-this": "off",
        "no-new-wrappers": "error",
        "no-restricted-imports": [
            "error",
            "rxjs/Rx"
        ],
        "no-shadow": [
            "error",
            {
                "hoist": "all"
            }
        ],
        "no-throw-literal": "error",
        "no-trailing-spaces": "error",
        "no-undef-init": "error",
        "no-underscore-dangle": "error",
        "no-unsafe-finally": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-var": "error",
        "object-shorthand": "error",
        "one-var": [
            "error",
            "never"
        ],
        "prefer-arrow/prefer-arrow-functions": "error",
        "prefer-const": "error",
        "quote-props": [
            "error",
            "as-needed"
        ],
        "radix": "error",
        "space-before-function-paren": [
            "error",
            {
                "anonymous": "never",
                "asyncArrow": "always",
                "named": "never"
            }
        ],
        "spaced-comment": [
            "error",
            "always",
            {
                "markers": [
                    "/"
                ]
            }
        ],
        "use-isnan": "error",
        "valid-typeof": "off",
        "@typescript-eslint/tslint/config": [
            "error",
            {
                "rules": {
                    "component-class-suffix": true,
                    "component-selector": [
                        true,
                        "element",
                        "app",
                        "kebab-case"
                    ],
                    "contextual-lifecycle": true,
                    "directive-class-suffix": true,
                    "directive-selector": [
                        true,
                        "attribute",
                        "app",
                        "camelCase"
                    ],
                    "import-spacing": true,
                    "no-conflicting-lifecycle": true,
                    "no-host-metadata-property": true,
                    "no-input-rename": true,
                    "no-inputs-metadata-property": true,
                    "no-output-native": true,
                    "no-output-on-prefix": true,
                    "no-output-rename": true,
                    "no-outputs-metadata-property": true,
                    "template-banana-in-box": true,
                    "template-no-negated-async": true,
                    "use-lifecycle-interface": true,
                    "use-pipe-transform-interface": true,
                    "whitespace": [
                        true,
                        "check-branch",
                        "check-decl",
                        "check-operator",
                        "check-separator",
                        "check-type",
                        "check-typecast"
                    ]
                }
            }
        ]
    }
};
```

With the following warnings:

```txt
8 ESLint rules behave differently from their TSLint counterparts:
  * no-console:
    - Custom console methods, if they exist, will no longer be allowed.
  * space-before-function-paren:
    - Option "constructor" is not supported by ESLint.
    - Option "method" is not supported by ESLint.
  * camelcase:
    - Leading and trailing underscores (_) in variable names will now be ignored.
    - ESLint's camel-case rule does not allow pascal or snake case variable names. Those cases are reserved for class names and static methods.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.

19 rules are not known by tslint-to-eslint-config to have ESLint equivalents:
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "component-class-suffix".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "component-selector".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "contextual-lifecycle".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "directive-class-suffix".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "directive-selector".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-conflicting-lifecycle".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-host-metadata-property".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-input-rename".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-inputs-metadata-property".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-native".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-on-prefix".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-rename".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-outputs-metadata-property".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "template-banana-in-box".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "template-no-negated-async".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "use-lifecycle-interface".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "use-pipe-transform-interface".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "whitespace".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "import-spacing".
```

We have everything except the last two rules, which are mostly formatting related so we can ignore.

**Comment by KingDarBoja** [comment]
Hi @mgechev 

Most of the missing rules have been integrated on the latest release of [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config/releases/tag/1.0.0-beta2).

**Comment by JamesHenry** [comment]
Thanks folks! I have updated the list to include ESLint 7.x and typescript-eslint 3.x, we may as well get any breaking changes out the way and there are performance improvements in typescript-eslint 3.x because it requires more a modern version of the TypeScript compiler (inline with Angular itself) and we dropped support for much older versions

**Comment by JamesHenry** [comment]
I've carved out some time this weekend to finalize some of these things

**Comment by wszydlak** [comment]
Hi, when are you planning to release stable version?

**Comment by Fafnur** [comment]
@JamesHenry Maybe you need help to release a stable version? I'm not sure I can do it, but I can try.

**Comment by JamesHenry** [comment]
Apologies (in particular to the tagged folks and) if you are subscribed to multiple issues/PRs you will see this copy pasted multiple times:

---

I have been going through a difficult time personally dealing with, amongst other things, the sudden death of my Dad. Open-source contributions have naturally had to take a back seat.

I really appreciate your continued patience on this and I will be doing my best to improve the speed at which PRs are merged in the near future. Hopefully this will then also allow more core contributors/maintainers to emerge from the community to work alongside @mgechev @wKoza @sfabriece @rafaelss95 and myself.

Thanks again for giving this project and the community your time and contribution.

**Comment by KingDarBoja** [comment]
My condolences for you and your family mate!

And yes, more contributors will emerge to help with development of this awesome package to lessen the workload of the current maintainers and bring support to each other as a whole. ❤️

**Comment by JamesHenry** [comment]
Thank you for all the well-wishes everyone, it really means a lot.

The latest version I just published `v0.1.0-beta.1` contains breaking changes and moves us to Angular 10, TypeScript 3.9, ESLint 7 and typescript-eslint 3.9

It should have fixed a few issues and gets us a step closer to being able to confidently declare the toolset as stable

**Comment by JamesHenry** [comment]
Major update to the builder and configuration in `v0.2.0-beta.1` - anybody that has been using this toolset so far, please read the updated docs in the README and take a look at PR #120 for when this change happened.

You will need to update your usage of the builder to match what we do in the integration-tests within this repo.

There is new (schematics) tooling available to take existing Angular CLI project and add all the right configuration files and architect target config for you, so you only need to worry about the actual ESLint config

**Comment by JamesHenry** [comment]
`v0.4.0-beta.1` has been released and contains BREAKING CHANGES.

I had a call with the Angular Tooling Team on how we can get this toolset merged into the Angular CLI itself.

As agreed with them, we have removed the required explicit usage of `tsconfig.eslint.json`. It offered a good way to solve any compilation issues in a transparent way, but it was effectively there to work around only one file: `environment.prod.ts` - all other files are naturally captured by the existing `tsconfig*.json` files for a project.

Therefore we have agreed to not require the extra config file just to work around this and will instead lean on the createDefaultProgram parser option from `@typescript-eslint`.

This PR also improves the schematics to do more automatically in a monorepo workspace, regardless of what order projects are converted in, and standardises around `.eslintrc.json` which is the most useful format to build tooling/migrations around and is a good equivalent of `tslint.json` for users.

If you have been using @angular-eslint before this release, please update your usage to match how the integration-tests example is set up.

Thanks 🙏

**Comment by JamesHenry** [comment]
I released `v0.5.0-beta.1` and `v0.5.0-beta.2` today.

On `v0.5.x` we are now using the latest Angular v10.1 and TypeScript v4 (as well as typescript-eslint v4).

I have had a chat with Josh around a path forward on the TSLint to ESLint config conversion logic and we opened an issue here to track: https://github.com/typescript-eslint/tslint-to-eslint-config/issues/729

I will scaffold the schematic which will wrap this updated logic on the angular-eslint side and then we will release a `1.0` RC once they are both ready

**Comment by JamesHenry** [comment]
The schematic for converting existing TSLint setups to ESLint is now underway and things are looking promising!

@JoshuaKGoldberg has been amazing as always and I hope to have an initial version out within the next few weeks, with us going to 1.0 not long after that.

**Comment by alvarocjunq** [comment]
Hi @JamesHenry 
Tks for all the hard work, it's really impressive =)
Do u have a new status about the v1?

**Comment by JamesHenry** [comment]
v1.0 will be released this week once the default schematic collection has been published (allowing you to generate additional projects without needing to first make them TSLint and then convert them).

What will that mean/represent?

It will represent that the toolset it feature complete enough to take over from TSLint + Codelyzer, and it will mean we are going to:
- start respecting semver
- publish changelogs using automated tooling
- release via automated tooling on a regular basis

However:
- It does **not** mean the toolset has become magically better vs 0.8.0-betas, I would strongly encourage you to try out the toolset as soon as possible.
- It does **not** mean we will not be making breaking changes in the near future (it just means they will cause major version bumps to happen post v1.0)

Long-term I think it will make sense to align the major version with Angular so that it is super easy for users to know which version range they should be using.

So, for now we will go for v1, anticipating that there will be several breaking changes to `angular-eslint` (particularly around preset configs) during the lifecycle of Angular v11, and then line up the version with Angular v12.

**Comment by JamesHenry** [comment]
v1.0.0 has now been released.

https://twitter.com/MrJamesHenry/status/1344996625899532294?s=20

Thanks everyone!

**Comment by jerone** [comment]
@JamesHenry Great news!

What is the instruction to update to the latest version (when you already had the beta installed)?

```shell
ng update @angular-eslint/builder @angular-eslint/eslint-plugin @angular-eslint/eslint-plugin-template @angular-eslint/schematics @angular-eslint/template-parser
```

**Comment by JamesHenry** [comment]
@jerone No special instructions or `ng update` process required for this.

You can see in the barebones release notes on github releases what the changes (mainly additions) were.

From now on, we will be respecting semver and full changelog/release note data will be generated from commits and `ng update` instructions will be provided if required
