### ISSUE TITLE
using externalSchematic with ng-add

### ISSUE THREAD

**Issue by betoobernal** [angular-eslint/angular-eslint#861]
**Description and reproduction of the issue**

Hi, I'm trying run `externalSchematic('@angular-eslint/schematics', 'ng-add', options)` before create my own workspace with other schematic `externalSchematic('@schematics/angular', 'ng-new', options);` consecutively. But when my directory or workspace is created, @angular-eslint/schematics don't know what is the project, I guess.

This works if run the schematics separately, so if I begin creating my workspace with a schematic, then `cd my-new-project`, then run my angular-eslint schematic.

Is the first idea possible?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `13.0.1` |
| `ESLint`                           | `8.5.0` |
| `node`                             | `16.10.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.2
Node: 16.10.0
Package Manager: npm 7.24.0
OS: darwin x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.2
@angular-devkit/core         13.1.2
@angular-devkit/schematics   13.1.2
@schematics/angular          13.1.2
typescript                   4.5.4


```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @betoobernal if I understand you correctly you want to ng-add _before_ you have created the workspace? This is conceptually not possible.

The intended behavior of ng-add, whether run via the CLI or via the schematics SDK as you do here, is to add packages to an existing workspace.
