### ISSUE TITLE
Angular CLI peer dependency version error @angular-eslint/schematics on Angular 12 projects

### ISSUE THREAD

**Issue by hardmaster92** [angular-eslint/angular-eslint#862]
**Description and reproduction of the issue**

Sorry if this is the wrong place but there wasn't an option for the schematics. I have a few Angular v12 projects. After migrating to node 16 (and npm 8) I started getting this error when trying to do a clean `npm install` (with deleted node_modules and package.json)
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ultimate-starter@0.0.0
npm ERR! Found: @angular/cli@12.2.14
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"^12.2.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 13.0.0 < 14.0.0" from @angular-eslint/schematics@13.0.1
npm ERR! node_modules/@angular-eslint/schematics
npm ERR!   dev @angular-eslint/schematics@"^13.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

After looking at the package.json file at `@angular-eslint/schematics` I saw this in the peer dependencies section
```json
"peerDependencies": {
    "@angular/cli": ">= 13.0.0 < 14.0.0"
  },
```

Which is not correct since according to the angular-eslint docs, angular v12 and above should use the latest angular-eslint.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `13.0.1` |
| `ESLint`                           | `8.5.0` |
| `node`                             | `16.13.1` |

```sh
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            13.1.2 (cli-only)
@angular-devkit/schematics      13.1.2 (cli-only)
@angular/cli                    13.1.2 (cli-only)
@schematics/angular             13.1.2 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Hi @hardmaster92, I'm sorry for not getting back to you sooner on this.

I'm not sure if this was just a timing thing with docs being updated, but the README says that the major version of angular-eslint and Angular should be aligned - i.e. v12 of angular-eslint goes with v12 of angular:

https://github.com/angular-eslint/angular-eslint#supported-angular-cli-versions

Certain things changed for v12 _and later_ but that does not mean that v12 should use the latest.

Again, apologies if this is not the original source of confusion if the README has changed since you last looked.

I'm going to close this for now, but please feel free to reopen if I have misunderstood
