### ISSUE TITLE
Conditional Complexity

### ISSUE THREAD

**Issue by cpfouche** [angular-eslint/angular-eslint#863]
The following bit of code gives this error: 'The conditional complexity 8 exceeds the defined limit 5 eslint@angular-eslint/template/conditional-complexity'.

`<div class="col" id="one-two-three-four-five-six-seven-eight-{{9}}">`

It doesn't have a conditional complexity of 8, of course. I think the code confuses hyphens in a string as subtractions in an equation.

**Comment by JamesHenry** [comment]
Thank you @cpfouche, I have addressed this in #986

**Comment by cpfouche** [comment]
Excellent! Thanks, @JamesHenry!
