### ISSUE TITLE
Angular 13.1 TypeScript 4.5 support

### ISSUE THREAD

**Issue by cveld** [angular-eslint/angular-eslint#865]
As mentioned here:
https://github.com/angular-eslint/angular-eslint/issues/715#issuecomment-1009652385

When running ng lint with Angular 13.1 I get the following warning:

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
YOUR TYPESCRIPT VERSION: 4.5.4

Angular 13.0 is running TypeScript 4.4 whereas Angular 13.1 is running TypeScript 4.5.

And indeed in package.json I see a mismatch in minor version numbers:

"dependencies": {
    "@angular/animations": "~13.1.0",
    "@angular/common": "~13.1.0",
    "@angular/compiler": "~13.1.0",
    "@angular/core": "~13.1.0",
    "@angular/forms": "~13.1.0",
    "@angular/platform-browser": "~13.1.0",
    "@angular/platform-browser-dynamic": "~13.1.0",
    "@angular/router": "~13.1.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.2",
    "@angular-eslint/builder": "13.0.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/schematics": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/cli": "~13.1.2",
    "@angular/compiler-cli": "~13.1.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^5.3.0",
    "@typescript-eslint/parser": "^5.3.0",
    "eslint": "^8.6.0",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }

What is your guidance?
Should I assume no support yet for 13.1 and stick to Angular 13.0 for now to be able to lint my source code?

**Comment by jqr91** [comment]
I have updated these two packages:

"@typescript-eslint/eslint-plugin": "^5.3.0",
"@typescript-eslint/parser": "^5.3.0"

to version 5.9.1 and everything works!

**Comment by JamesHenry** [comment]
@cveld Hopefully you saw @jqr91 message - very often it is fine to bump these packages yourself when it comes to patch and minor versions.
