### ISSUE TITLE
Not recognized "trackBy" directive after migrating to eslint 8.0.1

### ISSUE THREAD

**Issue by kzmonarski** [angular-eslint/angular-eslint#878]
Hello,
When I run `npx ng lint ` got ` Missing trackBy function in ngFor directive  @angular-eslint/template/use-track-by-function` although it's present in my source code.
My .eslintrc.json
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "ecmaVersion": 2017,
        "createDefaultProgram": true
      },
      "env": {
        "es6": true
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "plugins": [
        "eslint-plugin-rxjs"
      ],
      "rules": {
        "@angular-eslint/component-class-suffix": [
          "error",
          {
            "suffixes": [
              "Component"
            ]
          }
        ],
        "@angular-eslint/component-max-inline-declarations": "error",
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": [
              "kidos"
            ],
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/directive-class-suffix": [
          "error",
          {
            "suffixes": [
              "Directive"
            ]
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": [
              "kidos"
            ],
            "style": "camelCase"
          }
        ],
        "@angular-eslint/no-attribute-decorator": "error",
        "@angular-eslint/no-forward-ref": "off",
        "@angular-eslint/no-lifecycle-call": "error",
        "@angular-eslint/no-queries-metadata-property": "error",
        "@angular-eslint/prefer-output-readonly": "error",
        "@angular-eslint/use-component-selector": "off",
        "@angular-eslint/prefer-arrow-callback": "off",
        "@typescript-eslint/ban-types": "off",
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/dot-notation": "off",
        "@typescript-eslint/member-ordering": "off",
        "@typescript-eslint/no-unused-expressions": [
          "error",
          {
            "allowTernary": true
          }
        ],
        "@typescript-eslint/naming-convention": [
          "error",
          {
            "selector": "default",
            "format": [
              "camelCase"
            ],
            "leadingUnderscore": "allow",
            "trailingUnderscore": "allow"
          },
          {
            "selector": "variable",
            "format": [
              "camelCase",
              "UPPER_CASE"
            ],
            "leadingUnderscore": "allow",
            "trailingUnderscore": "allow"
          },
          {
            "selector": "classProperty",
            "format": [
              "UPPER_CASE",
              "camelCase"
            ],
            "leadingUnderscore": "allow",
            "trailingUnderscore": "allow"
          },
          {
            "selector": "enumMember",
            "format": [
              "UPPER_CASE",
              "camelCase"
            ]
          },
          {
            "selector": "typeLike",
            "format": [
              "PascalCase"
            ]
          },
          {
            "selector": [
              "classProperty",
              "objectLiteralProperty",
              "typeProperty",
              "classMethod",
              "objectLiteralMethod",
              "typeMethod",
              "accessor",
              "enumMember"
            ],
            "format": null,
            "modifiers": [
              "requiresQuotes"
            ]
          }
        ],
        "@typescript-eslint/prefer-for-of": "off",
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            "accessibility": "explicit"
          }
        ],
        "brace-style": [
          "error",
          "1tbs"
        ],
        "id-blacklist": "error",
        "max-len": [
          "error",
          140,
          {
            "ignorePattern": "^import\\s.+\\sfrom\\s.+;$",
            "ignoreTemplateLiterals": true,
            "ignoreStrings": true
          }
        ],
        "no-underscore-dangle": "off",
        "rxjs/no-subject-unsubscribe": "error",
        "space-before-function-paren": [
          "error",
          {
            "anonymous": "ignore",
            "named": "never",
            "asyncArrow": "ignore"
          }
        ],
        "prefer-arrow/prefer-arrow-functions": "off",
        "object-shorthand": "off",
        "quote-props": "off"
      }
    },
    **{
      "files": [
        "*.html"
      ],
      "parser": "@angular-eslint/template-parser",
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {
        "@angular-eslint/template/use-track-by-function": "error"
      }
    }**
  ]
}

My dev dependencies fragment in package.json
"devDependencies": {
    "@angular-eslint/builder": "^13.0.0",
    "@angular-eslint/eslint-plugin": "^13.0.0",
    "@angular-eslint/eslint-plugin-template": "^13.0.0",
    "@angular-eslint/schematics": "~12.6.1",
    "@angular-eslint/template-parser": "^13.0.0",
    "@angular/cli": "~12.2.14",
    "@angular/compiler-cli": "~12.2.15",
    "@types/node": "~16.11.18",
     "eslint": "^8.1.0",
    "@typescript-eslint/eslint-plugin": "~5.3.1",
    "@typescript-eslint/parser": "^5.10.0",
    "eslint-plugin-import": "~2.25.4",
    "eslint-plugin-jsdoc": "^37.0.3",
    "eslint-plugin-prefer-arrow": "~1.2.3",
    "eslint-plugin-rxjs": "^4.0.1",
.....
  }

**Comment by timdeschryver** [comment]
> although it's present in my source code

It would be great if you could show a code snippet.

**Comment by kzmonarski** [comment]
```
<div class="field grid"*ngFor="let rec of recipientWithDepartmentsArray; trackBy: trackByRecipientKey">
```
`  trackByRecipientKey(index, element: MailReceiverWithDepartments): string {
    return element.id;
  }`

**Comment by kzmonarski** [comment]
the issue is gone when used the syntax `[ngForTrackBy]=“trackByRecipientKey"` 
Can you make it possible to use both ?

**Comment by kzmonarski** [comment]
It was my fault not to reinstall all the project's npm modules.
