### ISSUE TITLE
Export getTemplateParserServices and ParserServices to allow writing custom template rules

### ISSUE THREAD

**Issue by reduckted** [angular-eslint/angular-eslint#888]
I would like to write my own template-based rules, but the `getTemplateParserServices` function and the `ParserServices` interface are not exported from `eslint-plugin-template`.

I've posted a workaround here: https://github.com/angular-eslint/angular-eslint/discussions/849#discussioncomment-2040750

It seems that you can safely define the `ParserServices` interface yourself and do some casting to get it from the context, but it would be great if they were exported instead.

**Comment by jerone** [comment]
@JamesHenry Would you consider exporting suggested methods.

This allows me to get ride of the clones in my custom plugin: 
- [jerone/eslint-plugin-angular-template-consistent-this@master/src/lib/external/get-parser-service.ts](https://github.com/jerone/eslint-plugin-angular-template-consistent-this/blob/master/src/lib/external/get-parser-service.ts)
- [jerone/eslint-plugin-angular-template-consistent-this@master/tests/external/test-helpers.ts](https://github.com/jerone/eslint-plugin-angular-template-consistent-this/blob/master/tests/external/test-helpers.ts)
- [jerone/eslint-plugin-angular-template-consistent-this@master/tests/external/rule-tester.ts](https://github.com/jerone/eslint-plugin-angular-template-consistent-this/blob/master/tests/external/rule-tester.ts)

**Comment by pumano** [comment]
@JamesHenry would love to see it exported too, because I have experience to create own custom rules, and want to do it same as your rules.

**Comment by JamesHenry** [comment]
@reduckted @jerone @pumano that makes sense I will happily accept a PR for this, many thanks
