### ISSUE TITLE
eslint-plugin and eslint-plugin-template rule url's are constructed wrong way

### ISSUE THREAD

**Issue by rubiesonthesky** [angular-eslint/angular-eslint#889]
eslint-plugin rule url is constructed as (note "template")

file: `packages/eslint-plugin/src/utils/create-eslint-rule.ts`

```typescript
export const createESLintRule = patchedRuleCreator(
  (ruleName) =>
    `https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin-template/docs/rules/${ruleName}.md`,
);
```
and eslint-plugin-template rule url is constructed as (note no "template")

file: `packages/eslint-plugin-template/src/utils/create-eslint-rule.ts`

```typescript
export const createESLintRule = patchedRuleCreator(
  (ruleName) =>
    `https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/docs/rules/${ruleName}.md`,
);
```

I would open PR but the code base is a little bit intimidating to me :)

**Comment by JamesHenry** [comment]
Thanks @rubiesonthesky not sure how we missed this for so long!
