### ISSUE TITLE
Linting the .eslintrc.js file itself

### ISSUE THREAD

**Issue by jonkoops** [angular-eslint/angular-eslint#91]
Also a bit of a question, but perhaps the `.eslintrc.js` itself should also be linted itself instead of only linting just the project files. Any thoughts about this?

**Comment by BO41** [comment]
What do you mean?
To check if rules exist, before running eslint?

**Comment by jonkoops** [comment]
@BO41 I mean that the file itself is checked to see if it matches the configuration, such as which quotation marks are used, etc.

**Comment by BO41** [comment]
That is not the scope of **angular**-eslint.
You should suggest this on the main [eslint project](https://github.com/eslint/eslint/)

**Comment by jonkoops** [comment]
So if I get this correctly `angular-eslint` does at this point not determine which files should be included for linting?

**Comment by BO41** [comment]
Yes, you decide which file eslint should lint with which rule and plugin.

Here is a basic example on how to let eslint use angular-eslint on ts and html files
https://github.com/angular-eslint/angular-eslint/blob/2bb695a640559413b4f2e7f1ab4bc52488083270/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js
