### ISSUE TITLE
Schema validation failed

### ISSUE THREAD

**Issue by andrefilimono** [angular-eslint/angular-eslint#92]
Hi!

When I'm running validation using the command `ng lint`, I'm always getting the following error message although the linting itself goes without errors:

```
Linting "app"...
All files pass linting.

Schema validation failed with the following errors:
  Data path "" should have required property 'eslintConfig'.
```

The `lint` section has the following content:

```
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "eslintConfig": ".eslintrc.json",
            "tsConfig": [
              "tsconfig.app.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
```

Packages: 
```
Angular version: `9.1.7`
 "@angular-eslint/builder": "0.0.1-alpha.32",
 "@angular-eslint/eslint-plugin": "0.0.1-alpha.32",
 "@angular-eslint/eslint-plugin-template": "0.0.1-alpha.32",
 "@angular-eslint/schematics": "0.0.1-alpha.32",
 "@angular-eslint/template-parser": "0.0.1-alpha.32",
 "@typescript-eslint/eslint-plugin": "2.31.0",
 "@typescript-eslint/parser": "2.31.0"
```

**Comment by andrefilimono** [comment]
This occurs only when I have multiple angular projects with lint section.

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Hi @andrefilimono, I see you've closed this, were you able to solve your issue?

**Comment by andrefilimono** [comment]
Hi, this issue actually is a duplicate of #109
