### ISSUE TITLE
Performance issues and angular-eslint schematics defaults

### ISSUE THREAD

**Issue by digeomel** [angular-eslint/angular-eslint#935]
I spent many days trying to figure out why after following your instructions our big monorepo project took 50+ minutes to lint. In the end, after lots of trials and errors, I managed to bring it down to 2 minutes, following the instructions in https://github.com/angular-eslint/angular-eslint#eslint-configs-and-performance
However, I am wonderin, since many devs seems to be facing these performance issues, and assuming the first thing to try would be this, why isn't this already taken care of by the schematics? I mean, why doesn't the builder create a separate `tsconfig.eslint.json` file with the default setting that you recommend above, and a `.eslintrc.json` file pointing to that instead of the main `tsconfig.json` file which seems to be creating the problems? Also, why aren't folders like `node_modules`, `.angular/cache`, `dist`, etc. already included in `.eslintignore`?
I think this would save a lot of time from many developers, and I cannot see why it's not the default.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `13.1.0` |
| `ESLint`                           | `8.9.0` |
| `node`                             | `14.18.3` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.2.3
Node: 14.18.3
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@schematics/angular             13.2.3
rxjs                            7.5.4
typescript                      4.5.5
```

- [✔] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
Sorry for not getting back to you on this sooner @digeomel

Hopefully you saw in v15 we changed our approach to scaffold a fast by default linting setup for users:

https://github.com/angular-eslint/angular-eslint/releases/tag/v15.0.0

I also wrote up guidance and explanations around the performance factors:

https://github.com/angular-eslint/angular-eslint/blob/4fee6b08060838ba004a8d20ee6cb43a781ff2c3/docs/RULES_REQUIRING_TYPE_INFORMATION.md
