### ISSUE TITLE
@angular-eslint/schematics NOT SUPPORTED error.

### ISSUE THREAD

**Issue by miguel-leon** [angular-eslint/angular-eslint#945]
Running `ng new test --skip-git --skip-install --collection=@angular-eslint/schematics` gives the following error `NOT SUPPORTED: keyword "id", use "$id" for schema ID`.

`ng --version`
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.0
Node: 16.14.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.0 (cli-only)
@angular-devkit/core         13.3.0 (cli-only)
@angular-devkit/schematics   13.3.0 (cli-only)
@schematics/angular          13.3.0 (cli-only)
```

**Comment by JamesHenry** [comment]
Please kindly follow the steps outlined at the top of the README (`ng new` then `ng add`):

<img width="949" alt="image" src="https://user-images.githubusercontent.com/900523/161432262-31b3074f-2db2-4dd2-995c-4dd7346f35b1.png">

Passing `@angular-eslint/schematics` as a value to `--collection` on `ng new` has not been supported for a long time
