### ISSUE TITLE
Templates: Support eslint-disable comments

### ISSUE THREAD

**Issue by LakMoore** [angular-eslint/angular-eslint#97]
I tried to use VS Code's fix/suggest on a template error and the following comment was added to the html template:
`  // eslint-disable-next-line @angular-eslint/template/banana-in-a-box`
This is obviously supposed to be:
`  <!-- eslint-disable-next-line @angular-eslint/template/banana-in-a-box -->`

Having a quick look at the source of both this project and es-lint itself I am struggling to see where this functionality comes from.  Can anyone fix or point me in the right direction to fix?

**Comment by Admiralfeb** [comment]
I believe any quick fixes themselves come from the eslint VSCode extension.

**Comment by bbarry** [comment]
Your code didn't come through. 

https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax

**Comment by LakMoore** [comment]
Thanks @bbarry.  I fixed my message.

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by meta72** [comment]
@LakMoore Did the html-comment `<!-- eslint-disable-next-line -->` work for you? I'm trying to disable the eslint rule `max-len`, but even with an html-comment it shows up as an error.

**Comment by JamesHenry** [comment]
I had a look into this and it appears that the Angular Compiler does not currently attach comments in the AST for us to surface to ESLint. I will take this up with the Angular Team to assess what work is required

**Comment by iameduardod** [comment]
@JamesHenry  following up on this error

**Comment by JamesHenry** [comment]
I have raised this with the Angular tooling team today as a broader point around an establishing a process around feedback/fix/feature requests for the `parseTemplate()` API we depend on from `@angular/compiler`

**Comment by JamesHenry** [comment]
I have opened a PR to add the capability we need to the Angular compiler: https://github.com/angular/angular/pull/41251

**Comment by JamesHenry** [comment]
If we can rekindle this then we can also enhance the VSCode ESLint plugin to add the right comments for HTML: https://github.com/microsoft/vscode-eslint/pull/857

I left a note on there about our use-case

**Comment by kambbado** [comment]
Is there a way to make this work?

I tried this and I'm getting an error
```
  <!-- eslint-disable-next-line -->
  <!--    test
  -->
```

An a few various and  I  keep getting the same error, any suggestions?

`An unhandled exception occurred: Cannot read property '0' of undefined`

**Comment by JamesHenry** [comment]
@kambbado Please open a new issue and follow the template, I cannot reproduce any issue based on the information you have given and commenting on closed issues is not a good way to get problems resolved
