### ISSUE TITLE
[no-negated-async] Does the reasoning behind this rule only apply when inside *ngIf?

### ISSUE THREAD

**Issue by josh18** [angular-eslint/angular-eslint#972]
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "@angular-eslint/template/no-negated": ["error"]
  }
}
```

```Typescript
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  editable$ = new Subject();

  constructor() {
    setTimeout(() => {
      this.editable$.next(true);
    }, 2000);
  }
}
```

```HTML
<input [disabled]="!(editable$ | async)">
```

Does the reasoning behind this rule apply in this example? Assuming that you want the input disabled until the observable emits. If so, what would be the proposed solution in this case? Like this?
```HTML
<input [disabled]="(editable$ | async) === false || (editable$ | async) === null">
```

[Stackblitz](https://stackblitz.com/edit/angular-ivy-rp1fen?file=src/app/app.component.ts)

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `13.1.0` |
| `@angular-eslint/template-parser`         | `13.1.0` |
| `@typescript-eslint/parser`               | `5.10.2` |
| `ESLint`                                  | `8.11.0` |
| `node`                                    | `16.13.2` |

```sh
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@schematics/angular             13.2.5
rxjs                            6.6.7
typescript                      4.5.5

```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by josh18** [comment]
The more I think about it, the less I understand this rule. The original reasoning was
> Angular's async pipes emit null initially, prior to the observable emitting
any values, or the promise resolving. This can cause negations, like
*ngIf="!(myConditional | async)" to thrash the layout and cause expensive
side-effects like firing off XHR requests for a component which should not
be shown.
https://github.com/mgechev/codelyzer/pull/317

As far as I can tell either way would have the same amount of renders. I think this rule only applies when used in `*ngIf` _and_ you want the condition to default to false until the observable emits. Maybe this happens regularly but it seems like you might get a lot of false positives (outside of `*ngIf` or you want it to default to true)?

Does that sound right or am I missing something?

**Comment by JamesHenry** [comment]
I certainly wouldn't recommend:

```html
<input [disabled]="(editable$ | async) === false || (editable$ | async) === null">
```

Because you would create two subscriptions to the Observable.

I don't think we can generalise about where and when this rule will apply 100% (we can say ngIf for sure, but I don't believe we can say _only_ ngIf).

It's not uncommon for there to be times where lint rules do not apply to specific instances, and for that reason you can suppress an error or warning inline for that specific usage by using an `eslint-disable` comment. I think that's what I would do in this specific case.

Make sure you are using valid HTML comments, i.e. , not the kind of comments you use in TypeScript code.
