### ISSUE TITLE
eslint-disable does not work in Angular templates

### ISSUE THREAD

**Issue by LakMoore** [angular-eslint/angular-eslint#98]
The following code in a template has no effect.
  

I can see where the disable directive is processed in es-lint and I don't think it can be re-used for templates.  I think this will need to be re-implemented in the parser in this project.  Any pointers, clues or ideas about where and how you want to achieve this?

**Comment by GerkinDev** [comment]
The mentioned code is absent. But I guess, from the title, that this issue is related to #97

**Comment by JamesHenry** [comment]
As @GerkinDev this report is currently incomplete, and probably best to handle as a duplicate of #97
