### ISSUE TITLE
Does `@nrwl/devkit` need to be a dep of builder?

### ISSUE THREAD

**Issue by griest024** [angular-eslint/angular-eslint#982]
Seem like it should be an optional dep at most.

https://github.com/angular-eslint/angular-eslint/blob/bd82092e92c6df623b168aa94c0750b3335f9434/packages/builder/package.json#L21-L23

**Comment by JamesHenry** [comment]
@griest024 what makes you say that? It is an integral piece of the implementation of the builder, and is executed at runtime of the code. With that understanding, I think it most certainly is a dependency

**Comment by damienwebdev** [comment]
@JamesHenry I came across this question independently to and @griest024 and I just so happen to work together:

```txt
frontend@0.0.0 /frontend
└─┬ @angular-eslint/builder@13.2.1
  └─┬ @nrwl/devkit@13.1.3
    └─┬ @nrwl/tao@13.1.3
      └─┬ nx@13.1.3
        └─┬ @nrwl/cli@14.1.7
          └─┬ nx@14.1.7
            └─┬ @swc/core@1.2.186
              └── @swc/core-linux-x64-gnu@1.2.186 
```
 
 I was investigating why my `node_modules` was blown up to `2.1GB` all of a sudden when we transitioned to eslint!
 
 ```txt
47M     node_modules/@daffodil
57M     node_modules/dgeni-packages
59M     node_modules/@nrwl
61M     node_modules/typescript
109M    node_modules/@angular-devkit
114M    node_modules/@angular
166M    node_modules/canvas
821M    node_modules/@swc
2.1G    node_modules/
```

Most of that is from `@swc`. While I can't say what to change, or why it `nx` is installed that deep in my package graph, I would much prefer to not have an extra GB of storage. Is there a slimmer package that could accomplish the same thing?

**Comment by JamesHenry** [comment]
@damienwebdev thanks for flagging this up, I believe in 14.2 of Nx being released this week, swc will no longer be pulled in by default
