### ISSUE TITLE
npm audit async

### ISSUE THREAD

**Issue by dertuerke** [angular-eslint/angular-eslint#985]
installed version "@angular-eslint/builder": "13.2.0",

```
# npm audit report

async  <3.2.2
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install @angular-eslint/builder@12.2.1, which is a breaking change
node_modules/async
node_modules/portfinder/node_modules/async
  jake  >=8.0.1
  Depends on vulnerable versions of async
  node_modules/jake
    ejs  >=3.1.2
    Depends on vulnerable versions of jake
    node_modules/ejs
      @nrwl/devkit  *
      Depends on vulnerable versions of ejs
      node_modules/@nrwl/devkit
        @angular-eslint/builder  >=12.2.2-alpha.0
        Depends on vulnerable versions of @nrwl/devkit
        node_modules/@angular-eslint/builder
  portfinder  0.1.0 || >=0.4.0
  Depends on vulnerable versions of async
  node_modules/portfinder
    webpack-dev-server  >=2.0.0-beta
    Depends on vulnerable versions of portfinder
    node_modules/webpack-dev-server
      @angular-devkit/build-angular  *
      Depends on vulnerable versions of webpack-dev-server
      node_modules/@angular-devkit/build-angular
```

**Comment by matiukhov** [comment]
Same problem. Helped for me: 
`npm audit --production`
But after install another dependency - problem come back

**Comment by dvalley56** [comment]
Same happened with me today after installing a library.  Removing it, deleting node_modules and package lock file didn't helped.

```

async  <3.2.2
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
No fix available
node_modules/async
  portfinder  0.1.0 || >=0.4.0
  Depends on vulnerable versions of async
  node_modules/portfinder
    webpack-dev-server  >=2.0.0-beta
    Depends on vulnerable versions of portfinder
    node_modules/webpack-dev-server
      @angular-devkit/build-angular  *
      Depends on vulnerable versions of @angular-devkit/build-webpack
      Depends on vulnerable versions of webpack-dev-server
      node_modules/@angular-devkit/build-angular
      @angular-devkit/build-webpack  *
      Depends on vulnerable versions of webpack-dev-server
      node_modules/@angular-devkit/build-webpack

5 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```
Would be glad if someone helped.

**Comment by emiliohell** [comment]
Same with a completely new angular project with fully updated packages.

**Comment by JamesHenry** [comment]
We need to distinguish what's going on here.

The OP is reporting `angular-eslint` v12, which is not the current major version of this project.

The vulnerability related to `async` is present in brand new Angular CLI workspaces without any involvement from `angular-eslint` at all, because as seen on these reports it is originating from `@angular-devkit/build-webpack`:

![image](https://user-images.githubusercontent.com/900523/163358894-b8a9408c-41d0-48a5-a3a3-f9a0ea48df11.png)

Please kindly report this to the Angular CLI folks. I will leave this open for now for visibility

**Comment by Frtrillo** [comment]
Have same issue. Got angular eslint v13 but wants to install esllint v12 to fix it:
# npm audit report

async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install @angular-eslint/builder@12.2.1, which is a breaking change
node_modules/jake/node_modules/async
  jake  >=8.0.1
  Depends on vulnerable versions of async
  node_modules/jake
    ejs  >=3.1.2
    Depends on vulnerable versions of jake
    node_modules/ejs
      @nrwl/devkit  *
      Depends on vulnerable versions of ejs
      node_modules/@nrwl/devkit
        @angular-eslint/builder  >=12.2.2-alpha.0
        Depends on vulnerable versions of @nrwl/devkit
        node_modules/@angular-eslint/builder

5 high severity vulnerabilities

**Comment by trazeris** [comment]
Hi!
I don't know for the brand new Angular CLI but the vulnerability is really present in the current version of angular/es-lint.

In [master package.json](https://github.com/angular-eslint/angular-eslint/blob/master/package.json) : 
`"@nrwl/devkit": "13.9.7",`
Also in angular-eslint/builder it is an older version still, with the same pb
`"@nrwl/devkit": "13.1.3"`

In [nrwl/devkit package.json @ 13.9.7, same for @13.1.3](https://github.com/nrwl/nx/blob/13.9.7/package.json):
`"ejs": "^3.1.5",`

In [ejs@3.1.5](https://github.com/mde/ejs/blob/v3.1.5/package.json)
`"jake": "^10.6.1"`

In [jake@10.6.1](https://github.com/jakejs/jake/blob/v10.6.1/package.json)
`"async": "0.9.x"`

async version 0.9.x will be reported by npm audit as OP reported.

**Comment by PeterHewat** [comment]
> We need to distinguish what's going on here.
> 
> The OP is reporting `angular-eslint` v12, which is not the current major version of this project.

Hi @JamesHenry ,
No OP is not reporting `angular-eslint` v12. They have installed v13 and it is the audit fix that suggests to downgrade a major version to "fix" this issue. And as @trazeris mentioned, it all boil down to a vulnerability in a dependency of a dependency:
@angular-eslint/builder@13.2.1 => @nrwl/devkit@13.1.3 => ejs@3.1.6 => jake@10.8.4 => async@0.9.2

**Comment by PeterHewat** [comment]
> We need to distinguish what's going on here.
> 
> The OP is reporting `angular-eslint` v12, which is not the current major version of this project.

Hi @JamesHenry ,
No, OP is not reporting `angular-eslint` v12. @dertuerke has installed v13 and it is the audit fix that suggests to downgrade a major version to "fix" this issue. And as @trazeris mentioned, it all boil down to a vulnerability in a dependency of a dependency:
@angular-eslint/builder@13.2.1 => @nrwl/devkit@13.1.3 => ejs@3.1.6 => jake@10.8.4 => async@0.9.2

All versions of async have a [Prototype Pollution](https://snyk.io/vuln/SNYK-JS-ASYNC-2441827) high vulnerability that has been fixed in 3.2.2
https://snyk.io/vuln/npm:async
It is up to jake to [update their dependency on async](https://github.com/jakejs/jake/issues/408).

**Comment by trazeris** [comment]
ejs has fixed their dependecy https://github.com/jakejs/jake/pull/411

**Comment by webdevelopland** [comment]
[Jake](https://github.com/jakejs/jake) fixed the vulnerability 6 days ago: https://github.com/jakejs/jake/issues/408

**Comment by webdevelopland** [comment]
`npm audit fix` fixes it

**Comment by JamesHenry** [comment]
angular-eslint v14.0.0 was just published and is available on npm and does not contain any negative results from `npm audit`

Please check out the release notes for guidance: https://github.com/angular-eslint/angular-eslint/releases/tag/v14.0.0

Many thanks 🙏
