### ISSUE TITLE
Improper fix for @angular-eslint/template/banana-in-a-box failes in conjuntion with lint-staged but works on CLI

### ISSUE THREAD

**Issue by IAMtheIAM** [angular-eslint/angular-eslint#99]
When applying the rule `'@angular-eslint/template/banana-in-a-box': "error"` it works fine when eslint is called from the CLI

But for some reason when `lint-staged` runs the same script using node `spawn`, it fails with 

```
  0:0  error  Parsing error: Template parse errors:
Parser Error: Unexpected token '=' at column 13 in [(locationId)=$event]
```

HTML
```
 <div ([ngModel])="locationId">
```

This gets auto fixed just fine using `eslint --fix` but fails with the error above on lint-staged, even though behind the scenes all it does it call the same command.

What it appears to do is incorrectly apply the "fix" to `locationId` instead of `ngModel`, .  It temporarily becomes
```
<div ([ngModel])="(locationId)"></div>
```
And then upon the second pass validation after the fix, it throws off the parser. I cannot understand why, any ideas?

**Comment by IAMtheIAM** [comment]
Until this is resolved, is there a way I can manually override the "fix" and disable it for this one rule, without affecting any other of `eslint`'s auto fix mechanics?

**Comment by JamesHenry** [comment]
Thanks for the report @IAMtheIAM, I have carved out some time this weekend to work on angular-eslint so I'll be looking into this then!

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Hi @IAMtheIAM, sorry that it has been a long time since this issue was last acknowledged, please can you provide a reproduction with the latest version of the tooling?

E.g. you could pull down the repo and use the lightweight Angular CLI workspace in the integration tests fixtures here: packages/integration-tests/fixtures/v1014-multi-project-manual-config

And add any extra deps like lint-staged that you may need, and push up a branch on your fork for others to pull down and repro.

Many thanks!

**Comment by JamesHenry** [comment]
@IAMtheIAM I'm going to close this as I haven't heard back from you, but please feel free to reopen if you can provide a reproduction/steps on how to reproduce.

The bare minimum I would need to investigate this is the configuration you are using for eslint, lint-staged and husky and all the versions of all the tools involved, but obviously the more you can give me the better.

Thanks 🙏
