### ISSUE TITLE
When migrating, all rules from TSLint are ignored and didn't transfer to ESLint

### ISSUE THREAD

**Issue by EPolishchuk** [angular-eslint/angular-eslint#990]
Trying to migrate from TSLint to ESLint, but when running
`ng g @angular-eslint/schematics:convert-tslint-to-eslint <project-name>`

got an error:
`Command failed: npm i -D tslint-to-eslint-config@2.4.0`

Only works if this package is installed manually. 

package | version
-- | --
@angular-eslint/eslint-plugin-template | 13.2.1
@angular-eslint/template-parser | 13.2.1
@typescript-eslint/parser | 5.17.0
ESLint | 8.13.0
node | v16.14.0

```
Angular CLI: 13.3.3
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin x64

Angular: 13.3.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/cli                    13.3.3
@angular/elements               13.3.3
@schematics/angular             13.3.3
ng-packagr                      13.3.1
rxjs                            6.6.7
typescript                      4.6.3
```

**Comment by EPolishchuk** [comment]
Okay, small update: it didn't work as intended: all current rules from tslint were dropped.

**Comment by JamesHenry** [comment]
@EPolishchuk please provide a clear reproduction of the issue. Either clear steps, or a minimal reproduction repo that can be run directly

**Comment by EPolishchuk** [comment]
> @EPolishchuk please provide a clear reproduction of the issue. Either clear steps, or a minimal reproduction repo that can be run directly

Here: https://github.com/EPolishchuk/test-app
You can take initial commit and try to update, not a single rule is saved. But don't have error about npm install =)
